### PR TITLE
Fix missing destination marker regression when using the Drop-in UI

### LINKED ISSUE #3459: The destination marker is missing when using the drop-in UI
**Android API:** Any
**Mapbox Navigation SDK version:** 1.0

### Steps to trigger behavior

 1. Run `NavigationViewActivity` example

### Expected behavior
image

### Actual behavior
image

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fixes #3459 

Regression from legacy https://github.com/mapbox/mapbox-navigation-android/pull/1622 not caught by recent refactors

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Show destination markers when using the Drop-in UI

### Implementation

`destination` `LiveData` wasn't firing off as `setValue` was never called.

Noting that the Drop-in UI doesn't fully support neither the _Free Drive_ use-case nor _Active Guidance_ / _Free Drive_ transitions. We should cut a ticket to keep track of these. @abhishek1508 could you when you have a chance?

## Testing

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

@JunDai could you run a quick test on your side and confirm dark and light destination markers are displayed and regression fixed?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

File: libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java [hunk 1]
```diff
@@ -8,9 +8,7 @@
 import org.junit.Test;
 
 import static org.mockito.ArgumentMatchers.any;
-import static org.mockito.Mockito.mock;
-import static org.mockito.Mockito.verify;
-import static org.mockito.Mockito.when;
+import static org.mockito.Mockito.*;
```
Comment (JunDai) [inline libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java:11]: do we also want to avoid the wildcard import in test code?

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationSymbolManager.java [hunk 2]
```diff
@@ -26,8 +27,12 @@
...
+    if (destinationSymbol != null) {
+      symbolManager.delete(destinationSymbol);
+      mapMarkersSymbols.remove(destinationSymbol);
+    }
     SymbolOptions options = createSymbolOptionsFor(position);
-    createSymbolFrom(options);
+    destinationSymbol = createSymbolFrom(options);
   }
 
   void addCustomSymbolFor(@NonNull SymbolOptions options) {
```
Comment (JunDai) [inline libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationSymbolManager.java:38]: do we also want to save the custom symbol to `destinationSymbol` here and so we can clear it later?

File: libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java [hunk 3]
```diff
@@ -42,7 +56,7 @@ public void removeAllMarkerSymbols_previouslyAddedMarkersRemoved() {
   }
 
   @Test
-  public void addDestinationMarkerFor_previouslyAddedMarkersRemoved() {
+  public void addCustomSymbolFor_symbolManagerCreatesSymbol() {
```
Comment (JunDai) [inline libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java:59]: similar to my previous comment, can we consider add a new test case, which verifies:
1. add custom symbol by `addCustomSymbolFor`
2. then `addDestinationMarkerFor`

to verify if the delete old symbol gets executed?

File: libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java (hunk 1 above)
Comment (Guardiola31337) [reply libnavigation-ui/src/test/java/com/mapbox/navigation/ui/map/NavigationSymbolManagerTest.java]: Checkstyle doesn't check that while Ktlint does. I put the explicit imports back though 👍

**Comment by Guardiola31337** [comment]
> discussed with @Guardiola31337 offline, the addCustomSymbol isn't an issue here.

https://github.com/mapbox/mapbox-navigation-android/pull/3462#discussion_r473233245 this is a great question though. At some point we should revisit the design / implementation of `NavigationSymbolManager` as there are some inconsistencies that cause confusion and complicate the overall interaction with it e.g. there are `add` methods for destination and custom markers (`addDestinationMarkerFor` and `addCustomSymbolFor`) but there are no methods to remove a single marker, only `removeAllMarkerSymbols` is available. Also `NavigationMapboxMap` exposes `addDestinationMarker`, `addCustomMarker` and `clearMarkers` but `NavigationView` only exposes `addMarker`.

cc @abhishek1508 for visibility
