### PR TITLE
Off-Route Bug Fixes

### LINKED ISSUE #603: Frequent rerouting on curved onramps
I've noticed that curved onramps such as the one below frequently trigger reroutes in the Android SDK. The GPS locations seem to match the road geometry in these cases.

image

Could this be something related to bearing?

cc @mapbox/navigation-android

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #603 #578 

Running into three scenarios where off-route events are triggered when the user location is not actually off-route:

###  1st Scenario:
- Increment the step index too quickly --> the step distance remaining, when we increment the step index, is a larger distance than our off-route radius --> off-route event
  - In this scenario, the bearing match check (user bearing vs. maneuver final bearing) we do is true + the `stepDistanceRemaining` is < the `maneuverZoneRadius` (set to 40)
  - We increase the step index by 1 and finishing creating the new `RouteProgress`
  - We then run the off route check on this new `RouteProgress` and what just was the `stepDistanceRemaining` now becomes our distance away from the step.  
    - Depending on our current radius of off-route, this will trigger `offRoute = true` 

### Fix
 - [x] The premature turn completion logic iOS has added should help here https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L814-L831 
     - We will now check the expected turn angle of the maneuver and if it's less than our threshold of `30`, we will wait for the step distance remaining to be `0` before we increment the step index.

### 2nd Scenario 
 - We don’t advance the step at all --> As we drive away from the step, an off-route is triggered as our distance away from the step increases 
   - The bearing match check (user bearing vs. maneuver final bearing) we do never returns true, so we never increment the step index  
   - This issue seems to be mostly caused by a bug in the directions API, but we should also ensure that our check `isCloseToUpcomingStep` returns true in this case and overrides the fact that the bearings never match.

### Fix
- [x] Ensure that `isCloseToUpcomingStep` returns true when we are off-route of the current step but within the off-route radius of the upcoming step.
     - If this happens, we need to increase the step index or updates will halt while we continue towards the upcoming step  
### 3rd Scenario
- We don't return early if we find that we are on-route at the beginning of our off-route checks.  If the first check doesn't have us exit early, only then should the logic check the following additional conditions:

1. Check to see if the user is moving away from the maneuver. (if yes, off route)
2. Check and see if the user is near a future step. (if yes, on route)
3. If the user is > the reroute threshold of that future step, then off route

- We currently check all of the off-route logic, every time and for on / off-ramps + roundabouts, even though we are considered on-route, this extra logic fires an off-route scenario at time.

### Fix 
- [x] This should be simply rearranging the off-route logic to return early if we find the interpolated location is within the off-route radius 

TODO:
- [x] Complete fixes for all three scenarios
- [x] Fix any other bugs that may result from changing this logic
- [x] Remove logging statements
- [x] Write unit tests to ensure the logic stands

cc @ericrwolfe please add or correct any of these findings / fixes if needed

### CODE REVIEW

**Comment by danesfeder** [comment]
Found and addressed an issue with the snapped `Location` bearing when the step distance remaining is `0`.  We were trying to measure 1 meter ahead of the current step and this wasn't possible at the end of the step.  This would cause the location to do a 180 and "flip-flop".  

Now, we look ahead and measure 1 meter into the upcoming step if the step distance remaining is `0`.

**Comment by danesfeder** [comment]
Java doc and tests need to be added - core logic is looking solid.

**Comment by danesfeder** [comment]
Tests + Javadoc added.  This should be good for 👀 now @devotaaabel @Guardiola31337

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java [hunk 1]
```diff
@@ -1,16 +1,331 @@
...
+  @Test
+  public void invalidOffRoute_onFirstLocationUpdate() throws Exception {
+    boolean isUserOffRoute = offRouteDetector.isUserOffRoute(
+      mockLocation, mockProgress, options, distances, mockCallback
+    );
+    assertFalse(isUserOffRoute);
+  }
+
+  @Test
+  public void validOffRoute_onMinimumDistanceBeforeReroutingPassed() throws Exception {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Generally is preferable having only 1 assertion per test 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=57

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java [hunk 2]
```diff
@@ -1,16 +1,331 @@
...
+    Location mapboxOffice = buildDefaultLocationUpdate(-77.0339782574523,38.89993519985637);
+    RouteProgress routeProgress = buildDefaultRouteProgress();
+
+    // First update sets the last re-route location
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Why comments?

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java (hunk 1 above)
Comment (Guardiola31337) [reply libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Why having comments in a test?

Comment (Guardiola31337) [reply libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Normally is good to structure the tests following the triple A 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40 http://wiki.c2.com/?ArrangeActAssert
If the `A`rrange part gets too long we should create factory or builder methods.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java [hunk 3]
```diff
@@ -1,16 +1,331 @@
...
+    boolean isUserOffRouteThirdTry = offRouteDetector.isUserOffRoute(
+      fourthLocationUpdate, routeProgress, options, distances, mockCallback
+    );
+    assertFalse(isUserOffRouteThirdTry);
+  }
+
+  /**
+   * @return {@link Location} with Mapbox DC coordinates
+   */
+  private static Location buildDefaultLocationUpdate(double lng, double lat) {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Why some builders are `static`?

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java [hunk 4]
```diff
@@ -95,47 +112,76 @@ private boolean validOffRoute(Location location, MapboxNavigationOptions options
...
       routeProgress.currentLegProgress().upComingStep().maneuver().location(),
-      futurePosition, TurfConstants.UNIT_METERS
+      currentPoint, TurfConstants.UNIT_METERS
     );
 
-    if (!recentDistancesFromManeuverInMeters.isEmpty()
-      && recentDistancesFromManeuverInMeters.peekLast()
-      - recentDistancesFromManeuverInMeters.peekFirst() < MINIMUM_BACKUP_DISTANCE_FOR_OFF_ROUTE
-      && recentDistancesFromManeuverInMeters.size() >= 3) {
+    if (!distancesAwayFromManeuver.isEmpty()
```
[the remark this answers is not in the document]
Comment (danesfeder) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java]: Going to hold on altering this logic - we can clean it up in another PR.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java (hunk 1 above)
Comment (danesfeder) [reply libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: Yeah some of these assertions need to be checked after multiple location updates given to the detector IMO - in order to properly check the detector is acting correctly after certain update scenarios

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Guardiola31337) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java]: @danesfeder now that we have tests covering that code, the refactoring should be pretty pleasant. I mean, having those tests as backup, we'll be pretty confident if we mess up 😅

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java (hunk 1 above)
Comment (Guardiola31337) [reply libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java]: The problem of having multiple assertions are:
- It's annoying to have to look at the stacktrace to know what's failing (which assertion failed?)
- You don't have information about the remaining assertions (because when an assertion fails it breaks the execution of the test)

That's why is preferable to have only 1 assertion per test and one test per scenario. Basically, if one of them fails you'll know at a glance what in the code might have caused that failure and in which part (class, method, etc.).

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java [hunk 5]
```diff
@@ -94,48 +105,96 @@ private boolean validOffRoute(Location location, MapboxNavigationOptions options
...
-      && recentDistancesFromManeuverInMeters.peekLast()
-      - recentDistancesFromManeuverInMeters.peekFirst() < MINIMUM_BACKUP_DISTANCE_FOR_OFF_ROUTE
-      && recentDistancesFromManeuverInMeters.size() >= 3) {
+    boolean hasDistances = !distancesAwayFromManeuver.isEmpty();
+    boolean validOffRouteDistanceTraveled = hasDistances && distancesAwayFromManeuver.peekLast()
+      - distancesAwayFromManeuver.peekFirst() < MINIMUM_BACKUP_DISTANCE_FOR_OFF_ROUTE;
+    boolean exceedsManeuverDistancesThreshold = validOffRouteDistanceTraveled
+      && distancesAwayFromManeuver.size() >= 3;
+
+    if (exceedsManeuverDistancesThreshold) {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java]: Great job 👏
This now reads nicely and you can understand what's going on 👍
