### PR TITLE
Fix PredictiveCache crash

### LINKED ISSUE #4603: Fix PredictiveCache crash
Fix `PredictiveCache` ConcurrentModificationException crash, cover it with tests

### PR DESCRIPTION
**Pull request by korshaknn**
### Description

Fix PredictiveCache crash
closes #4603 

`ArrayList`s were used to store nav controllers and options. Lists do not allow to iterate and modify the content.
At the same time we should prevent duplicates in the list.
It's enough to replace lists with sets.

### Changelog

```
<changelog>Fixed PredictiveCache ConcurrentModificationException crash, covered it with tests</changelog>
```

### CODE REVIEW

**Comment by LukasPaczos** [comment]
I see this failure locally that CI will probably catch in a moment:
```
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.mapbox.navigation.core.internal.cache.PredictiveCacheTests.controllers are recreated when navigator is recreated(PredictiveCacheTests.kt:136)
```

**Review by Guardiola31337 — APPROVED** [review]

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt [hunk 1]
```diff
@@ -7,17 +7,17 @@ import com.mapbox.navigator.PredictiveCacheController
...
+        mutableSetOf<PredictiveCacheController>()
+    internal val cachedMapsPredictiveCacheControllers =
         mutableMapOf<Any, MutableMap<String, PredictiveCacheController>>()
 
-    private val navPredictiveCacheLocationOptions =
-        mutableListOf<PredictiveCacheLocationOptions>()
-    private val mapsPredictiveCacheLocationOptions =
+    internal val navPredictiveCacheLocationOptions =
+        mutableSetOf<PredictiveCacheLocationOptions>()
+    internal val mapsPredictiveCacheLocationOptions =
```
Comment (LukasPaczos) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt:17]: This looks like a hack. We still try to concurrently modify the list, it just turns out that we are not adding any elements to it because all are already there. If that wasn't the case, we would see a crash again. This means that the loop itself in `init` is not built correctly in the first place. The loop shouldn't try adding new controllers to the list, they all are already there, it should only create a new native controller.

Comment (LukasPaczos) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt:17]: Clarifying - I'm not against using sets here, I just think we should refactor the loop as well.

Comment (korshaknn) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt:17]: there are no controllers, we clear them
```kotlin
 MapboxNativeNavigatorImpl.setNativeNavigatorRecreationObserver {
            cachedNavigationPredictiveCacheControllers.clear()
            cachedMapsPredictiveCacheControllers.clear()
            
            ...
}
```

after that we iterate over cached options and recreate controllers

```kotlin
 MapboxNativeNavigatorImpl.setNativeNavigatorRecreationObserver {
          ...
          navPredictiveCacheLocationOptions.forEach {
                createNavigationController(it)
            }
          ...
}
```

but, `fun createNavigationController(options: PredictiveCacheLocationOptions)`
caches `options` , so we iterate over collection and modify it.
it's a valid operation, but lists throw `ConcurrentModificationException`. To use it with lists, we need `Iterator` instance. But `Set` allows it without an `Iterator` and as a bonus we get non-duplicates

Comment (korshaknn) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt:17]: @LukasPaczos got you concern, will double check

Comment (korshaknn) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/PredictiveCache.kt:17]: @LukasPaczos ready

**Review by LukasPaczos — APPROVED** [review]
