### PR TITLE
ReRoute fix

### LINKED ISSUE #2501: IndexOutOfBounds when rerouting
Refs https://github.com/mapbox/mapbox-navigation-android/pull/2477.

When re-routing, the previous bearing's list might've been empty which will lead to the `IndexOutOfBoundsException`. We should fill it with nulls to match the number of coordinates instead.

```
2020-02-20 14:21:17.007 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.logistics_example, PID: 31056
    java.lang.IndexOutOfBoundsException: toIndex = 2
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.MapboxNavigation.buildAdjustedRouteOptions(MapboxNavigation.kt:498)
        at com.mapbox.navigation.core.MapboxNavigation.reRoute(MapboxNavigation.kt:474)
        at com.mapbox.navigation.core.MapboxNavigation.access$reRoute(MapboxNavigation.kt:105)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:454)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:80)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:30)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:258)
```

/cc @korshaknn

### PR DESCRIPTION
**Pull request by korshaknn**
## Description

Fixed bearings list on reRoute
Added tests for reRoute
Fixed flaky RemoveTilesTaslTest

closes #2501 

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### Goal

Please describe the PR goals. Just the stuff needed to implement the fix / feature and a simple rationale. It could contain many check points if needed

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 1]
```diff
@@ -212,6 +218,100 @@ class MapboxNavigationTest {
...
 
+    @Test
+    fun reRoute_called() {
+        val offRouteObserverSlot = slot<OffRouteObserver>()
+        verify { tripSession.registerOffRouteObserver(capture(offRouteObserverSlot)) }
+
+        offRouteObserverSlot.captured.onOffRouteStateChanged(true)
+
+        val optionsSlot = slot<RouteOptions>()
+        verify(exactly = 1) { directionsSession.requestRoutes(capture(optionsSlot), any()) }
```
Comment (Guardiola31337) [inline libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]:
```suggestion
        verify(exactly = 1) { directionsSession.requestRoutes(any(), any()) }
```

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 2]
```diff
@@ -212,6 +218,100 @@ class MapboxNavigationTest {
...
+    }
+
+    @Test
+    fun reRoute_called_with_null_bearings() {
```
Comment (Guardiola31337) [inline libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]: Minor thing.

Normally is good to structure the tests following the triple A 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40 http://wiki.c2.com/?ArrangeActAssert
If the `A`rrange part gets too long we should create factory or builder methods.

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 3]
```diff
@@ -212,6 +218,100 @@ class MapboxNavigationTest {
...
+        offRouteObserverSlot.captured.onOffRouteStateChanged(true)
+
+        val optionsSlot = slot<RouteOptions>()
+        verify(exactly = 1) { directionsSession.requestRoutes(capture(optionsSlot), any()) }
+
+        val options = optionsSlot.captured
+        val bearings = options.bearingsList()
+        val coordinates = options.coordinates()
+
+        assertEquals(coordinates.size, bearings!!.size)
```
Comment (Guardiola31337) [inline libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]: Open for discussion.

Generally is preferable having only 1 assertion per test 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=57

The problem of having multiple assertions are:
- It's annoying to have to look at the stacktrace to know what's failing (which assertion failed?)
- You don't have information about the remaining assertions (because when an assertion fails it breaks the execution of the test)

That's why is preferable to have only 1 assertion per test and one test per scenario. Basically, if one of them fails you'll know at a glance what in the code might have caused that failure and in which part (class, method, etc.).

I rarely write tests with multiple assertions (at least I try 😅), only if they're tearing apart the result object to verify everything e.g. if there's no `equals` (which is another problem although could happen if it's coming from a 3rd party library object) or if the assertions are atomic to the object (what we're asserting needs to be verified as whole). Is this one of these cases?

The same thing applies to the rest of the tests 👇

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt (hunk 1 above)
Comment (korshaknn) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]: fixed

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt (hunk 2 above)
Comment (korshaknn) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]: fixed

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt (hunk 3 above)
Comment (korshaknn) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt]: fixed, compare expected and actual lists
