### PR TITLE
Check for null camera engine before returning from MapboxNavigation

### LINKED ISSUE #842: Crash after close (terminatem, exit) navigation from notification bar
**Android API:6
**Mapbox Navigation SDK version:13.0.0-snapshot

### Steps to trigger behavior

 1. during the navigation (near to destination)
 2. close navigation from notification
 3. app sometime crashes!

### Actual behavior

I have fabric but because I tested lots of different version with same versioning number the last part of stacktrace is not correct:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.geojson.Point com.mapbox.services.android.navigation.v5.navigation.x.x.x(com.mapbox.services.android.navigation.v5.navigation.a.c)' on a null object reference
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.initialize(Unknown Source)
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.initialize(Unknown Source)
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera$1.onProgressChange(Unknown Source)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.addMilestoneEventListener(Unknown Source)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(Unknown Source)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

so because of that wrong stack trace on initialize I try to find the real stack trace and seems the problem is with navigationCamera-animateCameraFromLocation method:
Point targetPoint = cameraEngine.target(routeInformation);

that make sense because of input and output part of method. btw seems the camera is null because of termination from notification bar but there is a running thread in background that should be canceled or put some check before every call to changing camera

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #842 

Always return default `SimpleCamera` engine if one hasn't already been initialized.

Took a moment to clean up `MapboxNavigationTest` as well.

### CODE REVIEW

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 1]
```diff
@@ -28,199 +28,251 @@
...
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
     assertNotNull("should not be null", navigationWithOptions);
   }
 
   @Test
   public void voiceMilestone_onInitializationDoesGetAdded() throws Exception {
+    MapboxNavigation navigation = buildMapboxNavigation();
+
     assertTrue(navigation.getMilestones().get(0).getIdentifier() == VOICE_INSTRUCTION_MILESTONE_ID);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Normally is good to structure the tests following the triple A 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40 http://wiki.c2.com/?ArrangeActAssert

Here we're including the `Act` inside the `Assert`. It'd be great to have them separated and take advantage of giving great names to variables so it's easy to understand what's going on.

This applies to other tests included in `MapboxNavigationTest`.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 2]
```diff
@@ -28,199 +28,251 @@
...
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
+    assertNull(navigationWithOptions.getFasterRouteEngine());
   }
 
   @Test
   public void addMilestone_milestoneDidGetAdded() throws Exception {
+    MapboxNavigation navigation = buildMapboxNavigation();
+
     Milestone milestone = new StepMilestone.Builder().build();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: IMO These two lines of code belongs to the `Arrange` part. 

This applies to other tests included in `MapboxNavigationTest`.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 3]
```diff
@@ -28,199 +28,251 @@
...
     assertEquals(0, navigationWithOptions.getMilestones().size());
   }
 
   @Test
   public void removeMilestone_correctMilestoneWithIdentifierGetsRemoved() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
     Milestone milestone = new StepMilestone.Builder().setIdentifier(5678).build();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: What about using a well-named variable for `5678` reflecting what's useful for here? Maybe `theMilestone`?

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 4]
```diff
@@ -28,199 +28,251 @@
...
   @Test
   public void removeMilestone_noMilestoneWithIdentifierFound() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
     navigationWithOptions.addMilestone(new StepMilestone.Builder().build());
-    assertEquals(1, navigationWithOptions.getMilestones().size());
+
     navigationWithOptions.removeMilestone(5678);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Same here ☝️ but reflecting that the milestone was not found.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 5]
```diff
@@ -28,199 +28,251 @@
...
+
     assertEquals(1, navigationWithOptions.getMilestones().size());
   }
 
   @Test
   public void getLocationEngine_returnsCorrectLocationEngine() throws Exception {
+    MapboxNavigation navigation = buildMapboxNavigation();
     LocationEngine locationEngine = mock(LocationEngine.class);
     LocationEngine locationEngine2 = mock(LocationEngine.class);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: We should avoid adding "numbers" to variable names. Could we refactor-rename adding more context so it'll be easier to read and understand what's going on in the test?

**Comment by danesfeder** [comment]
@Guardiola31337 addressed, thanks!

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 6]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void voiceMilestone_onInitializationDoesGetAdded() throws Exception {
-    assertTrue(navigation.getMilestones().get(0).getIdentifier() == VOICE_INSTRUCTION_MILESTONE_ID);
+    MapboxNavigation navigation = buildMapboxNavigation();
+
+    int identifier = navigation.getMilestones().get(0).getIdentifier();
+
+    assertEquals(identifier, VOICE_INSTRUCTION_MILESTONE_ID);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: This should be the other way around, "expected" value 👉 `VOICE_INSTRUCTION_MILESTONE_ID` which would be better represented using the literal value instead of using the constant (👀 [Expect Literals](https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=61)), "actual" value 👉 `identifier`.
The same thing happens in `bannerMilestone_onInitializationDoesGetAdded` test 👇

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 7]
```diff
@@ -28,199 +28,257 @@
...
 
 
   @Test
   public void defaultMilestones_onInitializationDoNotGetAdded() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
     assertEquals(0, navigationWithOptions.getMilestones().size());
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: 👀 https://github.com/mapbox/mapbox-navigation-android/pull/866#discussion_r182155984
`navigationWithOptions.getMilestones().size()` is the `Act` here.
This applies to other tests included in `MapboxNavigationTest` 👇

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 8]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void addMilestone_milestoneOnlyGetsAddedOnce() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
     Milestone milestone = new StepMilestone.Builder().build();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: `Milestone milestone = new StepMilestone.Builder().build();` should be in the `Arrange` part.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 9]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void removeMilestone_milestoneDidGetRemoved() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
     Milestone milestone = new StepMilestone.Builder().build();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]:
```
Milestone milestone = new StepMilestone.Builder().build();
navigationWithOptions.addMilestone(milestone);
```
Should be in the `Arrange` part.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 10]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void removeMilestone_milestoneDoesNotExist() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+
     Milestone milestone = new StepMilestone.Builder().build();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]:
```
Milestone milestone = new StepMilestone.Builder().build();
navigationWithOptions.addMilestone(new StepMilestone.Builder().build());
```
Should be in the `Arrange` part.
We could take advantage of the naming here to understand clearer what's going on. Like naming `new StepMilestone.Builder().build()` as `inexistentMilestone` for example.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 11]
```diff
@@ -28,199 +28,257 @@
...
     assertEquals(1, navigationWithOptions.getMilestones().size());
   }
 
   @Test
   public void removeMilestone_nullRemovesAllMilestones() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
     navigationWithOptions.addMilestone(new StepMilestone.Builder().build());
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: We could extract this block of code into a `private` method called `addABunchOfMilestones` for example. It'd reflect better our intention and it'd be clearer and easier to understand.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 12]
```diff
@@ -28,199 +28,257 @@
...
     assertEquals(0, navigationWithOptions.getMilestones().size());
   }
 
   @Test
   public void removeMilestone_noMilestoneWithIdentifierFound() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
     navigationWithOptions.addMilestone(new StepMilestone.Builder().build());
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: We could take advantage of the naming here to understand clearer what's going on. Like naming `new StepMilestone.Builder().build()` as `aMilestone` for example and rename `removedMilestoneIdentifier` with `inexistentMilestoneIdentifier` for example.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 13]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void removeMilestone_correctMilestoneWithIdentifierGetsRemoved() throws Exception {
     MapboxNavigationOptions options = MapboxNavigationOptions.builder().defaultMilestonesEnabled(false).build();
-    MapboxNavigation navigationWithOptions = new MapboxNavigation(mock(Context.class),
-      ACCESS_TOKEN, options, mock(NavigationTelemetry.class), mock(LocationEngine.class));
-    Milestone milestone = new StepMilestone.Builder().setIdentifier(5678).build();
+    MapboxNavigation navigationWithOptions = buildMapboxNavigationWithOptions(options);
+    int removedMilestoneIdentifier = 5678;
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: IMO `removedMilestoneIdentifier` is not a good name here 👀 https://github.com/mapbox/mapbox-navigation-android/pull/866#discussion_r182158018

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 14]
```diff
@@ -28,199 +28,257 @@
...
   }
 
   @Test
   public void getLocationEngine_returnsCorrectLocationEngine() throws Exception {
+    MapboxNavigation navigation = buildMapboxNavigation();
     LocationEngine locationEngine = mock(LocationEngine.class);
-    LocationEngine locationEngine2 = mock(LocationEngine.class);
+    LocationEngine locationEngineInstanceNotUsed = mock(LocationEngine.class);
+
     navigation.setLocationEngine(locationEngine);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Should be in the `Arrange` part 👀 `getLocationEngine_returnsCorrectLocationEngine` is telling us what's the `Act` here `getLocationEngine`.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 15]
```diff
@@ -28,199 +28,257 @@
...
+    assertNotSame(locationEngineInstanceNotUsed, navigation.getLocationEngine());
     assertEquals(locationEngine, navigation.getLocationEngine());
   }
 
   @Test
   public void endNavigation_doesSendFalseToNavigationEvent() throws Exception {
+    MapboxNavigation navigation = buildMapboxNavigation();
     NavigationEventListener navigationEventListener = mock(NavigationEventListener.class);
+
     navigation.addNavigationEventListener(navigationEventListener);
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Same here ☝️
This applies to other tests included in `MapboxNavigationTest` 👇

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 16]
```diff
@@ -28,199 +28,257 @@
...
   public void setSnapEngine_doesReplaceDefaultEngine() throws Exception {
-    Snap snap = navigation.getSnapEngine();
-    assertTrue(snap instanceof SnapToRoute);
-    snap = mock(Snap.class);
+    MapboxNavigation navigation = buildMapboxNavigation();
+
+    Snap snap = mock(Snap.class);
     navigation.setSnapEngine(snap);
+
     assertTrue(!(navigation.getSnapEngine() instanceof SnapToRoute));
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: What about using `assertFalse` instead?

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 17]
```diff
@@ -28,199 +28,257 @@
...
   public void setOffRouteEngine_doesReplaceDefaultEngine() throws Exception {
-    OffRoute offRoute = navigation.getOffRouteEngine();
-    assertTrue(offRoute instanceof OffRouteDetector);
-    offRoute = mock(OffRoute.class);
+    MapboxNavigation navigation = buildMapboxNavigation();
+
+    OffRoute offRoute = mock(OffRoute.class);
     navigation.setOffRouteEngine(offRoute);
+
     assertTrue(!(navigation.getOffRouteEngine() instanceof OffRouteDetector));
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Same here ☝️
