### PR TITLE
MapboxNavigationTelemetry: logging user feedback creating if failed

### LINKED ISSUE #3865: Logging session
2Tap feedback flow cannot be sent when TripSession has been stopped. We should logging that to notify external developers that it might happen. 

Ref https://github.com/mapbox/mapbox-navigation-android/issues/3853

**cc** @LukasPaczos @Guardiola31337

### PR DESCRIPTION
**Pull request by RingerJK**
### Description
MapboxNavigationTelemetry: logging user feedback creating if failed

Closes #3865

### CODE REVIEW

**Review by Lebedinsky — APPROVED** [review]

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 1]
```diff
@@ -274,6 +274,13 @@ internal object MapboxNavigationTelemetry :
                 }
                 onEventUpdated?.let { it(feedbackEvent) }
             }
+        } else {
+            logger?.e(
+                TAG,
+                Message(
+                    "Cannot create User feedback if session is stopped or data is not initialized"
```
Comment (LukasPaczos) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:281]:
```suggestion
                    "User Feedback event creation failed. The event can only be created in active guidance (trips session started and route available)."
```

**Review by LukasPaczos — APPROVED** [review]

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 2]
```diff
@@ -274,6 +274,13 @@ internal object MapboxNavigationTelemetry :
                 }
                 onEventUpdated?.let { it(feedbackEvent) }
             }
+        } else {
+            logger?.e(
+                TAG,
+                Message(
+                    "User Feedback event creation failed. The event can only be created in active guidance (trips session started and route available)."
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:281]: @LukasPaczos 🤔 
```suggestion
                    "User Feedback event creation failed. The event can only be created in active guidance (trips session started and route is available)."
```
