### PR TITLE
Fix issue 2732: stop tripSession when MapboxNavigation destroy

### LINKED ISSUE #2732: NavigationViewActivity doesn't end the trip session when clicking on the back button
When testing the `examples` test app noticed that `NavigationViewActivity` doesn't end the trip session after clicking on the back button 👇 Is that on purpose / by design? We should 👀 the rest of the examples and be consistent.

navigation_view_activity_end_trip_session

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2732 

When NavigationView destroys itself, we need to make sure the Notification goes away.
It's in legacy code, but not in V1.0 SDK.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### CODE REVIEW

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 1]
```diff
@@ -286,10 +286,9 @@ constructor(
         mainJobController.scope.launch {
             Log.d(TAG, "onDestroy")
             MapboxNavigationTelemetry.unregisterListeners(this@MapboxNavigation)
-            ThreadController.cancelAllNonUICoroutines()
-            ThreadController.cancelAllUICoroutines()
```
Comment (JunDai) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:290]: inside tripSession.stop already cancel all the coroutines jobs.

Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:290]: The ones canceled in `MapboxTripSession#stop` are local to `MapboxTripSession` i.e. we should leave these as they're stopping the "root" ones. Also I think even if they were already canceled calling these wouldn't be harmful, good to be precautious 😅

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 2]
```diff
@@ -286,10 +286,9 @@ constructor(
...
             directionsSession.shutDownSession()
             directionsSession.unregisterAllRoutesObservers()
+            tripSession.stop()
```
Comment (Guardiola31337) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:291]: Great catch!

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 1 above)
Comment (JunDai) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:290]: it's reverted.
