### PR TITLE
Fix notification instruction not updated for arrive maneuver

### LINKED ISSUE #1956: Notification instruction not updated for arrive maneuver
Found 👇 while testing

you_have_arrive_maneuver_banner

you_have_arrived_maneuver_notification_not_updated

As seen in the screenshots the Notification is displaying `"You will arrive"` when it should be `"You have arrived"`.

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fixes #1956 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Goal here is to ensure that both banner and notification instructions show the correct text 

### Implementation

Refactor `MapboxNavigationNotification` to use the current `BannerInstruction` (NN) from the `RouteProgress` instead of 👀 `LegStep` (`RouteProgress#currentLegProgress()#currentStep()`) which may be not properly updated / refreshed 

## Screenshots or Gifs

**Before**

you_have_arrive_maneuver_banner

you_have_arrived_maneuver_notification_not_updated

**After**

you_have_arrive_maneuver_banner_fixed

you_have_arrived_maneuver_notification_updated

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

cc @danesfeder

### CODE REVIEW

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java [hunk 1]
```diff
@@ -226,20 +233,20 @@ private void unregisterReceiver(Context applicationContext) {
     }
   }
 
-  private void updateInstructionText(LegStep step) {
-    if (hasInstructions(step) && (instructionText == null || newInstructionText(step))) {
-      instructionText = step.bannerInstructions().get(0).primary().text();
-      collapsedNotificationRemoteViews.setTextViewText(R.id.notificationInstructionText, instructionText);
-      expandedNotificationRemoteViews.setTextViewText(R.id.notificationInstructionText, instructionText);
+  private void updateInstructionText(BannerInstruction bannerInstruction) {
+    if (bannerInstruction != null && (instructionText == null || newInstructionText(bannerInstruction))) {
```
Comment (nesfeder) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java]: @Guardiola31337 💯

**Comment by Guardiola31337** [comment]
Thanks for taking a look at this @danesfeder 🙇

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java (hunk 1 above)
Comment (abhishek1508) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java]: 👍
