### PR TITLE
Fix HybridRouter test

### LINKED ISSUE #3221: MapboxHybridRouterTest#whenConnectionAppearedRoutersSwitched flaky test
While working on https://github.com/mapbox/mapbox-navigation-android/pull/3204 CI ❌ https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/7383/workflows/0a0563ef-b4a8-4623-95f8-77d096599aa8/jobs/28226/steps because of `MapboxHybridRouterTest#whenConnectionAppearedRoutersSwitched` flaky test 👀 

```
> Task :libdirections-hybrid:testReleaseUnitTest

com.******.navigation.route.hybrid.MapboxHybridRouterTest > whenConnectionAppearedRoutersSwitched FAILED
    java.lang.AssertionError at MapboxHybridRouterTest.kt:158

12 tests completed, 1 failed

> Task :libdirections-hybrid:testReleaseUnitTest FAILED
```

cc @korshaknn

### PR DESCRIPTION
**Pull request by korshaknn**
## Description

closes #3221 
`delay` removed. Channel is not used to change `NetworkStatus`. It is changed directly with `internal` fun.

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make 1.0-core-update-api` (Core) / `$> make 1.0-ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

File: libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt [hunk 1]
```diff
@@ -48,16 +49,18 @@ class MapboxHybridRouter(
...
-            }
-        }, networkStatusService::cleanup)
+        networkStatusJob = jobControl.scope.monitorChannelWithException(
+            networkStatusService.getNetworkStatusChannel(),
+            ::onNetworkStatusChanged,
+            networkStatusService::cleanup
+        )
+    }
+
+    internal suspend fun onNetworkStatusChanged(networkStatus: NetworkStatus) {
```
Comment (Guardiola31337) [inline libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt:59]:
```suggestion
    internal fun onNetworkStatusChanged(networkStatus: NetworkStatus) {
```

> Redundant 'suspend' modifier

File: libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouterTest.kt [hunk 2]
```diff
@@ -224,11 +223,7 @@ class MapboxHybridRouterTest {
     private suspend fun disableNetworkConnection() = networkConnected(false)
 
     private suspend fun networkConnected(networkConnected: Boolean) {
-        channel.offer(NetworkStatus(networkConnected))
-        // channel is listened with a coroutine. When channel is empty, coroutine suspends
-        // until channel has a new value. Need some small delay to give coroutine time to wake up
-        // and handle a value.
-        delay(10)
```
Comment (kmadsen) [inline libdirections-hybrid/src/test/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouterTest.kt:231]: 🎈

File: libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt (hunk 1 above)
Comment (korshaknn) [reply libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt:59]: it's not redundant, it has to be `suspend`, because passed `predicate` is suspend
```
fun <T> CoroutineScope.monitorChannelWithException(
    channel: ReceiveChannel<T>,
    predicate: suspend (T) -> Unit,
    onCancellation: (() -> Unit) = {}
): Job
```

**Comment by korshaknn** [comment]
@Guardiola31337 
we still test `job - channel` integration in the context of `cancellation`:
```
@Test
    fun networkStatusService_cleanup_calledOnChannelClose() = runBlocking {
        channel.close()

        hybridRouter.networkStatusJob.join()

        verify(exactly = 1) { networkStatusService.cleanup() }
    }
```
but you are right, coroutine doesn't receive values from the channel, we pass it directly to the callback function.

File: libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt (hunk 1 above)
Comment (Guardiola31337) [reply libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt:59]: Interesting the IDE doesn't catch this one 🤔

Comment (korshaknn) [reply libdirections-hybrid/src/main/java/com/mapbox/navigation/route/hybrid/internal/MapboxHybridRouter.kt:59]: yep, IDE marks it redundant
