### PR TITLE
changed navigationActivity name and added a few routeStep test

### LINKED ISSUE #60: App crashes on end of navigation if speed is higher than step length
**Platform:** Android 7.1.2
**SDK version:** Latest SNAPSHOT

### Steps to trigger behavior

 1. Open the `RerouteActivity.java`
 2. Set speed of the MockEngine to `60` on [this line](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java#L78)
(2.1. Set destination coordinate to be sure you'll experience the bug: `-87.6910, 41.8542`)
 3. Reach the end of the path and observe crash

I thought this was specific to the mock engine but actually if I'm right this could happen in real life if car is going fast and GPS signal is slow I guess.

### Expected behavior
Navigation should end nicely

### Actual behavior
App crash with an NPE

### PR DESCRIPTION
**Pull request by cammace**
Closes #60

### CODE REVIEW

**Comment by cammace** [comment]
This PRs ready for your review @zugaldia

File: navigation/libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/models/RouteStepProgressTest.java [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+  public void getDistanceRemaining_equalsZeroAtEndOfStep() {
+    RouteStepProgress routeStepProgress = new RouteStepProgress(firstLeg, 3,
+      firstLeg.getSteps().get(4).getManeuver().asPosition());
+
+    Assert.assertEquals(0, routeStepProgress.getDistanceRemaining(), BaseTest.DELTA);
+  }
+
+  @Test
+  public void getDistanceTraveled() {
+
```
Comment (zugaldia) [inline navigation/libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/models/RouteStepProgressTest.java]: Looks like some tests didn't get pushed?

Comment (cammace) [inline navigation/libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/models/RouteStepProgressTest.java]: Removed the empty test, they were generated when creating the class (should be re-added later on)
