### PR TITLE
Bug fix. The route clearing API was not including the restricted road…

### LINKED ISSUE #4253: Restricted road source not cleared on map with rest of route line.
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

Restricted road sections are enabled and visible.
When the route line is cleared via the API the rendered result isn't clearing the restricted road sections.

### Expected behavior

The line representing the restricted section should be cleared along with the rest of the route line.

### Actual behavior

The line is still visible.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Fixes #4253 by including the restricted road sections in the clear route API call and rendering.

### Changelog
```
<changelog>Bug fix for restricted road sections not getting cleared when calling API.</changelog>
```

### CODE REVIEW

File: libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt [hunk 1]
```diff
@@ -1171,4 +1190,11 @@ class MapboxRouteLineViewTest {
         assertEquals(Visibility.VISIBLE, result)
         unmockkObject(MapboxRouteLineUtils)
     }
+
+    private fun getEmptyFeature(): Feature {
+        return Feature.fromJson(
+            "{\"type\":\"Feature\",\"id\":\"${UUID.randomUUID()}\"," +
```
Comment (RingerJK) [inline libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt:1196]: avoid using random values in tests as it non-determine behavior 
```suggestion
            "{\"type\":\"Feature\",\"id\":\"1\"," +
```

Comment (cafesilencio) [reply libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/route/line/api/MapboxRouteLineViewTest.kt:1196]: That's exactly the reason a random number is being used here.

**Review by Guardiola31337 — APPROVED** [review]
