### PR TITLE
Fix backwards instructions in left-side driving scenarios

### LINKED ISSUE #396: Android: Incorrect Direction Images
Being In The UK we drive on the left side of the road, i approached a rounder-bout well testing the Navigation yesterday, the Instructions told me to `At the rounder-bout take the second exit`

Below is the image that was presented to me - this is showing driving the wrong way around the rounder-bout.

screenshot_20171017-154758

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fixes backwards instructions in left-side driving scenarios.

Fixes #396 and a regression from https://github.com/mapbox/mapbox-navigation-android/pull/1946

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Maneuvers images (both the maneuver view and the notification maneuver icon) should be displayed accordingly in left-side driving countries.

### Implementation

Fixed `ManeuverView` regression and added new notification maneuver icons and logic for left driving side 👀 `ManeuverUtils#getManeuverResource` 

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

cc @1ec5

### CODE REVIEW

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverUtils.java [hunk 1]
```diff
@@ -7,22 +7,29 @@
...
       StepManeuver maneuver = step.maneuver();
-      if (!TextUtils.isEmpty(maneuver.modifier())) {
+      String maneuverType = maneuver.type();
+      String maneuverModifier = maneuver.modifier();
+      if (!TextUtils.isEmpty(maneuverModifier)) {
         String drivingSide = step.drivingSide();
-        if (!STEP_MANEUVER_MODIFIER_LEFT.equals(drivingSide)) {
-          drivingSide = EMPTY;
+        if (STEP_MANEUVER_MODIFIER_LEFT.equals(drivingSide)) {
+          if (STEP_MANEUVER_MODIFIER_UTURN.equals(maneuverModifier)
```
Comment (andrlee) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverUtils.java]: i wonder if we could reduce number (5) of nested `if` conditions to improve readability of this method.

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java [hunk 2]
```diff
@@ -141,6 +141,21 @@
       R.drawable.ic_maneuver_roundabout_straight);
     maneuverMap.put(STEP_MANEUVER_TYPE_ROUNDABOUT, R.drawable.ic_maneuver_roundabout);
 
+    maneuverMap.put(STEP_MANEUVER_TYPE_ROUNDABOUT + STEP_MANEUVER_MODIFIER_LEFT + STEP_MANEUVER_MODIFIER_LEFT,
```
Comment (andrlee) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java]: what's the benefit of maintaining hashmap of the constants vs. simple `switch-case`? also note is that `ManeuverMap` constructor is not private, which may potentially result in multiple instances of the `ManeuverMap`object.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java [hunk 3]
```diff
@@ -234,9 +234,12 @@ protected void onDraw(Canvas canvas) {
     if (maneuverViewUpdate != null) {
       maneuverViewUpdate.updateManeuverView(canvas, primaryColor, secondaryColor, size, roundaboutAngle);
     }
-    if (drivingSide.equals(STEP_MANEUVER_MODIFIER_RIGHT)) {
-      boolean flip = SHOULD_FLIP_MODIFIERS.contains(maneuverModifier);
-      setScaleX(flip ? -1 : 1);
+    boolean flip = SHOULD_FLIP_MODIFIERS.contains(maneuverModifier);
```
Comment (andrlee) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java]: is this equivalent to:
```suggestion
    boolean flip = SHOULD_FLIP_MODIFIERS.contains(maneuverModifier);
    if (STEP_MANEUVER_MODIFIER_LEFT.equals(drivingSide) && STEP_MANEUVER_MODIFIER_UTURN.contains(maneuverModifier)) {
        setScaleX(flip ? 1 : -1);
    } else {
       setScaleX(flip ? -1 : 1);
    }
```

**Comment by Guardiola31337** [comment]
I'm still testing multiple scenarios in different countries, I'll report back here and let you know when this is ready for review.

**Comment by Guardiola31337** [comment]
Tested some of the incorrect cases reported in #396 and https://github.com/mapbox/mapbox-navigation-android/pull/1946 and so far it’s working :ok_hand: 

_Borsdane Ave Banner_

borsdane_ave_banner

_Borsdane Ave Notification_

borsdane_ave_notification

_East Lancashire Rd Banner_

east_lancashire_rd_banner

_East Lancashire Rd Notification_

east_lancashire_rd_notification

_Flamingo Rd Banner_

flamingo_rd_banner

_Flamingo Rd Notification_

flamingo_rd_notification

_Old Kent Rd Banner_

old_kent_rd_banner

_Old Kent Rd Notification_

old_kent_rd_notification

**Comment by Guardiola31337** [comment]
One thing that I noticed during testing is that the source of the data that we're using for the banner and the notification is different 👀

`BannerInstructions` for `ManeuverView` https://github.com/mapbox/mapbox-navigation-android/blob/71fae584248a7b9c703fe9232bdd70fa6df7dee2/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java#L493-L502

and `LegStep` for `MapboxNavigationNotification` https://github.com/mapbox/mapbox-navigation-android/blob/71fae584248a7b9c703fe9232bdd70fa6df7dee2/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationNotification.java#L274-L281

For consistency, we should revisit / consolidate this using the banner information in a feature PR. Refs. https://github.com/mapbox/mapbox-navigation-android/pull/1946#discussion_r288317754

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java (hunk 2 above)
Comment (Guardiola31337) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java]: > what's the benefit of maintaining hashmap of the constants vs. simple `switch-case`?

As Martin Fowler describes in _Refactoring Improving the Design of Existing Code_:

> The problem with switch statements is essentially that of duplication. Often you
find the same switch statement scattered about a program in different places. If you add a new clause to the switch, you have to find all these switch, statements and change them. The object oriented notion of polymorphism gives you an elegant way to deal with this problem.
>
> Most times you see a switch statement you should consider polymorphism.

So in general, switch statements are considered a bad smell 👀 https://refactoring.guru/smells/switch-statements

Most of the times a  switch statement can be easily replaced with map / dictionary.

And yeah, it's true there’s probably a bit more overhead in the dictionary than in the switch statement because you have to store the dictionary somewhere so it’s obviously using some memory. However IMO, in return you’re getting clean, concise, less error-prone and well-organized code that helps maintainability in the long term.

**Comment by Guardiola31337** [comment]
IMO, objects and methods should live / be where their context is. From my experience utility classes become a drawer easily and we should treat them carefully. So I went ahead and removed `ManeuverUtils` and moved `getManeuverResource` utility method into `MapboxNavigationNotification`. Also I don't believe this class needs to be public as it's used only internally (breaking change / SemVer).

This is now ready for review @andrlee @abhishek1508 @olegzil

**Comment by Christophe668** [comment]
> IMO, objects and methods should live / be where their context is. From my experience utility classes become a drawer easily and we should treat them carefully. So I went ahead and removed `ManeuverUtils` and moved `getManeuverResource` utility method into `MapboxNavigationNotification`. Also I don't believe this class needs to be public as it's used only internally (breaking change / SemVer).
> 
> This is now ready for review @andrlee @abhishek1508 @olegzil

@Guardiola31337, To be honest, I was using this class to retrieve to the icon resource in order to implement our upcoming/follow up leg design.
Is this something you want to restrict/avoid?

**Comment by Guardiola31337** [comment]
Hey @Christophe668 thanks for your feedback.

> To be honest, I was using this class to retrieve to the icon resource in order to implement our upcoming/follow up leg design.
Is this something you want to restrict/avoid?

As commented in https://github.com/mapbox/mapbox-navigation-android/pull/2044#issuecomment-529054075 we should consolidate the data source for the banner and the notification, in favor of using the banner information. Also mentioning that the logic changed is used for generating the `MapboxNavigationNotification` icons (which still has some known issues 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1952).

As you may know, all this data can be retrieved from the `RouteProgress` and used to implement your upcoming / follow up leg design. Would that work for you? Are you using these resources directly in your UI? If so, I wouldn't recommend you doing that because of the reasons above-mentioned and because it could break your UI if we decide to change the resources internally. As mentioned we don't believe this class / method needs to be public as it's used only internally. On a side note, if you still want to use this logic you can grab the code and implement it on your side, that's the beauty of open source 😅

In any case, could you talk more about your specific use case? We'd love to make sure we're not missing anything. Thanks again!
