### PR TITLE
Fix bug with MapRoute onClick

### LINKED ISSUE #701: On map click, route line gets placed on top of markers
when the route is first drawn and you tap the map, the origin and destination markers get placed below the route layer.

ezgif com-video-to-gif 2

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #701 

Also fixed up some of the logic in regard to how we handle clicking on alternatives.  Previously, if both routes were within the `250m` padding, the logic would sometimes still choose the index for the already clicked route even if we clicked on the alternative.

Current `master`: 
ezgif com-video-to-gif 1

This PR:
ezgif com-video-to-gif

cc @cammace

### CODE REVIEW

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java [hunk 1]
```diff
@@ -601,50 +607,66 @@ public void removeRoute() {
 
   @Override
   public void onMapClick(@NonNull LatLng point) {
-    if (directionsRoutes == null || directionsRoutes.isEmpty() || !alternativesVisible) {
+
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java]: NIT blank line

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java [hunk 2]
```diff
@@ -601,50 +607,66 @@ public void removeRoute() {
 
   @Override
   public void onMapClick(@NonNull LatLng point) {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java]: IMO `onMapClick` is getting too long.
What about extracting blocks of code into well-named (based on the comments) `private` methods and simplifying conditional expressions?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java [hunk 3]
```diff
@@ -601,50 +607,66 @@ public void removeRoute() {
...
     }
   }
 
-  @SuppressWarnings("unchecked")
-  private static List<com.mapbox.geojson.Point> calculateLinePoints(
-    FeatureCollection featureCollection) {
-    List<com.mapbox.geojson.Point> linePoints = new ArrayList<>();
-    for (Feature feature : featureCollection.getFeatures()) {
-      List<Position> positions = (List<Position>) feature.getGeometry().getCoordinates();
+  private boolean calculateClickDistancesFromRoutes(HashMap<Double, DirectionsRoute> routeDistancesAwayFromClick,
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java]: Long method.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java [hunk 4]
```diff
@@ -703,7 +725,7 @@ public void onProgressChange(Location location, RouteProgress routeProgress) {
    * the source into pieces so data-driven styling can be used to change the route colors
    * accordingly.
    */
-  private static FeatureCollection addTrafficToSource(DirectionsRoute route, int index) {
+  private FeatureCollection addTrafficToSource(DirectionsRoute route, int index) {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java]: Long method.

**Comment by danesfeder** [comment]
@Guardiola31337 Added some refactoring to address your comments
