### PR TITLE
fix example app issues #2733

### LINKED ISSUE #2733: BasicNavigationActivity doesn't support configuration changes
When testing the `examples` test app noticed that `BasicNavigationActivity` doesn't support configuration changes. Tested in simulation mode putting the app in the background and bringing it back to the foreground from the notification and puck is stuck 👀 Rest of examples work 👌 

basic_navigation_activity_config_changes_not_supported

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix several example app issues in `InstructionViewActivity` / `SummaryBottomSheetActivity` / `BasicNavigationActivity`:
* Fix #2733
* After starting the navigation, pull notification down and click `End Navigation` from notification, you could see the puck keeps moving even the route has been cleared. It's only in replay mode.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Make example app more robust.

### Implementation

* not remove the observer in onStop, only remove it in onDestroy. this can fix the #2733 
* add the location observer when `NavigationMapboxMap` onStart() like we remove it in onStop(). this is also needed to fix the #2733 
* not start/stop location update in Replay mode. Because when trip session stopped, if we startLocationUpdate again, then the ReplayEngine will dispatch the location update again which will cause the puck moving.

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java [hunk 1]
```diff
@@ -553,6 +553,10 @@ public void onStart() {
     handleFpsOnStart();
     locationFpsDelegate.onStart();
 
+    if (navigation != null) {
+      navigation.registerLocationObserver(locationObserver);
+    }
```
Comment (Guardiola31337) [inline libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: Is this an issue in the legacy or a regression from when adding support to `1.0` to the UI SDK?

Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: I think it's not in legacy. The related logic was added here: https://github.com/mapbox/mapbox-navigation-android/pull/2698/files#diff-e5a5b815f804b7277b6f60237aacc739

**Comment by JunDai** [comment]
> One thing that I noticed though is that if you put `InstructionViewActivity` in the background and bring it back to the foreground (clicking on the notification) voice instructions are duplicated probably because `SpeechPlayerProvider` is recreated when in `onCreate` 👀

great find!

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java (hunk 1 above)
Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: Wondering if that was not included as part of `onStart` on purpose as we're adding it when on `addProgressChangeListener` https://github.com/mapbox/mapbox-navigation-android/blob/f91471b070aa66c9bbf1736c208ac61d638d3202/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L345 and then unregistering when on `onStop` assuming that as part of the next `NavigationMapboxMap` lifecycle you need to `addProgressChangeListener`. Also do you know how adding this would affect registering the observer in `addProgressChangeListener`? Are we adding duplicated ones? Could that be a problem 🤔? cc @cafesilencio as you work on https://github.com/mapbox/mapbox-navigation-android/pull/2698

Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: @Guardiola31337 - if I understand correctly that you were saying this `locationObserver` might be registered twice, first is in `addProgressChangeListener` sencond is in `onStart`, during the stand-up meeting? That's a good point. 
I verified that it will not because the `mapboxNavigation` is added only after the navigation starts. So I think we should be good to add the `locationObserver` in `onStart()` here.

@cafesilencio , wdyt?

Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: > I verified that it will not because the `mapboxNavigation` is added only after the navigation starts.

Ohh I see. So you're saying that `addProgressChangeListener` is now only called once and not as part of the lifecycle. I think that's not the case in the legacy and hence my confusion. If so, yeah, we need to add it as part of the lifecycle so it's re-added when in on configuration changes 👍

Comment (cafesilencio) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: From what I can remember this was done intentionally in and seems correct.

Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java:558]: I mean, right now that won't be a problem because of https://github.com/mapbox/mapbox-navigation-android/pull/2834 but if we can avoid one check ¯\\\_(ツ)\_/¯
