### PR TITLE
Fix #2604: wrong notification that shows a free-drive notification

### LINKED ISSUE #2604: Navigation notification shows free-drive mode when there is an ongoing navigation
### Steps to trigger behavior

 1. Run the example app in the repo
 2. Launch `SimpleMapboxNavigationKt` and start a navigation
 3. Check navigation notification

### Expected behavior
Notification shows correct navigation mode
### Actual behavior
Notification shows free-drive mode
Screenshot_20200317-103134

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2604 : wrong notification that shows a free-drive notification

The kotlin let will use the last sentence in the block as its return value. Before this fix, the `let` block will return `routeProgress.bannerInstructions()?.let` as its result. So in any cases that the routeProgress has a valid `route` but doesn't have a bannerInstruction then it will execute the right-hand side expression
of the elvis operator which is `setFreeDriveMode(true)` in this issue.

To fix this issue, just move a non-null expression to the last of the let block.

- [X] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### CODE REVIEW

File: libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt [hunk 1]
```diff
@@ -245,11 +244,12 @@ class MapboxTripNotification constructor(
...
                 if (isManeuverStateChanged(bannerInstructions)) {
                     updateManeuverImage(
-                            routeProgress.currentLegProgress()?.currentStepProgress()?.step()?.drivingSide()
-                                    ?: STEP_MANEUVER_MODIFIER_RIGHT
+                        routeProgress.currentLegProgress()?.currentStepProgress()?.step()?.drivingSide()
+                            ?: STEP_MANEUVER_MODIFIER_RIGHT
                     )
                 }
             }
+            setFreeDriveMode(false)
```
Comment (JunDai) [inline libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt]: The only change is to move this line from top to bottom inside the `let` block so the `let` block will always have a valid return value.

Comment (Guardiola31337) [reply libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt]: Could we add a Unit / UI tests to avoid regressions in the future?

Comment (JunDai) [reply libtrip-notification/src/main/java/com/mapbox/navigation/trip/notification/MapboxTripNotification.kt]: Good point, working on it 👍

File: libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt [hunk 2]
```diff
@@ -105,6 +107,8 @@ class MapboxTripNotificationTest {
         every { mockedContext.packageManager } returns (mockedPackageManager)
         every { mockedContext.packageName } returns ("com.mapbox.navigation.trip.notification")
         every { mockedContext.getString(any()) } returns FORMAT_STRING
+        every { mockedContext.getString(R.string.stop_session) } returns STOP_SESSION
+        every { mockedContext.getString(R.string.end_navigation) } returns END_NAVIGATION
```
Comment (Guardiola31337) [inline libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt]: Previously discussed

> I'm not a big fan of inline setup in tests

File: libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt [hunk 3]
```diff
@@ -181,6 +185,8 @@ class MapboxTripNotificationTest {
         verify(exactly = 1) { bannerText.text() }
         verify(exactly = 1) { collapsedViews.setTextViewText(any(), primaryText()) }
         verify(exactly = 1) { expandedViews.setTextViewText(any(), primaryText()) }
+        verify(exactly = 1) { expandedViews.setTextViewText(any(), END_NAVIGATION) }
+        verify(exactly = 0) { expandedViews.setTextViewText(any(), STOP_SESSION) }
```
Comment (Guardiola31337) [inline libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt]: Previously discussed

> Generally is preferable having only 1 assertion per test 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=57

Same thing applies to behavior verification tests (`verify`)

File: libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt [hunk 4]
```diff
@@ -35,6 +35,8 @@ import org.junit.Assert.assertNull
 import org.junit.Before
 import org.junit.Test
 
+private const val STOP_SESSION = "Stop session"
+private const val END_NAVIGATION = "End Navigation"
```
Comment (Guardiola31337) [inline libtrip-notification/src/test/java/com/mapbox/navigation/trip/notification/MapboxTripNotificationTest.kt]: 👀 [_Working Effectively with Unit Tests_](https://leanpub.com/wewut/read) 
> when writing tests you should prefer DAMP (Descriptive And Maintainable Procedures) 

That includes a bunch of _procedures_ as [Expect Literals](https://leanpub.com/wewut/read#leanpub-auto-expect-literals) 😅
