### PR TITLE
Fix OffRoute detection disabled bug

### LINKED ISSUE #780: Crash when enableOffRouteDetection is set to false
**Bug report:** If you set enableOffRouteDetection to false in MapboxNavigationOptions the crashes if you start navigation. 

Seems like because of this setting no OffRouteDetector is set during the MapboxNavigation init: 
[MapboxNavigation.java](https://github.com/mapbox/mapbox-navigation-android/blob/090cb38532bbe9c5d1ea260b72f92fb6152d4f49/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L158)

Because no engine is set. The following lines throw a NullPointerException: 
[NavigationHelper.java](https://github.com/mapbox/mapbox-navigation-android/blob/c4e928d83e4415dac8397e03c176c2baa6b18c2a/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelper.java#L203)

**Logs:** 
`
E/AndroidRuntime: FATAL EXCEPTION: NavThread
                                                                Process: com.app.debug, PID: 572
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.navigation.v5.offroute.OffRoute.isUserOffRoute(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress, com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions)' on a null object reference
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.isUserOffRoute(NavigationHelper.java:205)
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:99)
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:65)`

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #780

### CODE REVIEW

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 1]
```diff
@@ -70,6 +69,39 @@ public void defaultEngines_didGetInitialized() throws Exception {
     assertNotNull(navigation.getOffRouteEngine());
   }
 
+  @Test
+  public void offRouteEngine_doesNotGetInitializedWithFalseOption() throws Exception {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Normally is good to structure the tests following the triple A 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40 http://wiki.c2.com/?ArrangeActAssert
If the `A`rrange part gets too long we should create factory or builder methods.

This applies to other tests included in `MapboxNavigationTest`.

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java [hunk 2]
```diff
@@ -70,6 +69,39 @@ public void defaultEngines_didGetInitialized() throws Exception {
...
+    MapboxNavigationOptions options = MapboxNavigationOptions.builder()
+      .enableOffRouteDetection(false)
+      .build();
+    navigation = new MapboxNavigation(mock(Context.class), ACCESS_TOKEN, options, mock(NavigationTelemetry.class),
+      mock(LocationEngine.class));
+    assertNull(navigation.getOffRouteEngine());
+    initDefaultNavigation();
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java]: Why is `initDefaultNavigation()` needed?

👀 [FIRST](https://hackernoon.com/test-f-i-r-s-t-65e42f3adc17)

File: libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelperTest.java [hunk 3]
```diff
@@ -89,29 +101,40 @@ public void increaseIndex_stepIndexResetsOnLegIndexIncrease() throws Exception {
...
+    mapboxNavigation.addMilestone(new StepMilestone.Builder()
+      .setTrigger(Trigger.eq(TriggerProperty.STEP_INDEX, 0))
+      .setIdentifier(1001).build());
+    mapboxNavigation.addMilestone(new StepMilestone.Builder()
+      .setTrigger(Trigger.eq(TriggerProperty.STEP_INDEX, 4))
+      .setIdentifier(1002).build());
+
+    List<Milestone> triggeredMilestones
+      = checkMilestones(routeProgress, routeProgress, mapboxNavigation);
+    assertEquals(1, triggeredMilestones.size());
```
Comment (Guardiola31337) [inline libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelperTest.java]: Generally is preferable having only 1 assertion per test 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=57
