### PR TITLE
Fix for soft gradient expression created with extremely small distanc…

### LINKED ISSUE #4857: Soft gradient traffic expression with extremely small distance offset
When using the soft gradient option for creating traffic expressions an Expression.Stop is created to give the appearance of a hard stop at the vanishing point.  Part of the calculation uses the distance offset representing the amount of the route that has been traveled.  If this value is extremely small it will create an expression stop with a negative value and thus an invalid Expression.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Fixes #4857 by checking the distance offset value when creating soft gradient Expression objects. 

### Changelog
```
<changelog>Bug fix for traffic expressions using soft gradients.</changelog>
```

### CODE REVIEW

File: libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt [hunk 1]
```diff
@@ -1954,6 +1954,76 @@ class MapboxRouteLineUtilsTest {
...
+        val segments = MapboxRouteLineUtils.calculateRouteLineSegments(
+            route,
+            listOf(),
+            true,
+            colorResources
+        )
+        val stopGap = 20.0 / route.distance()
+
+        val result = MapboxRouteLineUtils.getTrafficLineExpressionSoftGradient(
+            .00000000001,
```
Comment (LukasPaczos) [inline libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt:2017]: Could you extract this to an internal (or visible for test only) value? Otherwise, if we'd change it in code, we'd never remember to update the test as well.

**Review by LukasPaczos — APPROVED** [review]

File: libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt (hunk 1 above)
Comment (cafesilencio) [reply libnavui-maps/src/test/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtilsTest.kt:2017]: Presumably the test would fail but I can move it out.
