### PR TITLE
make use of fixed duration for non tracking statuses

### LINKED ISSUE #1404: Incorrect ETA since Navigation SDK 20
Incorrect ETA displayed until user is moving.

**Android API:28**
**Mapbox Navigation SDK version:21**

### Steps to trigger behavior
``` 
		val navigationOptions = MapboxNavigationOptions.builder()
				.snapToRoute(false)
				.isFromNavigationUi(true)

		val options = NavigationViewOptions.builder()
				.navigationListener(this)
				.directionsRoute(directionsRoute)
				.directionsProfile(DirectionsCriteria.PROFILE_CYCLING)
				.waynameChipEnabled(false)
				.routeListener(createRouteListener())
				.progressChangeListener { _, progress -> }
				.navigationOptions(navigationOptions.build())
		navigationView.startNavigation(options.build())
```

### Expected behavior
Displayed ETA 30 mins and 5km

### Actual behavior
screenshot_20181009-095154
ETA pannel is displaying 1 min and 50 m instead of 25mins and 5km. 
In `progressChangeListener` `durationRemaining()` and `distanceRemaining()` is returning 0

### PR DESCRIPTION
**Pull request by kevinkreiser**
fixes #1404

This uses the latest native release to fix the issue regarding ETA when the user isn't navigating on the route, either after having just loaded the road (initialized status), just having completed the route (complete status) or having gone off route (offroute status). The initialized status will hold a duration that is that of the entire loaded route leg and will update once you beging tracking on the route. For complete the duration will be 0 and for off route the duration should be the last duration you saw before you went off route.

### CODE REVIEW

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java [hunk 1]
```diff
@@ -27,7 +27,7 @@
 class NavigationRouteProcessor {
 
   private static final int ONE_INDEX = 1;
-  private static final long ONE_SECOND_IN_MILLISECONDS = 1000L;
+  private static final double ONE_SECOND_IN_MILLISECONDS = 1000.0;
```
Comment (kevinkreiser) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java]: using double here so we dont truncate below. not sure if we really need subsecond accuracy, but its there if we need :smile:
