### PR TITLE
Fix some telemetry outstanding issues

### LINKED ISSUE #3135: Telemetry ignores all events if a trip session is started before a route is set
The [`MapboxNavigationTelemetry.kt`](https://github.com/mapbox/mapbox-navigation-android/blob/master/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt) is set up in a way, that forces the route to be present _before_ we start the trip session, otherwise, all of the telemetry events are ignored.
The SDK makes this check:
https://github.com/mapbox/mapbox-navigation-android/blob/b469ee786e60bef101c4250774f85037abc9d7f4/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt#L172-L177
https://github.com/mapbox/mapbox-navigation-android/blob/b469ee786e60bef101c4250774f85037abc9d7f4/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt#L237-L239
but the route is only assigned when the trip session is started:
https://github.com/mapbox/mapbox-navigation-android/blob/b469ee786e60bef101c4250774f85037abc9d7f4/libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt#L493-L502

In short, this means that if the trip session is started before the route is set, we will not send any telemetry events.

@mapbox/navigation-android

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fixes 3 outstanding telemetry issues:

- `NavigationSession.State` transitions
- `sessionStop`
- `MapboxMetricsReporter` cancelation (`disable`)

Fixes #3135 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Fix telemetry issues causing missing events

#### `NavigationSession.State` transitions

Remove unnecessary `TripSessionStateObserver` / `TripSessionState` and rely on `NavigationSessionStateObserver` / `NavigationSession.State`

#### `sessionStop`

Wasn't called in some situations (not sending `NavigationCancelEvent`s)  because `telemetryThreadControl` coroutines were canceled when `MapboxNavigation#onDestroy` was called https://github.com/mapbox/mapbox-navigation-android/blob/6f5359e789d4aa24ac01e937a98663198bedc8d1/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L325-L326 before finishing its work. For operations that shouldn't be cancelled `telemetryScope` was created as recommended in https://medium.com/androiddevelopers/coroutines-patterns-for-work-that-shouldnt-be-cancelled-e26c40f142ad

#### `MapboxMetricsReporter` cancelation (`disable`)

`MapboxMetricsReporter.disable()` should be called at the end as last operation when destroying `MapboxNavigation` i.e. as part of `monitorJobCancelation` and before was called prematurely in `unregisterListeners` when calling `MapboxNavigation#onDestroy` so any events sent afterwards (cancel and flushed events) were ignored by `MapboxTelemetry` downstream

## Testing

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make 1.0-core-update-api` (Core) / `$> make 1.0-ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

cc @zugaldia @mskurydin @Aurora-Boreal

### CODE REVIEW

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 1]
```diff
@@ -107,12 +103,13 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
     internal const val LOCATION_BUFFER_MAX_SIZE = 20
     private const val ONE_SECOND = 1000
     private const val MOCK_PROVIDER =
-        "com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine"
+        "com.mapbox.navigation.core.replay.ReplayLocationEngine"
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:106]: 🥇

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 2]
```diff
@@ -195,65 +189,51 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
...
-    private fun sessionStop() {
-        Log.d(TAG, "TripSessionState.STOPPED")
+    private suspend fun sessionStop() {
+        Log.d(TAG, "sessionStop")
         postUserEventDelegate =
             postUserEventBeforeInit // The navigation session is over, disallow posting user feedback events
         when (dynamicValues.routeArrived.get()) { // Cancellation events will be sent after an arrival event.
             true, false -> {
-                telemetryThreadControl.scope.launch {
+                telemetryScope.launch {
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:223]: is this needed? looks like this function is already in a `suspend`

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 3]
```diff
@@ -107,12 +103,13 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
...
     private const val ONE_SECOND = 1000
     private const val MOCK_PROVIDER =
-        "com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine"
+        "com.mapbox.navigation.core.replay.ReplayLocationEngine"
 
     internal const val TAG = "MAPBOX_TELEMETRY"
     private const val EVENT_VERSION = 7
     private lateinit var context: Context // Must be context.getApplicationContext
     private lateinit var telemetryThreadControl: JobControl
+    private val telemetryScope: CoroutineScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: Hmm interesting https://proandroiddev.com/kotlin-coroutines-patterns-anti-patterns-f9d12984c68e

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 2 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:223]: hmm maybe this is why the supervisor job is needed, to handle the multiple children?
https://medium.com/androiddevelopers/exceptions-in-coroutines-ce8da1ec060c

launch -> launch calls are hard to wrap the head around

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 4]
```diff
@@ -195,65 +189,51 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
...
+            }
         }
     }
 
-    private fun sessionStop() {
-        Log.d(TAG, "TripSessionState.STOPPED")
+    private suspend fun sessionStop() {
+        Log.d(TAG, "sessionStop")
         postUserEventDelegate =
             postUserEventBeforeInit // The navigation session is over, disallow posting user feedback events
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: `postUserEventBeforeInit` looks worthless. Log to the console? Was this being called?

It's a debug log: "Not in a navigation session, cannot send user feedback events". Looks like an error

Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: If that's all it does.. 🎁  if you delete it

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 3 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: `TIL` Looks like this is how we're handling the crash. Because SupervisorJob watches over multiple children launched within scope, and prevents one child from crashing another.

Does this mean we've moved error handling to somewhere else?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 5]
```diff
@@ -195,65 +189,51 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
...
+            false -> {
+                // Do nothing
+                Log.d(TAG, "Only Active Guidance supported")
+            }
         }
     }
 
-    private fun sessionStop() {
-        Log.d(TAG, "TripSessionState.STOPPED")
+    private suspend fun sessionStop() {
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:217]: Would we want to remove the `suspend` and handle the launch inside `sessionStop`?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 3 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: What's the difference between telemetryThreadControl and telemetryScope?

Will we be migrating to telemetryScope?

Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: This was mainly added to support running operations that shouldn’t be cancelled in Coroutines even if its parent is cancelled https://medium.com/androiddevelopers/coroutines-patterns-for-work-that-shouldnt-be-cancelled-e26c40f142ad That was the issue and how we're trying to solve it here as described in https://github.com/mapbox/mapbox-navigation-android/pull/3162#issue-433390967 In other words, we create a separate scope that we know for sure it's not going to be canceled so work is guaranteed to run with `join()`. Does that make sense?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 2 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:223]: It's needed for `join()` 👀 comment above https://github.com/mapbox/mapbox-navigation-android/pull/3162/files#r439164901

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 4 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: It's a way to "reset" 👀 

```kotlin
/**
 * The lambda that is called if the SDK client did not initialize telemetry. If telemetry is not initialized,
 * calls to post a user feedback event will fail silently
 */
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 5 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:217]: If you look at it carefully `sessionStop` is executed when `sessionEndPredicate` lambda is executed, so that'd require extra thought and changes. Didn't want to change the overall logic, only wanted to fix the outstanding issues 😅

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 4 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: yeah i only see a log didn't seem needed 🤷 
```
        { _, _, _, _, _ ->
            Log.d(TAG, "Not in a navigation session, cannot send user feedback events")
        }
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 3 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: > What's the difference between telemetryThreadControl and telemetryScope?

`telemetryThreadControl` 👉 https://github.com/mapbox/mapbox-navigation-android/blob/68758c5dcfebadf0b296304fdbcae4749114fd83/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L203

`telemetryScope` 👉 separate scope that we know for sure it's not going to be canceled

> Will we be migrating to telemetryScope?

Nah, that's on purpose and needed as described above. We need to revisit `ThreadController` implementation though https://github.com/mapbox/mapbox-navigation-android/issues/3156

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 4 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: We can remove the log but it's "failing" silently or better said doing nothing if we tried to send events in an invalid state.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 5 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:217]: ah it's also for the `.join()`

Maybe this would be better? There's another job controller in here 
```
private fun sessionStop() = telemetryScope.launch {
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 3 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:112]: Yep I get it 🤔  

telemetryThreadControl is destroyed by onDestroy
telemetryScope will keep going

this class feels like we'll solve one problem and create a new one. populateNavigationEvent gets executed way late and sends bogus data? 

👍  fix crash

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt (hunk 4 above)
Comment (kmadsen) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:220]: Yeah up to you :). I can't tell if it's failing silently or successfully making noise 🙃

**Comment by LukasPaczos** [comment]
Amazing work @Guardiola31337!
