### PR TITLE
Example screen for reroute on route with silent waypoints 

### LINKED ISSUE #1781: Silent waypoints lost when rerouting
Silent waypoints (#1733) are lost when the user is rerouted. `RouteFetcher.buildRequestFromLocation()` and `RouteUtils.calculateRemainingWaypoints()` come up with a set of waypoints that consists of the user’s current location and any remaining waypoints:

https://github.com/mapbox/mapbox-navigation-android/blob/8d2ceeb842b0a923824cf13713c0521782d585df/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java#L122-L129 https://github.com/mapbox/mapbox-navigation-android/blob/927e923441efa049d49a6057a2e3cacf7fbf036b/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/RouteUtils.java#L73-L77

But that only considers explicit waypoints that separate legs, not via points:

https://github.com/mapbox/mapbox-navigation-android/blob/927e923441efa049d49a6057a2e3cacf7fbf036b/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/routeprogress/RouteProgress.java#L122-L124

We’ll need to figure out which waypoints in the original route options are along the remaining route. One edge case to consider is a route that doubles back on itself; we’ll need to preserve the order in that case.

The iOS equivalent to this issue is mapbox/mapbox-navigation-ios#2003.

/cc @mapbox/navigation-android

### LINKED ISSUE #3854: waypointIndicesList crash in reroute case?
**Android API:**30
**Mapbox Navigation SDK version:**1.2.1

### Steps to trigger behavior

 1. Request route with coordinates list, and pick some coordinates to make waypointIndicesList. I also check waypointIndicesList contains first coordinate (0) at first element of list, and coordinate size at last element of list
 2. Request route works with first time
 3. Make off-route case, app crashes with below log

```
java.lang.IndexOutOfBoundsException: toIndex = 17
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.kt:738)
        at com.mapbox.navigation.core.MapboxNavigation.access$reroute(MapboxNavigation.kt:130)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:732)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:121)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:48)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:512)
```

I also found out this information here:
https://github.com/mapbox/mapbox-navigation-android/pull/3581

It's related to problem I mention above? I use 1.2.1 version now, and it still happens.

Thank you for spending time to check my question.

### PR DESCRIPTION
**Pull request by Lebedinsky**
## Description

In this PR I added example screen with check is SDK crashes when reroute happening on the route with silent waypoints.
Fixes #1781 
Fixes #3854 
[Linked issue](https://github.com/mapbox/mapbox-navigation-android/issues/2644)

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### Goal

Check is SDK crashes when reroute happening on the route with silent waypoints. If it is - fix this crash locally. 

### Implementation

Added WaypointsRerouteActivity for reproduce this crash. But after adding any waypoints in this activity and forcing reroute event - crash didn't happen. At the same time, NN returns incorrect RouteOptions during polling (empty waypoint indices, while coordinates and legs are ok).

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs
[ ] I have added an `Activity` example in the test app showing the new feature implemented (where applicable)

```
<changelog>Added example screen for route with silent waypoints when reroute event happens.</changelog>
```

### CODE REVIEW

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 1]
```diff
@@ -0,0 +1,361 @@
...
+            navigationMapboxMap?.drawRoutes(routes)
+        }
+    }
+    private val routeProgressObserver = object : RouteProgressObserver {
+        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
+        }
+    }
+    private val routesReqCallback = object : RoutesRequestCallback {
+        override fun onRoutesReady(routes: List<DirectionsRoute>) {
+            Timber.d("route request success %s", routes.toString())
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:106]:
```suggestion
            Timber.d("route request success   ${routes.toString()}")
```
kotlin 😎 here and below

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 2]
```diff
@@ -0,0 +1,361 @@
...
+import kotlinx.android.synthetic.main.activity_reroute_layout.startNavigation
+//import kotlinx.android.synthetic.main.activity_waypoints_reroute_layout.*
+import timber.log.Timber
+
+/**
+ * This activity shows how to:
+ * - observe reroute events with the Navigation SDK's [RoutesObserver];
+ * - replace default [RerouteController] and handle re-route events.
+ */
+class WaypointsRerouteActivity : AppCompatActivity(), OnMapReadyCallback, OffRouteObserver,
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:56]: wrong description 🤔

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 3]
```diff
@@ -0,0 +1,355 @@
...
+        }
+    }
+
+    private class CoordinatesHolder {
+        var currentLocation: Location = Location("InternalProvider")
+        var destination: Point = Point.fromLngLat(0.0, 0.0)
+    }
+}
+
+private class StopsControllerr {
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:338]:
```suggestion
private class StopsController {
```

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 4]
```diff
@@ -0,0 +1,355 @@
...
+import kotlinx.android.synthetic.main.activity_reroute_layout.startNavigation
+import timber.log.Timber
+import java.lang.ref.WeakReference
+
+/**
+ * This activity shows how to:
+ * - add waypoints to the route;
+ * - observe reroute events with the Navigation SDK's [RoutesObserver].
+ */
+class WaypointsRerouteActivity :
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:54]:
```suggestion
 * This activity shows how to:
 * - add silent waypoints to the route;
 * - manually invoke reroute;
 * - observe reroute events with the Navigation SDK's [RoutesObserver].
 */
class SilentWaypointsRerouteActivity :
```

**Comment by RingerJK** [comment]
We have to demonstrate how reroute works with **silent** waypoints so we need to add it at flow. 
One of options is invoke `reroute` manually via `RerouteController.reroute()`

**Comment by zugaldia** [comment]
@Lebedinsky what are next steps for this PR?

**Comment by Lebedinsky** [comment]
@zugaldia In general it it ready for review, just need to handle nits Yury mentioned

**Comment by zugaldia** [comment]
@Lebedinsky could you address the PR review comments? I can help you get a new round of review from the team. Thanks!

**Comment by zugaldia** [comment]
@Lebedinsky is the PR ready for another review?

**Comment by Lebedinsky** [comment]
@zugaldia Yes, absolutely
@Guardiola31337 @RingerJK Please, check it one more time

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt (hunk 4 above)
Comment (RingerJK) [reply examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt]: have a look at class' name `SilentWaypointsRerouteActivity `

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 5]
```diff
@@ -0,0 +1,366 @@
...
+import timber.log.Timber
+import java.lang.ref.WeakReference
+
+/**
+ * This activity shows how to:
+ * - add waypoints to the route;
+ * - manually invoke reroute;
+ * - observe reroute events with the Navigation SDK's [RoutesObserver].
+ */
+class WaypointsRerouteActivity :
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:56]: could you also add simulation route option like at other screens. 
For illustration: 
https://github.com/mapbox/mapbox-navigation-android/blob/15734af0cfd9fb8300091c44561475976b393882/examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt#L523-L531

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 6]
```diff
@@ -0,0 +1,366 @@
...
+                val activity = activityRef.get() ?: return@let
+                activity.navigationMapboxMap?.updateLocation(result.lastLocation)
+            }
+        }
+
+        override fun onFailure(exception: Exception) {
+        }
+    }
+
+    private class CoordinatesHolder {
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:343]: could you put classes `CoordinatesHolder` and `WaypointsController` on the same level? I mean it might be into our out of main class

File: examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt [hunk 7]
```diff
@@ -0,0 +1,366 @@
...
+    private val waypointsController = WaypointsController()
+
+    private val locationListenerCallback = MyLocationEngineCallback(this)
+    private val tripSessionStateObserver = object : TripSessionStateObserver {
+        override fun onSessionStateChanged(tripSessionState: TripSessionState) {
+            when (tripSessionState) {
+                TripSessionState.STARTED -> {
+                    startNavigation.visibility = GONE
+                    stopLocationUpdates()
+                    mapboxNavigation?.registerRouteProgressObserver(routeProgressObserver)
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/WaypointsRerouteActivity.kt:80]: already registered at https://github.com/mapbox/mapbox-navigation-android/pull/3497/files#diff-d2425fa28634ae5a9275b0d2d3a9e77bbdf31e0f5e1463c0b2ea51e90c95aa89R155 (#L155)

**Comment by RingerJK** [comment]
When Navigation is started and trying to reroute manually so button `Start navigation` appear that shouldn't be

File: examples/src/main/res/layout/activity_waypoints_reroute_layout.xml [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+        android:id="@+id/navigationLayout"
+        android:layout_width="match_parent"
+        android:layout_height="wrap_content"
+        app:layout_constraintEnd_toEndOf="parent"
+        app:layout_constraintStart_toStartOf="parent"
+        app:layout_constraintBottom_toBottomOf="parent"
+        android:weightSum="0"
+        android:orientation="horizontal">
+        <Button
+            android:id="@+id/startNavigation"
```
Comment (RingerJK) [inline examples/src/main/res/layout/activity_waypoints_reroute_layout.xml:61]:
```suggestion
            android:id="@+id/btnStartNavigation"
```

Comment (Lebedinsky) [reply examples/src/main/res/layout/activity_waypoints_reroute_layout.xml]: 👍

**Review by RingerJK — APPROVED** [review]

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 9]
```diff
@@ -0,0 +1,377 @@
...
+    private val routeObserver = object : RoutesObserver {
+        override fun onRoutesChanged(routes: List<DirectionsRoute>) {
+            directionRoute = routes.firstOrNull()
+            navigationMapboxMap?.drawRoutes(routes)
+        }
+    }
+    private val routeProgressObserver = object : RouteProgressObserver {
+        override fun onRouteProgressChanged(routeProgress: RouteProgress) {
+        }
+    }
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:102]: This is unsued, can we remove?

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 10]
```diff
@@ -0,0 +1,377 @@
...
+        }
+
+        override fun onRoutesRequestCanceled(routeOptions: RouteOptions) {
+            Timber.d("route request canceled")
+        }
+    }
+
+    private val locationObserver = object : LocationObserver {
+        override fun onRawLocationChanged(rawLocation: Location) {
+            routeSettings.currentLocation = rawLocation
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:124]: Let's use enhanced location samples here. That's what we do in the SDK as well.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 11]
```diff
@@ -0,0 +1,377 @@
...
+        mapboxMap.addOnMapLongClickListener { latLng ->
+            waypointsController.add(latLng)
+            routeSettings.destination = latLng.toPoint()
+            mapboxMap.locationComponent.lastKnownLocation?.let { originLocation ->
+                mapboxNavigation?.requestRoutes(
+                    RouteOptions.builder().applyDefaultParams()
+                        .accessToken(Utils.getMapboxAccessToken(applicationContext))
+                        .coordinates(waypointsController.coordinates(originLocation))
+                        .waypointIndices("0;${waypointsController.waypoints.size}")
+                        .alternatives(true)
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:231]: The example does not handle alternative routes, let's just set this to `false`.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 12]
```diff
@@ -0,0 +1,377 @@
...
+        // This is here to demonstrate that this event needs to be handled in order to
+        // redraw the route line after a rotation.
+        directionRoute?.let {
+            outState.putString(Utils.PRIMARY_ROUTE_BUNDLE_KEY, it.toJson())
+        }
+    }
+
+    override fun onRestoreInstanceState(savedInstanceState: Bundle?) {
+        super.onRestoreInstanceState(savedInstanceState)
+        directionRoute = Utils.getRouteFromBundle(savedInstanceState)
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:313]: We also need to set this route to `MapboxNavigation#setRoutes`, otherwise, it won't be recognized anyway.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 13]
```diff
@@ -0,0 +1,377 @@
...
+            mapboxNavigation?.startTripSession()
+            btnReroute.visibility = VISIBLE
+            btnStartNavigation.visibility = GONE
+            mapboxReplayer.play()
+        }
+        btnReroute.setOnClickListener {
+            mapboxNavigation?.getRerouteController()?.reroute(
+                object : RerouteController.RoutesCallback {
+                    override fun onNewRoutes(routes: List<DirectionsRoute>) {
+                    }
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:265]:
```suggestion
                    override fun onNewRoutes(routes: List<DirectionsRoute>) {
                      //  default implementation of the RerouteController automatically sets the route, no action needed
                      // if you're implementing a custom RerouteController, you should invoke `MapboxNavigation#setRoute` here
                      Timber.d("reroute successful")
                    }
```

**Review by LukasPaczos — COMMENTED** [review]
Looking good, a couple of comments below that'd be great to address before merging.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 12 above)
Comment (LukasPaczos) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:313]: And `NavigationMapboxMap#drawRoutes`.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 11 above)
Comment (Guardiola31337) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:231]: We can even remove it as by default is set to `false` 👀 

https://github.com/mapbox/mapbox-navigation-android/blob/356e9d150b2e1ca5ea5b9c7222bc222316d60d23/libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt#L34

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 14]
```diff
@@ -0,0 +1,377 @@
...
+    }
+
+    override fun onLowMemory() {
+        super.onLowMemory()
+        mapView.onLowMemory()
+    }
+
+    @SuppressLint("MissingPermission")
+    override fun onMapReady(mapboxMap: MapboxMap) {
+        mapboxMap.setStyle(Style.MAPBOX_STREETS) { style ->
```
Comment (Guardiola31337) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:205]: > Parameter 'style' is never used, could be renamed to _

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 15]
```diff
@@ -0,0 +1,377 @@
...
+            mapboxMap.moveCamera(CameraUpdateFactory.zoomTo(15.0))
+            navigationMapboxMap = NavigationMapboxMap(mapView, mapboxMap, this, true)
```
Comment (Guardiola31337) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:207]: > 'constructor NavigationMapboxMap(MapView, MapboxMap, LifecycleOwner, Boolean)' is deprecated.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 16]
```diff
@@ -0,0 +1,377 @@
...
+        waypoints.clear()
+    }
+
+    fun coordinates(originLocation: Location): List<Point> {
+        val coordinates = mutableListOf<Point>()
+        coordinates.add(originLocation.toPoint())
+        coordinates.addAll(waypoints)
+        return coordinates
+    }
+}
```
Comment (Guardiola31337) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:377]: Could we extract this out into a utility class so it can be reused across examples? We have the same class in `ReplayWaypointsActivity` 👀 

https://github.com/mapbox/mapbox-navigation-android/blob/356e9d150b2e1ca5ea5b9c7222bc222316d60d23/examples/src/main/java/com/mapbox/navigation/examples/core/ReplayWaypointsActivity.kt#L314-L331

**Review by Guardiola31337 — COMMENTED** [review]
When testing `SilentWaypointsRerouteActivity` run into the following crash after selecting some waypoints, clicking on `START NAVIGATION` and right after clicking on `REROUTE`

```
2020-12-02 10:37:19.966 19893-19893/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 19893
    java.lang.IndexOutOfBoundsException: toIndex = 4
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.examples.core.SilentWaypointsRerouteActivity$initListeners$2.onClick(SilentWaypointsRerouteActivity.kt:262)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 9 above)
Comment (Lebedinsky) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt]: 👍

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 11 above)
Comment (Lebedinsky) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt]: 👍

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 12 above)
Comment (Lebedinsky) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt]: 👍

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 15 above)
Comment (Lebedinsky) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt]: 👍

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt (hunk 16 above)
Comment (Lebedinsky) [reply examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt]: 👍

**Comment by Lebedinsky** [comment]
@Guardiola31337 About crash: looks like it causes because this PR is only about example screen and it not included silent waypoints fix. I'm not able to reproduce it in my fix PR, so I think we will not see this crash after merging silent waypoints reroute fix. But of course, if it happens after merge this fix, I'll check what is going on there)

**Comment by zugaldia** [comment]
> About crash: looks like it causes because this PR is only about example screen and it not included silent waypoints fix. 

@Lebedinsky shouldn't we then rebase this work on a branch that includes the fix? I assume we want to confirm this example works as expected before we merge it to `main`.

File: examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt [hunk 17]
```diff
@@ -0,0 +1,338 @@
...
+    @SuppressLint("MissingPermission")
+    private fun initListeners() {
+        setupReplayControls()
+        btnStartNavigation.setOnClickListener {
+            updateCameraOnNavigationStateChange(true)
+            navigationMapboxMap?.addProgressChangeListener(mapboxNavigation!!)
+            if (mapboxNavigation?.getRoutes()?.isNotEmpty() == true) {
+                navigationMapboxMap?.startCamera(mapboxNavigation?.getRoutes()!![0])
+            }
+            mapboxNavigation?.registerRouteProgressObserver(ReplayProgressObserver(mapboxReplayer))
```
Comment (RingerJK) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SilentWaypointsRerouteActivity.kt:230]: could we make it depends on external setting `simulate route` as at `SimpleMapboxNavigationKt`, to have options ride or simulate route
https://github.com/mapbox/mapbox-navigation-android/blob/7f56d62164c226b1da499f99972a0e0c5c168030/examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt#L217-L221

**Review by RingerJK — APPROVED** [review]
LGTM 👍

**Comment by RingerJK** [comment]
please squash commits before merge

File: examples/src/main/res/values/strings.xml [hunk 18]
```diff
@@ -40,6 +40,9 @@
     <string name="title_replay_waypoints">Replay waypoints</string>
     <string name="description_replay_waypoints">Shows how to use navigate to waypoints.</string>
 
+    <string name="title_silent_waypoints_reroute" translatable="false">Silent waypoints reroute</string>
+    <string name="description_silent_waypoints_reroute" translatable="false">Shows how to use navigate to silent waypoints with reroute.</string>
```
Comment (Guardiola31337) [inline examples/src/main/res/values/strings.xml:44]:
```suggestion
    <string name="description_silent_waypoints_reroute" translatable="false">Shows how to use navigation with silent waypoints.</string>
```

**Review by Guardiola31337 — COMMENTED** [review]
Still running into https://github.com/mapbox/mapbox-navigation-android/pull/3497#pullrequestreview-542957989

```
2020-12-16 17:04:49.751 11414-11414/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 11414
    java.lang.IndexOutOfBoundsException: toIndex = 4
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.examples.core.SilentWaypointsRerouteActivity$initListeners$2.onClick(SilentWaypointsRerouteActivity.kt:269)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Probably is going to be fixed after https://github.com/mapbox/mapbox-navigation-android/pull/3581 lands. Although I thought we were going to do https://github.com/mapbox/mapbox-navigation-android/pull/3497#issuecomment-738826026

Also left a couple of minor comments.

cc @truburt

**Review by Guardiola31337 — APPROVED** [review]
LGTM
