### PR TITLE
Fixed issue where on fresh install, unit type was defaulting to imper…

### LINKED ISSUE #803: Navigation instructions are starting with imperial units when they should default to metric
On fresh install without changing any settings, the default unit type should be metric, though it is defaulting to imperial.

### PR DESCRIPTION
**Pull request by devotaaabel**
…ial instead of metric. Fixes #803

### CODE REVIEW

File: app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java [hunk 1]
```diff
@@ -295,9 +295,9 @@ private Locale getLocale() {
     return new Locale(sharedPreferences.getString("language", ""));
   }
 
-  private int getUnitType() {
+  private @NavigationUnitType.UnitType int getUnitType() {
     SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(this);
-    return Integer.parseInt(sharedPreferences.getString("unit_type", "0"));
+    return Integer.parseInt(sharedPreferences.getString("unit_type", "1"));
```
Comment (danesfeder) [inline app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java]: Should the default here be `NONE_SPECIFIED`?

File: app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java [hunk 2]
```diff
@@ -292,12 +293,13 @@ private void setFieldsFromSharedPreferences(NavigationRoute.Builder builder) {
 
   private Locale getLocale() {
     SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(this);
-    return new Locale(sharedPreferences.getString("language", ""));
+    String localeString = sharedPreferences.getString("language", "device_locale");
+    return localeString.equals("device_locale") ? LocaleUtils.getDeviceLocale(this) : new Locale(localeString);
   }
 
-  private int getUnitType() {
+  private @NavigationUnitType.UnitType int getUnitType() {
```
Comment (Guardiola31337) [inline app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java]: Minor thing annotations normally are on top of the method definition like 👇
```java
@NavigationUnitType.UnitType
private int getUnitType() {
```

File: app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java [hunk 3]
```diff
@@ -292,12 +293,13 @@ private void setFieldsFromSharedPreferences(NavigationRoute.Builder builder) {
 
   private Locale getLocale() {
     SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(this);
-    return new Locale(sharedPreferences.getString("language", ""));
+    String localeString = sharedPreferences.getString("language", "device_locale");
```
Comment (Guardiola31337) [inline app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java]: In order to increase readability, what about replacing magic numbers (literals in general including `String`s) with constants with a particular meaning?
Further information: [Replace Magic Number with Symbolic Constant](https://refactoring.com/catalog/replaceMagicNumberWithSymbolicConstant.html).
