### PR TITLE
Fixes alternatives and continuous alternatives in Drop-In

### LINKED ISSUE #6208: Android Drop-In UI : Show continuous alternatives in Drop-In UI
As a user using Drop-In UI, I should be able to see continuous alternatives and select an alternative route when presented with one.

### PR DESCRIPTION
**Pull request by abhishek1508**
### Description

Fixes #6208

### CODE REVIEW

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt [hunk 1]
```diff
@@ -117,19 +133,59 @@ class RouteLineComponent(
...
+                        else -> {
+                            updatedRoutes.addAll(offBoardAlternatives)
+                        }
                     }
-                    val routeDrawData = routeLineApi.setNavigationRouteLines(routeLines)
-                    routeLineView.renderRouteDrawData(style, routeDrawData)
+                    /**
+                     * TODO: We should pass in currentLegIndex and invoke contractProvider.get().setRoutesWithIndex(mapboxNavigation, updatedRoutes, currentLegIndex)
+                     * val currentLegIndex = routeProgress.value?.currentLegProgress?.legIndex ?: 0
+                     */
```
Comment (Zayankovsky) [inline libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt:187]: `RouteProgress` is passed to `NavigationRouteAlternativesObserver`, you can use it to retrieve the current leg index.

Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteLineComponent.kt]: @Zayankovsky This is fixed. Please take another look.

**Comment by Zayankovsky** [comment]
Looks like this won't work if I use Android Auto, but don't run the app on the phone. Can we do something about it?
For example in 1TAP we create a `MapboxNavigationObserver` in `Application.onCreate`, which registers a `NavigationRouteAlternativesObserver`, which calls `MapboxNavigation.setNavigationRoutes` whenever there are new alternative routes. This way it works in all cases, whether it is only Android Auto that runs or only the app on the phone or both, whether it is Drop-In or not. I guess we could do something similar here, like extracting alternatives observing logic into a separate component, which is installed in `SharedApp.setup`. This will also let us uninstall this component in 1TAP, when user disables alternative routes in the settings screen. 
Unfortunately the current implementation is going to break 1TAP, because users won't be able to see continuous alternatives in Android Auto and won't be able to disable the feature anymore.

**Comment by abhishek1508** [comment]
@Zayankovsky I made the changes and moved `RouteAlternativesObserver` to `StateController`. Please give it another look

**Comment by abhishek1508** [comment]
> I guess we could do something similar here, like extracting alternatives observing logic into a separate component, which is installed in `SharedApp.setup`. This will also let us uninstall this component in 1TAP, when user disables alternative routes in the settings screen.
>>
>Unfortunately the current implementation is going to break 1TAP, because users won't be able to see continuous alternatives in Android Auto and won't be able to disable the feature anymore.

I think the changes I made handles the use case where users will be able to see alternatives in Android Auto, since I moved the logic to `StateController` which registers an observer right in the beginning like you do in 1TAP. However, I think this still does not handle the use case where you want to disable the alternatives feature completely from settings screen.

@kmadsen Any suggestions on what else can be done?

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt [hunk 2]
```diff
@@ -2,14 +2,22 @@ package com.mapbox.navigation.ui.app.internal.controller
...
+import com.mapbox.navigation.ui.app.internal.routefetch.RoutePreviewAction
 import com.mapbox.navigation.ui.app.internal.routefetch.RoutesAction
+import com.mapbox.navigation.utils.internal.ifNonNull
+import kotlinx.coroutines.InternalCoroutinesApi
+import kotlinx.coroutines.flow.collect
+import kotlinx.coroutines.launch
 
-@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
-class RouteStateController(store: Store) : StateController() {
+@OptIn(ExperimentalPreviewMapboxNavigationAPI::class, InternalCoroutinesApi::class)
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt:19]: The annotation is not necessary, because no experimental APIs are used in this class. 
```suggestion
```

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt [hunk 3]
```diff
@@ -19,6 +27,51 @@ class RouteStateController(store: Store) : StateController() {
     override fun onAttached(mapboxNavigation: MapboxNavigation) {
         super.onAttached(mapboxNavigation)
         this.mapboxNavigation = mapboxNavigation
+
+        coroutineScope.launch {
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt:31]: Is it possible to extract this logic to a separate controller or component? I believe it will give us an option to unregister it, when user decides to disable alternative routes in the settings. If you think there should be a better option to handle this on Drop-In side, then we can merge it this way and keep the option always enabled for now.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt (hunk 2 above)
Comment (abhishek1508) [reply libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt]: `ExperimentalPreviewMapboxNavigationAPI::class` is required because the super class uses it.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt (hunk 3 above)
Comment (abhishek1508) [reply libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteStateController.kt]: Moved it to a separate `RouteAlternativeStateController`.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+import com.mapbox.navigation.ui.app.internal.Store
+import com.mapbox.navigation.ui.app.internal.navigation.NavigationState
+import com.mapbox.navigation.ui.app.internal.routefetch.RoutePreviewAction
+import com.mapbox.navigation.ui.app.internal.routefetch.RoutesAction
+import com.mapbox.navigation.utils.internal.ifNonNull
+import kotlinx.coroutines.flow.collect
+import kotlinx.coroutines.launch
+
+@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
+class RouteAlternativeStateController(private val store: Store) : StateController() {
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt:19]: I think you can extend `UIComponent` instead of `StateController`, because as a `Reducer` this class does nothing.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    init {
+        store.register(this)
+    }
+
+    private var mapboxNavigation: MapboxNavigation? = null
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt:24]: This can be removed.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+                            updatedRoutes.addAll(offBoardAlternatives)
+                        }
+                        else -> {
+                            updatedRoutes.add(routePrimary)
+                            updatedRoutes.addAll(alternatives)
+                        }
+                    }
+                    val currentLegIndex = routeProgress.currentLegProgress?.legIndex ?: 0
+                    when (store.state.value.navigation) {
+                        is NavigationState.RoutePreview -> {
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeStateController.kt:57]: This check can be removed, because you don't set the routes during route preview, so you won't receive any alternatives.

**Review by Zayankovsky — APPROVED** [review]

**Comment by abhishek1508** [comment]
@Zayankovsky Can you take a final look and confirm this is gonna work with 1TAP & Android Auto with/without Drop-In UI?

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt [hunk 7]
```diff
@@ -40,24 +44,31 @@ object SharedApp {
...
+        routePreviewStateController,
+        audioGuidanceStateController,
+        tripSessionStarterStateController,
     )
 
     fun setup(
         context: Context,
-        audioGuidance: MapboxAudioGuidance? = null
+        audioGuidance: MapboxAudioGuidance? = null,
+        routeAlternativeContract: Provider<RouteAlternativeContract>? = null
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt:60]: Is `Provider` really necessary? It is like wrapping a lambda with another lambda.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt [hunk 8]
```diff
@@ -13,4 +13,14 @@ sealed class RoutesAction : Action {
...
+
+    /**
+     * The action is used to directly set the [NavigationRoute] supplied to NavigationView.
+     * @param routes list of [NavigationRoute]
+     * @param legIndex index of route leg
+     */
+    data class SetRoutesWithIndex(
+        val routes: List<NavigationRoute>,
+        val legIndex: Int
+    ) : RoutesAction()
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt:25]: Not really important, but you could have added a parameter to existing `SetRoutes` with default value 0. 
Should we also add `legIndex` with a default value to `NavigationViewApi.startActiveGuidance(List<NavigationRoute>)`?

**Review by Zayankovsky — COMMENTED** [review]
The proposed change looks great, I only have a question about implicit filtering of alternatives by their origin.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+        super.onAttached(mapboxNavigation)
+
+        coroutineScope.launch {
+            mapboxNavigation.flowRouteAlternativeObserver().collect { pair ->
+                val routeProgress = pair.first
+                val alternatives = pair.second
+                val currentRoutes = mapboxNavigation.getNavigationRoutes()
+                val primaryRoute = currentRoutes.firstOrNull()
+                ifNonNull(primaryRoute) { routePrimary ->
+                    val isPrimaryRouteOffboard = routePrimary.origin == RouterOrigin.Offboard
```
[the remark this answers is not in the document]
Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:55]: I feel there is no harm in having this logic since offline routing will be a followup after stable Drop-In UI release.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt (hunk 8 above)
Comment (abhishek1508) [reply libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/routefetch/RoutesAction.kt:25]: Will add the index on a need basis.

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt [hunk 10]
```diff
@@ -40,24 +43,30 @@ object SharedApp {
...
         cameraStateController,
+        locationStateController,
         navigationStateController,
+        destinationStateController,
+        routePreviewStateController,
+        audioGuidanceStateController,
+        tripSessionStarterStateController,
     )
 
     fun setup(
```
Comment (Zayankovsky) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/SharedApp.kt:56]: Since this is used by Android Auto, which is a separate library, let's add `@JvmOverloads` to prevent binary incompatibilities. 
```suggestion
    @JvmOverloads
    fun setup(
```

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt [hunk 11]
```diff
@@ -0,0 +1,83 @@
...
+        mapboxNavigation.setNavigationRoutes(
+            routes = updatedRoutes,
+            initialLegIndex = legIndex
+        )
+    }
+}
+
+@ExperimentalPreviewMapboxNavigationAPI
+class RouteAlternativeComponent(
+    private val provider: Provider<RouteAlternativeContract>? = null
```
[the remark this answers is not in the document]
Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:37]: I am gonna let it be as is because we are using the same pattern in other components. We can handle this in all components collectively.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+                        it.origin == RouterOrigin.Offboard
+                    }
+                    val updatedRoutes = mutableListOf<NavigationRoute>()
+                    when {
+                        isPrimaryRouteOffboard -> {
+                            updatedRoutes.add(routePrimary)
+                            updatedRoutes.addAll(offBoardAlternatives)
+                        }
+                        offBoardAlternatives.isNotEmpty() -> {
+                            updatedRoutes.addAll(offBoardAlternatives)
```
[the remark this answers is not in the document]
Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:66]: I did what's recommended [here](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/NavigationRouteAlternativesObserver.kt#L66-L90)
If I change it as per the suggestion made, then there is no difference between the first 2 `when` clauses.

@Zayankovsky

[the remark this answers is not in the document]
Comment (Zayankovsky) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:66]: Well, in this recommendation you can see the following:

> consider notifying the user that a more accurate route is available and whether they'd want to switch

That's exactly what we do in 1TAP. If Drop-In switches to the offboard implicitly, then we won't be able to show the dialog.

File: libnavui-androidauto/build.gradle [hunk 13]
```diff
@@ -45,7 +45,8 @@ dependencies {
     def carSearchVersion = "1.0.0-beta.35"
     api("com.mapbox.navigation:android:${carNavVersion}")
     api("com.mapbox.search:mapbox-search-android:${carSearchVersion}")
-    implementation("com.mapbox.navigation:ui-app:${carNavVersion}")
+    //implementation("com.mapbox.navigation:ui-app:${carNavVersion}")
+    implementation project(":libnavui-app")
```
Comment (abhishek1508) [inline libnavui-androidauto/build.gradle:49]: Revert this and upgrade dependency to `v2.8.0-beta.3` when released.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt (hunk 9 above)
[the remark this answers is not in the document]
Comment (Zayankovsky) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:55]: By the way, how is this going to work if user has a custom router? Probably their routes will have `RouterOrigin.Custom` as origin, right? Might this filtering logic hurt such users?

[the remark this answers is not in the document]
Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:55]: >By the way, how is this going to work if user has a custom router? Probably their routes will have RouterOrigin.Custom as origin, right? Might this filtering logic hurt such users?

Have we addressed this situation in 1TAP already? @Zayankovsky

**Comment by abhishek1508** [comment]
Merging as https://github.com/mapbox/mapbox-navigation-android/pull/6213#discussion_r964024898 is not a blocker for this PR as the problem described in OP is resolved.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt (hunk 9 above)
[the remark this answers is not in the document]
Comment (Zayankovsky) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/ui/RouteAlternativeComponent.kt:55]: We don't have a custom router in 1TAP, so this implementation is OK for us. I'm talking about other potential Drop-In users who have a custom router.

File: libnavui-androidauto/build.gradle (hunk 13 above)
Comment (kmadsen) [reply libnavui-androidauto/build.gradle:49]: Why did this need to be done though? Did this create an incompatibility.

The goal is to make it so different versions of the nav-sdk can be used with different versions of android-auto. When there is a hard dependency, we should identify it and build a stable abstraction

Comment (Zayankovsky) [reply libnavui-androidauto/build.gradle:49]: It is because an incompatible change with `SharedApp` (which is in the internal package) was introduced in this PR. If we want to avoid such issues in the future, we should use only public APIs or maintain compatibility of all internal APIs that Android Auto uses.

Comment (kmadsen) [reply libnavui-androidauto/build.gradle:49]: `SharedApp` needs to have a backwards compatible API, I don't see why it would need to be public.

I've reverted to see what the error is. This is because the sdk does not have a version so maven is unable to upgrade it. I think we could fix it if the sdk was built as a next version snapshot.
```
    java.lang.NoSuchMethodError: No static method setup$default(Lcom/mapbox/navigation/ui/app/internal/SharedApp;Landroid/content/Context;Lcom/mapbox/navigation/ui/voice/internal/MapboxAudioGuidance;ILjava/lang/Object;)V in class Lcom/mapbox/navigation/ui/app/internal/SharedApp; or its super classes (declaration of 'com.mapbox.navigation.ui.app.internal.SharedApp' appears in /data/app/~~A22N4mjD5b-l0vUK9le73A==/com.mapbox.navigation.qa_test_app-7lYqGWAs7nQNNQ-aIPqa3w==/base.apk!classes12.dex)
        at com.mapbox.androidauto.MapboxCarApp.setup(MapboxCarApp.kt:51)
        at com.mapbox.navigation.qa_test_app.QaTestApplication.onCreate(QaTestApplication.kt:11)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Comment (Zayankovsky) [reply libnavui-androidauto/build.gradle:49]: It is hard to maintain compatibility of `SharedApp`, as it is not tracked by Metalava.

Comment (kmadsen) [reply libnavui-androidauto/build.gradle:49]: There is also this issue https://github.com/mapbox/mapbox-navigation-android/issues/6253

So I think we could make `SharedApp` backwards compatible and then we'll be good to go.

Comment (kmadsen) [reply libnavui-androidauto/build.gradle:49]: > It is hard to maintain compatibility of SharedApp, as it is not tracked by Metalava.

I think we can do it until we have a public api. Here's a step https://github.com/mapbox/mapbox-navigation-android/pull/6303

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxFlowableExtensions.kt [hunk 14]
```diff
@@ -106,3 +110,25 @@ fun MapboxNavigation.flowNavigationSessionState(): Flow<NavigationSessionState>
     registerNavigationSessionStateObserver(observer)
     awaitClose { unregisterNavigationSessionStateObserver(observer) }
 }
+
+@OptIn(ExperimentalCoroutinesApi::class)
+fun MapboxNavigation.flowRouteAlternativeObserver():
+    Flow<Pair<RouteProgress, List<NavigationRoute>>> =
```
Comment (dzinad) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxFlowableExtensions.kt:116]: Why don't you include RouterOrigin here?

File: libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeComponentImpl.kt [hunk 15]
```diff
@@ -0,0 +1,18 @@
...
+import com.mapbox.navigation.ui.maps.internal.ui.RouteAlternativeContract
+
+class RouteAlternativeComponentImpl(private val store: Store) : RouteAlternativeContract {
+
+    override fun onAlternativeRoutesUpdated(
+        legIndex: Int,
+        mapboxNavigation: MapboxNavigation,
+        updatedRoutes: List<NavigationRoute>
+    ) {
+        store.dispatch(RoutesAction.SetRoutes(routes = updatedRoutes, legIndex = legIndex))
```
Comment (dzinad) [inline libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeComponentImpl.kt:16]: Is it really `SetRoutes`? Alternative observer is invoked not when the alternatives routes are set but when they are available, if I'm not mistaken.

Comment (dzinad) [reply libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeComponentImpl.kt:16]: Ah, this only _will_ set the routes, right?

Comment (abhishek1508) [reply libnavui-app/src/main/java/com/mapbox/navigation/ui/app/internal/controller/RouteAlternativeComponentImpl.kt:16]: Yes, this will dispatch an action that will set routes to `mapboxNavigation`.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxFlowableExtensions.kt (hunk 14 above)
Comment (abhishek1508) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/internal/extensions/MapboxFlowableExtensions.kt:116]: At the moment I did not see the need of including `RouterOrigin`, but this will definitely be revisited once we also support offline routing in Drop-In UI
