### PR TITLE
Remove NavigationView lifecycle observer and add Fragment Example

### LINKED ISSUE #675: Native (OpenGL related?) crash when leaving navigation screen
I get the following crash when leaving the navigation view (sometimes).  I can't seem to be able to tie it to a specific series of events, it just sometimes happens.  I'm using the navigation view in a fragment.

Device: Google Pixel 2
OS Version: 8.1.0
library versions:
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.9.0') {
        transitive = true
    }
```

```
01-28 14:28:34.676 24698 24698 D QR/BaseFragment: onStop(185125091)
01-28 14:28:34.676 24698 24698 D QR/BaseFragment: onDestroyView(185125091)
01-28 14:28:34.696 24698 24698 W TextToSpeech: stop failed: not bound to TTS engine
01-28 14:28:34.696 24698 24698 W TextToSpeech: shutdown failed: not bound to TTS engine
01-28 14:28:34.698 24698 25254 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25254 (GLThread 55395), pid 24698 (kride.DriverApp)
01-28 14:28:34.726 24698 25156 D QR/DriverUpdatesWS: onClosed(240575796,1000,Closing)
01-28 14:28:34.777 25263 25263 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-28 14:28:34.778   865   865 I /system/bin/tombstoned: received crash request for pid 24698
01-28 14:28:34.780 25263 25263 I crash_dump64: performing dump of process 24698 (target tid = 25254)
01-28 14:28:34.781 25263 25263 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-28 14:28:34.781 25263 25263 F DEBUG   : Build fingerprint: 'google/walleye/walleye:8.1.0/OPM1.171019.013/4474084:user/release-keys'
01-28 14:28:34.781 25263 25263 F DEBUG   : Revision: 'MP1'
01-28 14:28:34.781 25263 25263 F DEBUG   : ABI: 'arm64'
01-28 14:28:34.781 25263 25263 F DEBUG   : pid: 24698, tid: 25254, name: GLThread 55395  >>> com.gosuna.quickride.DriverApp <<<
01-28 14:28:34.781 25263 25263 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
01-28 14:28:34.781 25263 25263 F DEBUG   : Cause: null pointer dereference
01-28 14:28:34.781 25263 25263 F DEBUG   :     x0   0000000000000000  x1   0000007ce46f4518  x2   0000000000000001  x3   0000007d09d3e17a
01-28 14:28:34.781 25263 25263 F DEBUG   :     x4   0000007cedbf3fc0  x5   0000008000000080  x6   00ffffffffffffff  x7   ffffffffffffffff
01-28 14:28:34.781 25263 25263 F DEBUG   :     x8   0000000000000000  x9   0000000000000001  x10  0000007cedbf54f0  x11  0000000000000000
01-28 14:28:34.781 25263 25263 F DEBUG   :     x12  0000000000000000  x13  ffffffffffffff00  x14  0000007cedbf4118  x15  0000000000000000
01-28 14:28:34.781 25263 25263 F DEBUG   :     x16  0000007cf26287a8  x17  0000007d8dd33598  x18  000000000000013c  x19  0000007ce46f4500
01-28 14:28:34.781 25263 25263 F DEBUG   :     x20  0000007cf3f89d00  x21  0000007ce46f4518  x22  0000007cf3f89dd8  x23  0000007cedbf5588
01-28 14:28:34.781 25263 25263 F DEBUG   :     x24  0000000000000004  x25  0000007cedbf5588  x26  0000007ceb6156a0  x27  0000000000000001
01-28 14:28:34.781 25263 25263 F DEBUG   :     x28  0000007cedbf4120  x29  0000007cedbf4090  x30  0000007cf2099e98
01-28 14:28:34.781 25263 25263 F DEBUG   :     sp   0000007cedbf4020  pc   0000007cf225c9dc  pstate 0000000080000000
01-28 14:28:34.791 25263 25263 F DEBUG   :
01-28 14:28:34.791 25263 25263 F DEBUG   : backtrace:
01-28 14:28:34.791 25263 25263 F DEBUG   :     #00 pc 00000000002759dc  /data/app/com.gosuna.quickride.DriverApp-TbALx_qfr2LZZ3tQHO5-aw==/lib/arm64/libmapbox-gl.so
01-28 14:28:34.791 25263 25263 F DEBUG   :     #01 pc 00000000000b2e94  /data/app/com.gosuna.quickride.DriverApp-TbALx_qfr2LZZ3tQHO5-aw==/lib/arm64/libmapbox-gl.so
01-28 14:28:34.791 25263 25263 F DEBUG   :     #02 pc 00000000000b5250  /data/app/com.gosuna.quickride.DriverApp-TbALx_qfr2LZZ3tQHO5-aw==/lib/arm64/libmapbox-gl.so
01-28 14:28:34.791 25263 25263 F DEBUG   :     #03 pc 00000000000b52a0  /data/app/com.gosuna.quickride.DriverApp-TbALx_qfr2LZZ3tQHO5-aw==/lib/arm64/libmapbox-gl.so
01-28 14:28:34.791 25263 25263 F DEBUG   :     #04 pc 0000000000553bf0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #05 pc 000000000054ab88  /system/lib64/libart.so (art_quick_invoke_stub+584)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #06 pc 00000000000dc594  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #07 pc 000000000029b498  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #08 pc 0000000000295a8c  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+700)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #09 pc 0000000000533d64  /system/lib64/libart.so (MterpInvokeDirect+356)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #10 pc 000000000053ca14  /system/lib64/libart.so (ExecuteMterpImpl+14484)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #11 pc 0000000000275bfc  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #12 pc 000000000052544c  /system/lib64/libart.so (artQuickToInterpreterBridge+1052)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #13 pc 0000000000553d0c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
01-28 14:28:34.791 25263 25263 F DEBUG   :     #14 pc 00000000001af22c  /dev/ashmem/dalvik-jit-code-cache (deleted)
01-28 14:28:36.861   865   865 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_07
01-28 14:28:36.863  1114 25264 W ActivityManager:   Force finishing activity com.gosuna.quickride.DriverApp/.activities.main.MainActivity
01-28 14:28:36.871  1114  1143 I ActivityManager: Showing crash dialog for package com.gosuna.quickride.DriverApp u0
01-28 14:28:36.871  1114  1157 I BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
01-28 14:28:36.905  1114  3248 I OpenGLRenderer: Initialized EGL, version 1.4
01-28 14:28:36.905  1114  3248 D OpenGLRenderer: Swap behavior 2
01-28 14:28:36.912  1114  1300 W InputDispatcher: channel '289fbfc com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-28 14:28:36.912  1114  1300 E InputDispatcher: channel '289fbfc com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-28 14:28:36.913  1114 14103 I WindowManager: WIN DEATH: Window{289fbfc u0 com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity}
01-28 14:28:36.913  1114 14103 W InputDispatcher: Attempted to unregister already unregistered input channel '289fbfc com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity (server)'
01-28 14:28:36.913   603   621 E SurfaceFlinger: Failed to find layer (SurfaceView - com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity#0) in layer parent (no-parent).
01-28 14:28:36.913   603   621 E SurfaceFlinger: Failed to find layer (Background for - SurfaceView - com.gosuna.quickride.DriverApp/com.gosuna.quickride.DriverApp.activities.main.MainActivity#0) in layer parent (no-parent).
01-28 14:28:36.913  1114  1124 I ActivityManager: Process com.gosuna.quickride.DriverApp (pid 24698) has died: fore TOP
01-28 14:28:36.914  1114  1124 W ActivityManager: Scheduling restart of crashed service com.gosuna.quickride.DriverApp/com.mapbox.services.android.telemetry.service.TelemetryService in 1000ms
01-28 14:28:36.914  1114  1145 W zygote64: kill(-24698, 9) failed: No such process
01-28 14:28:36.915   710   710 I Zygote  : Process 24698 exited due to signal (11)
01-28 14:28:36.925  1114  1160 W ActivityManager: setHasOverlayUi called on unknown pid: 24698
01-28 14:28:36.926  1114  2176 I ActivityManager: Killing 22924:com.google.android.gms.learning/u0a11 (adj 906): empty #17
01-28 14:28:36.937  1114  1145 W zygote64: kill(-24698, 9) failed: No such process
01-28 14:28:36.937  1114  1145 I zygote64: Successfully killed process cgroup uid 10287 pid 24698 in 22ms
01-28 14:28:36.937  1114  1145 W zygote64: kill(-22924, 9) failed: No such process
01-28 14:28:36.942  1114  1145 W zygote64: kill(-22924, 9) failed: No such process
01-28 14:28:36.942  1114  1145 I zygote64: Successfully killed process cgroup uid 10011 pid 22924 in 5ms
01-28 14:28:36.988 14597 14597 W SessionLifecycleManager: Handover failed. Creating new session controller.
```

### LINKED ISSUE #802: [Question] - Finish properly a navigation in a fragment
**Android API:** 26
**Mapbox Navigation SDK version:** 0.11.1

How to properly finish a fragment?
Using only `navigationView.finishNavigationView()` navigation is not enough. Is this a problem because of the fragment?

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #802, Closes #675 

When implemented with a `Fragment`, `NavigationView` would look at the `Activity` _and_ `Fragment` lifecycles, causing a Maps SDK crash intermittently.  

See https://github.com/mapbox/mapbox-navigation-android/issues/675#issuecomment-374603823 for full context on what was going on here.

### CODE REVIEW

**Comment by gonzalt03** [comment]
Thank you very much for this example. But if you allow me I have a problem, how do you finish the navigation (with onCancelNavigation or onNavigationFinished) without stopping the activity?

File: app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/fragment/NavigationFragment.java [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+  @Override
+  public void onDestroyView() {
+    super.onDestroyView();
+    navigationView.onDestroy();
+  }
+
+  @Override
+  public void onNavigationReady() {
+    Point origin = Point.fromLngLat(-77.04012393951416, 38.9111117447887);
```
Comment (Guardiola31337) [inline app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/fragment/NavigationFragment.java]: Magic numbers

**Comment by danesfeder** [comment]
Hey @gonzalt03, great question - we don't have an explicit method to do this.  All of the navigation logic resides in `NavigationViewModel` and we would need to expose a method in `NavigationView` giving access to `NavigationViewModel#endNavigation`.  I opened a ticket to track this: https://github.com/mapbox/mapbox-navigation-android/issues/813
