### PR TITLE
Adjusted flakey test in an attempt to remove flakiness.

### LINKED ISSUE #5659: multipleSetRouteCall_longAndShortRouteSameConsumerTest is flaky
Refs a failed test in [here](https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6722064102625921845/executions/bs.ad90341852e29dfa/testcases/25/test-cases).

cc @cafesilencio for visibility

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Attempts to fix #5659 with a minor adjustment which is intended to fix flakiness of test.

### CODE REVIEW

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt [hunk 1]
```diff
@@ -122,7 +124,7 @@ class SetRouteOrderTest : BaseTest<BasicNavigationViewActivity>(
                     .trafficExpressionProvider!!
                     .generateExpression()
                     .contents as ArrayList<*>
-                assertEquals(shortRoute, primaryRoute)
+                assertTrue(shortRoute.isSameRoute(primaryRoute))
```
Comment (LukasPaczos) [inline instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt:127]: Since we control the route references that are passed to the API, we are setting the right expectation that they should be equal here. Relaxing the check might just mask the issue. Do we know what mutates the internals of the route? Or maybe it's the fact that the long route is returned here while short should be?

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt [hunk 2]
```diff
@@ -138,7 +140,7 @@ class SetRouteOrderTest : BaseTest<BasicNavigationViewActivity>(
             timerTask {
                 routeLineApi.setRoutes(shortRoutes, consumer)
             },
-            5
+            3
```
Comment (tomaszrybakiewicz) [inline instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt:143]: I think this is the root cause of the test flakiness. We are reusing same `routeLineApi` instance in each test and we are mutating it using timers.

If we create new `routeLineApi` instance for each test, we'll increase test isolation which should fix the flakiness.

```kotlin 
    private lateinit var initIdlingResource: MapStyleInitIdlingResource
    private lateinit var routeLineApi: MapboxRouteLineApi
    private lateinit var myResourceIdler: CountingIdlingResource

    override fun setupMockLocation(): Location {
        val shortRoute = getRoute(activity, R.raw.short_route)
        val origin = shortRoute.routeOptions()!!.coordinatesList().first()
        return mockLocationUpdatesRule.generateLocationUpdate {
            latitude = origin.latitude()
            longitude = origin.longitude()
        }
    }

    @Before
    fun setUp() {
        initIdlingResource = MapStyleInitIdlingResource(activity.binding.mapView)
        routeLineApi = MapboxRouteLineApi(MapboxRouteLineOptions.Builder(activity).build())
        myResourceIdler = CountingIdlingResource("MultipleRouteSetTestResource")
        initIdlingResource.register()
        IdlingRegistry.getInstance().register(myResourceIdler)
        Espresso.onIdle()
    }
```

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt (hunk 1 above)
Comment (cafesilencio) [reply instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/ui/routeline/SetRouteOrderTest.kt:127]: You're right that long route was being returned. I was grasping at straws here.  The flakiness surfaced recently. I think it's related to the caching that was recently introduced with the `NativeRouteParserWrapper` but even trying to adjust for that in the test hasn't been entirely successful.  The test always passes for me locally which makes solving this all the more difficult.

**Comment by Guardiola31337** [comment]
`instrumentation-tests` caught another failing test `verify_history_files_are_recorded_and_readable_with_silent_waypoints` 👀 

```
05-03 07:16:02.676: E/TestRunner(24075): junit.framework.AssertionFailedError: expected:<-77.031991> but was:<-77.031957>
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.fail(Assert.java:50)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.failNotEquals(Assert.java:287)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.assertEquals(Assert.java:102)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.assertEquals(Assert.java:109)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.mapbox.navigation.instrumentation_tests.core.MapboxHistoryTest.verifyHistoryEvents(MapboxHistoryTest.kt:246)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.mapbox.navigation.instrumentation_tests.core.MapboxHistoryTest.verify_history_files_are_recorded_and_readable_with_silent_waypoints(MapboxHistoryTest.kt:220)
05-03 07:16:02.676: E/TestRunner(24075): 	at java.lang.reflect.Method.invoke(Native Method)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:31)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.Suite.runChild(Suite.java:128)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.Suite.runChild(Suite.java:27)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
05-03 07:16:02.676: E/TestRunner(24075): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
05-03 07:16:02.676: E/TestRunner(24075): ----- end exception -----
```

As this is unrelated to OP, we'll cut a new ticket and address separately. @kmadsen could you take a look at it when you have a chance? 🙏

**Review by Guardiola31337 — APPROVED** [review]

**Comment by kmadsen** [comment]
> As this is unrelated to OP, we'll cut a new ticket and address separately. @kmadsen could you take a look at it when you have a chance? 🙏

here's a ticket https://github.com/mapbox/mapbox-navigation-android/issues/5770
