### PR TITLE
Fixes audio focus not released

### LINKED ISSUE #4763: If navigation is cancelled when the voice guidance is still announcing, the volume of the music is not restored
**Android API:** 
**Mapbox Navigation SDK version:** `2.0.0-beta.19`

### Steps to reproduce

1. Test nav app on a mobile phone, when there is music playing at the same time.
2. Start the navigation and wait for the announcement of voice guidance
3. Cancel the navigation during the announcement of voice guidance

### Expected behavior
The volume of the music should be reduced when the navigation voice guidance starts, and then the volume will be restored after the voice guidance ends or cancelled. 

### Actual behavior

However, if the navigation is cancelled when the voice guidance is still announcing, the volume of the music will not be restored. It seems that AudioFocus was not released.

cc @VitaminPSG

### PR DESCRIPTION
**Pull request by n-frolov**
### Description
Closes #4763
Audio focus was not released when stopping MapboxVoiceInstructionsPlayer, because VoiceInstructionsPlayerCallback was not called in that event. Alternative solution was to invoke the callback, but that would change the API.

### Changelog
```
<changelog>Fixed the issue with music volume not restored after stopping voice instructions playback</changelog>
```

### CODE REVIEW

File: libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt [hunk 1]
```diff
@@ -96,6 +96,7 @@ class MapboxVoiceInstructionsPlayer @JvmOverloads constructor(
         clean()
         filePlayer.clear()
         textPlayer.clear()
+        audioFocusDelegate.abandonFocus()
```
Comment (Zayankovsky) [inline libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt:99]: I suggest to move the call to `clean` function. 
Also we should test that `abandonFocus` is called.

Comment (n-frolov) [reply libnavui-voice/src/main/java/com/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer.kt]: Implemented both

**Review by Zayankovsky — APPROVED** [review]
