### PR TITLE
Check for valid name property value in MapWayname

### LINKED ISSUE #1029: MapWayname#updateLayerWithRoadLabelFeatures NullPointerException
Run into the following 💥 while testing

```
06-14 20:34:26.537 31220-31220/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.testapp, PID: 31220
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
        at com.mapbox.geojson.Feature.getStringProperty(Feature.java:324)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateLayerWithRoadLabelFeatures(MapWayname.java:74)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateWaynameWithPoint(MapWayname.java:43)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateMapWaynameWithLocation(NavigationMapboxMap.java:217)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateLocation(NavigationMapboxMap.java:94)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.updateNavigationMap(NavigationView.java:330)
        at com.mapbox.services.android.navigation.ui.v5.NavigationPresenter.onNavigationLocationUpdate(NavigationPresenter.java:67)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:43)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:39)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.onProgressChange(NavigationViewModel.java:251)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:145)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:113)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:92)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5312)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1029

### CODE REVIEW

File: libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/map/MapWaynameTest.java [hunk 1]
```diff
@@ -72,6 +73,20 @@ public void onRoadsReturnedFromQuery_visibilityIsSetToTrueAndLayoutIconAdded() {
     verify(waynameLayer, times(1)).setProperties(any(PropertyValue.class));
   }
 
+  @Test
+  public void onFeatureWithoutNamePropertyReturned_updateIsIgnored() {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/map/MapWaynameTest.java]: ❤️

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapWayname.java [hunk 2]
```diff
@@ -71,12 +71,15 @@ public void updateDefaultMapTopPadding(int topPadding) {
 
   private void updateLayerWithRoadLabelFeatures(List<Feature> roads, SymbolLayer waynameLayer) {
     if (!roads.isEmpty()) {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapWayname.java]: IMO `updateLayerWithRoadLabelFeatures` is getting too long.
What about extracting blocks of code into well-named `private` methods and simplifying conditional expressions somehow?
