### PR TITLE
Fix voiceLanguage NPE and add tests for NavigationSpeechPlayer

### LINKED ISSUE #848: Add test coverage for API Voice functionality
- We should include some unit tests around the new API Voice functionality and the changes made.

👀 https://github.com/mapbox/mapbox-navigation-android/pull/751#pullrequestreview-109262786

cc @devotaaabel @danesfeder

### LINKED ISSUE #1052: Null Reference in NavigationInstructionPlayer
**Android API:** 8.1
**Mapbox Navigation SDK version:** 0.15.0

### Steps to trigger behavior

 1. Use a language that isn't supported by mapbox (I thought I was using English, but that's a separate issue...)
 2. Run library normally, such that it calls onOffRoute(), setMuted(), or onDestroy()

### Expected behavior

Nothing unusual

### Actual behavior

Null Reference Exception - mapboxSpeechPlayer will not have been initialised

### LINKED ISSUE #1060: Unable to destroy activity
**Gradle**
```
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.15.0') {
        transitive = true
        changing = true
    }
```

The following error occurs when touching the `X` to exit the `NavigationView`.

**Error**
```
06-25 17:45:58.910 5464-5464/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.ainscough.routeinfo, PID: 5464
    java.lang.RuntimeException: Unable to destroy activity {uk.co.ainscough.routeinfo/uk.co.ainscough.routeinfo.ActivityNavigation}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4603)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy()' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.voice.NavigationInstructionPlayer.onDestroy(NavigationInstructionPlayer.java:60)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.deactivateInstructionPlayer(NavigationViewModel.java:349)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.onDestroy(NavigationViewModel.java:94)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.shutdown(NavigationView.java:522)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:161)
        at uk.co.ainscough.routeinfo.ActivityNavigation.onDestroy(ActivityNavigation.java:138)
        at android.app.Activity.performDestroy(Activity.java:7462)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4590)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Error Location**
```java
 @Override
    protected void onDestroy() {
        super.onDestroy();
        navigationView.onDestroy();
    }
```

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1052 Closes #848 Closes #1060 

Refactor speech classes to be more testable and add tests to core classes used.  I aligned the naming "instruction" vs. "speech" because we were using both.  Also created an immutable `AutoValue` class `SpeechAnnouncement` to create from the `VoiceInstructionMilestone`

TODO tests for:
- [x] `NavigationSpeechPlayer`
- [x] `NavigationSpeechListener`
- [x] `SpeechPlayerProvider`

### CODE REVIEW

**Comment by danesfeder** [comment]
@Guardiola31337 @devotaaabel this is ready for 👀

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java [hunk 1]
```diff
@@ -17,27 +17,28 @@
...
+
   private boolean isMuted;
   private boolean languageSupported = false;
-  private InstructionListener instructionListener;
 
   /**
    * Creates an instance of {@link AndroidSpeechPlayer}.
    *
-   * @param context used to create an instance of {@link TextToSpeech}
+   * @param context  used to create an instance of {@link TextToSpeech}
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java]: extra space

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java [hunk 2]
```diff
@@ -267,7 +276,11 @@ public void userOffRoute(Location location) {
     @Override
     public void onMilestoneEvent(RouteProgress routeProgress, String instruction, Milestone milestone) {
       if (milestone instanceof VoiceInstructionMilestone) {
-        instructionPlayer.play((VoiceInstructionMilestone) milestone);
+        SpeechAnnouncement speechAnnouncement = SpeechAnnouncement.builder()
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: what if you pass in `VoiceInstructionMilestone` into a constructor in `SpeechAnnouncement` so this logic can be in `SpeechAnnouncement`? Instead of using the builder pattern

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java [hunk 3]
```diff
@@ -52,10 +53,14 @@ public void onInit(int status) {
   /**
    * Plays the given voice instruction using TTS
    *
-   * @param instruction voice instruction to be synthesized and played
+   * @param speechAnnouncement with voice instruction to be synthesized and played
    */
   @Override
-  public void play(String instruction) {
+  public void play(SpeechAnnouncement speechAnnouncement) {
+    if (speechAnnouncement == null) {
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java]: I would add this in the boolean `canPlay`. i.e., `boolean canPlay = languageSupported && !isMuted && !TextUtils.isEmpty(instruction) && speechAnnouncement != null;`

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 4]
```diff
@@ -25,30 +25,34 @@
...
   private File mapboxCache;
   private Cache okhttpCache;
+  private boolean isMuted;
 
   /**
    * Construct an instance of {@link MapboxSpeechPlayer}
    *
-   * @param context to setup the caches
-   * @param language for which language
+   * @param context     to setup the caches
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: we should be consistent with javadoc param spacing

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 5]
```diff
@@ -69,18 +73,24 @@ private void setupCaches(Context context) {
...
+      play(announcement.announcement(), TEXT_TYPE);
+    }
   }
 
   /**
    * Plays the specified text instruction using MapboxSpeech API
    *
    * @param instruction voice instruction to be synthesized and played
-   * @param textType either "ssml" or "text"
+   * @param textType    either "ssml" or "text"
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: again, keep consistent with existing javadoc or change ALL javadoc

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 6]
```diff
@@ -69,18 +73,24 @@ private void setupCaches(Context context) {
...
-   * @param instruction voice instruction to be synthesized and played
+   * @param speechAnnouncement with voice instruction to be synthesized and played
    */
   @Override
-  public void play(String instruction) {
-    play(instruction, SSML_TEXT_TYPE);
+  public void play(SpeechAnnouncement speechAnnouncement) {
+    this.announcement = speechAnnouncement;
+    String ssmlAnnouncement = announcement.ssmlAnnouncememnt();
+    if (ssmlAnnouncement != null) {
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: why would `ssmlAnnouncement` be null?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 7]
```diff
@@ -113,7 +123,7 @@ private void flushCache() {
     try {
       okhttpCache.flush();
     } catch (IOException exception) {
-      Timber.e(exception.getMessage());
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: shouldn't this stay how it is, printing the exception's message instead of toString?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 8]
```diff
@@ -129,12 +139,12 @@ private void stopMediaPlayerPlaying() {
       if (mediaPlayer != null && mediaPlayer.isPlaying()) {
         mediaPlayer.stop();
         mediaPlayer.release();
-        if (instructionListener != null) {
-          instructionListener.onDone();
+        if (speechListener != null) {
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: you shouldn't need this null check anymore since `SpeechListener` is a constructor parameter now.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 9]
```diff
@@ -129,12 +139,12 @@ private void stopMediaPlayerPlaying() {
...
+          speechListener.onDone();
         }
       }
     } catch (IllegalStateException exception) {
-      Timber.e(exception.getMessage());
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: again here?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 10]
```diff
@@ -190,7 +200,7 @@ private void pauseInstruction() {
         mediaPlayer.stop();
       }
     } catch (IllegalStateException exception) {
-      Timber.e(exception.getMessage());
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: and here

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 11]
```diff
@@ -206,8 +216,8 @@ private void setListeners() {
     mediaPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
       @Override
       public void onPrepared(MediaPlayer mp) {
-        if (instructionListener != null) {
-          instructionListener.onStart();
+        if (speechListener != null) {
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: should be able to remove null check

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 12]
```diff
@@ -216,8 +226,8 @@ public void onPrepared(MediaPlayer mp) {
       @Override
       public void onCompletion(MediaPlayer mp) {
         mp.release();
-        if (instructionListener != null) {
-          instructionListener.onDone();
+        if (speechListener != null) {
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: should be able to remove null check

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java [hunk 13]
```diff
@@ -243,12 +253,12 @@ private void startNextInstruction() {
 
   private void clearInstructionUrls() {
     while (!instructionQueue.isEmpty()) {
-      instructionQueue.remove().delete();
+      instructionQueue.poll();
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: Why this change? you still need to `delete` the actual files, and you shouldn't have to worry about exceptions because of the `while(!instructionQueue.isEmpty())`

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+   * <p>
+   * If an announcement is playing at the time this method is called,
+   * the announcement will be stopped immediately.
+   *
+   * @param isMuted true to mute, false to un-mute
+   * @since 0.16.0
+   */
+  public void setMuted(boolean isMuted) {
+    this.isMuted = isMuted;
+    retrieveSpeechPlayer().setMuted(isMuted);
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java]: so this is only going to set the currently retrieved speech player muted, not both if both are active

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java [hunk 15]
```diff
@@ -0,0 +1,87 @@
...
+  /**
+   * Optional method to implement in an {@link com.mapbox.services.android.navigation.v5.offroute.OffRouteListener}.
+   * <p>
+   * During an off-route scenario, you can use this method to cancel existing announcements without
+   * completely muting the player.
+   *
+   * @since 0.16.0
+   */
+  public void onOffRoute() {
+    retrieveSpeechPlayer().onOffRoute();
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java]: same here

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java [hunk 16]
```diff
@@ -0,0 +1,87 @@
...
+  /**
+   * Required method to implement in {@link FragmentActivity#onDestroy()} or
+   * {@link Fragment#onDestroy()}.
+   * <p>
+   * Ensures the player is properly shutdown and finishes any running announcements.
+   *
+   * @since 0.16.0
+   */
+  public void onDestroy() {
+    retrieveSpeechPlayer().onDestroy();
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechPlayer.java]: same here

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java [hunk 17]
```diff
@@ -0,0 +1,31 @@
...
+
+  @Override
+  public void onDone() {
+    audioFocusManager.abandonAudioFocus();
+  }
+
+  @Override
+  public void onError(String errorText, SpeechAnnouncement speechAnnouncement) {
+    Timber.e(errorText);
+    speechPlayerProvider.retrieveAndroidSpeechPlayer().play(speechAnnouncement);
```
Comment (devotaaabel) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java]: Isn't this going to go into an infinite loop if `AndroidSpeechPlayer` returns an error?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 4 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: All of the javadoc spacing was moved to align to the length of the longest `@param`, in this case `accessToken`:
```
   * @param context     to setup the caches
   * @param language    for which language
   * @param accessToken a valid Mapbox access token
```
This is how I had always done it, but if we'd like to agree on a set style here I'm happy to conform / adjust cc @Guardiola31337

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 6 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: Using `VoiceInstructionMilestone` it wouldn't ever be `null`, but if someone uses `NavigationSpeechPlayer` outside of the turn-by-turn UI, they could choose to not include this.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 7 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: `Timber` was showing a lint warning here `Explicitly including the exception message is redundant when supplying an exception to the log`.  

It looks like the library includes the exception message as well as the rest of the exception data when you give it the `Exception` as a param.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 9 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: See https://github.com/mapbox/mapbox-navigation-android/pull/1054#discussion_r198137464

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java (hunk 17 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java]: Currently not firing error listener for `AndroidSpeechPlayer` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/UtteranceListener.java#L31

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 13 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: The `poll()` Javadoc states `Retrieves and removes the head of this queue, or returns {@code null} if this queue is empty.` Does that not actually delete the file?  I changed it back in case I was missing context here.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java (hunk 2 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: Was thinking here in terms of usability outside of the turn-by-turn UI.  `NavigationSpeechPlayer` is a `public` API, so tying it completely to the `VoiceInstructionMilestone` in order to voice something may not make a lot of sense to someone that doesn't want to use the milestones to voice something.  

I did update the builder though to also take a `VoiceInstructionMilestone`, does that work?   Any reasons you don't like the builder pattern here?

**Comment by danesfeder** [comment]
@devotaaabel updated and addressed some of your comments - let me know if anything is unclear

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java [hunk 18]
```diff
@@ -212,9 +215,19 @@ private void initUnitType(NavigationUiOptions options) {
...
   }
 
+  private void initTimeFormat(MapboxNavigationOptions options) {
+    timeFormatType = options.timeFormatType();
+  }
+
   private void initVoiceInstructions(NavigationViewOptions options) {
-    boolean languageSupported = options.directionsRoute().voiceLanguage() != null;
-    instructionPlayer = new NavigationInstructionPlayer(getApplication(), language, languageSupported, accessToken);
+    boolean voiceLanguageSupported = options.directionsRoute().voiceLanguage() != null;
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: Minor thing - Per consistency with other `boolean`s in the code base, what about calling it `isVoiceLanguageSupported` instead?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 4 above)
Comment (Guardiola31337) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: That’s correct. But it’s true that we don’t have a checkstyle rule that enforces it. So if you reformat (as I do constantly :sweat_smile: ⌥⌘L) it gets formatted as @danesfeder mentioned.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechDownloadTask.java [hunk 19]
```diff
@@ -11,14 +11,16 @@
 
 import okhttp3.ResponseBody;
 
-class InstructionDownloadTask extends AsyncTask<ResponseBody, Void, File> {
+class SpeechDownloadTask extends AsyncTask<ResponseBody, Void, File> {
+
   private static final String MP3_POSTFIX = ".mp3";
   private static final int END_OF_FILE_DENOTER = -1;
   private static int instructionNamingInt = 1;
+
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechDownloadTask.java]: NIT - unnecessary empty line

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechAudioFocusManager.java [hunk 20]
```diff
@@ -0,0 +1,45 @@
...
+  private AudioManager audioManager;
+  private AudioFocusRequest audioFocusRequest;
+
+  SpeechAudioFocusManager(Context context) {
+    initAudioManager(context);
+    initAudioFocusRequest();
+  }
+
+  void requestAudioFocus() {
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechAudioFocusManager.java]: Could we remove/abstract these kind of checks somehow? I'm thinking on implementing like a mix of [_Factory_](https://sourcemaking.com/design_patterns/factory_method) and [_Strategy_](https://sourcemaking.com/design_patterns/strategy) patterns.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 6 above)
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: Could we refactor this `if else` somehow? Both branches are calling `play` with different parameters.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechListener.java [hunk 21]
```diff
@@ -1,10 +1,10 @@
...
 
-interface InstructionListener {
+interface SpeechListener {
 
   void onStart();
 
   void onDone();
 
-  void onError(boolean isMapboxPlayer, String errorText);
+  void onError(String errorText, SpeechAnnouncement speechAnnouncement);
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechListener.java]: Question - Could we refactor the code so we don't need to pass the announcement in the error callback?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java (hunk 2 above)
Comment (devotaaabel) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: That makes sense! And yea having a builder method that takes in a `VoiceInstructionMilestone` for convenience is 👍

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java (hunk 17 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/NavigationSpeechListener.java]: It looks like we are logging this currently in `master` https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/AndroidSpeechPlayer.java#L44 

Does sticking with that work okay?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechListener.java (hunk 21 above)
Comment (danesfeder) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/SpeechListener.java]: Let's stick with the current setup here - this is an internal listener.  No excuse, though, I know.  We can look into re-wiring in the future.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 13 above)
Comment (devotaaabel) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: nope, it removes the File object from the queue and we lose track of it in memory but remember the audio file is still in the file system.

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java (hunk 4 above)
Comment (Guardiola31337) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/voice/MapboxSpeechPlayer.java]: > We should add this to checkstyle, or at least going forward start to update non-conforming javadoc as we run into it.

Yeah as I mentioned we don't have one and it'd be awesome to add it. I briefly looked into it and it's a tricky one though (more difficult than I initially thought). I'll keep digging.
