### PR TITLE
Fix MapboxNavigationTelemetry init logic

### LINKED ISSUE #3486: UserFeedback is not sent
> I could not track the feedback event to be really sent. Probably it wasn't.
>
> I found that the code takes a turn at `MapboxNavigationTelemetry::telemetryEventGate` and logs *"Route not selected. Telemetry event not sent. Caused by:Navigation"* instead of reporting the event `metricsReporter.addEvent(event)` because the `dynamicValues.originalRoute` seems to be `null`, although guidance is active (`dynamicValues.isActiveGuidance`).

### Steps to trigger behavior

>```
>// app is started
>MapboxNavigation(...)
>mapboxNavigation.unregisterOffRouteObserver(...) // This is odd, but shouldn't be the source of problems
>mapboxNavigation.registerRouteProgressObserver(...)
>
>// user starts guidance
>mapboxNavigation.registerOffRouteObserver(...)
>mapboxNavigation.setRoutes(listOf(
>	DirectionsRoute))
>
>// user sends feedback
>MapboxNavigation.postUserFeedback("confusing_instruction", "Confusing Instructions", FeedbackEvent.UI, null)
>```

### Expected behavior

> The feedback is sent and winds up in the profiler. Probably `metricsReporter.addEvent(event)` should be called.

### Actual behavior

> I cannot see the request in the profiler and a few seconds after reporting, the event winds up in `MapboxNavigationTelemetry::telemetryEventGate:177` which does NOT execute `metricsReporter.addEvent(event)`, but logs
>```
>MAPBOX_TELEMETRY: Route not selected. Telemetry event not sent. Caused by:Navigation State: true Route exists: false
>MAPBOX_TELEMETRY: Posting a user feedback event false
>```

**Logs**

>I did a `adb logcat | grep -i mapbox` did the following:
>- start the app
>- start guidance
>- clicked feedback button
>- feedback was not posted
>
>and cleaned out a few of our logs, see this:
>```
>MAPBOX_TELEMETRY: MapboxMetricsReporter.init from MapboxNavigation main
>MAPBOX_TELEMETRY: Current session state is: IDLE
>MAPBOX_TELEMETRY: Valid initialization
>MAPBOX_TELEMETRY: Navigation state is FREE_DRIVE
>MAPBOX_TELEMETRY: Current session state is: FREE_DRIVE
>MAPBOX_TELEMETRY: Free drive not supported
>MAPBOX_TELEMETRY: Lifecycle monitor created
>MAPBOX_TELEMETRY: Navigation state is ACTIVE_GUIDANCE
>MAPBOX_TELEMETRY: Current session state is: ACTIVE_GUIDANCE
>MAPBOX_TELEMETRY: First time route set
>MAPBOX_TELEMETRY: Subsequent route set
>MAPBOX_TELEMETRY: trying to post a user feedback event
>MAPBOX_TELEMETRY: Route not selected. Telemetry event not sent. Caused by:Navigation State: true Route exists: false
>MAPBOX_TELEMETRY: Posting a user feedback event false
>```

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fix `MapboxNavigationTelemetry` init logic so that `initialize` can be called multiple times and reset properly when `MapboxNavigation` instance is re-created

Fixes #3486 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

All events are sent when in _Active Guidance_ irrespective of `MapboxNavigation` lifecycle

### Implementation

Fix `MapboxNavigationTelemetry` init logic so that `initialize` can be called multiple times and reset properly when `MapboxNavigation` instance is re-created. Note that `MapboxNavigationTelemetry` is an `object` (singleton) and was guarded by `preInitializePredicate` and `postInitializePredicate` `initializer` predicates. Those were removed and logic adapted so that `MapboxNavigationTelemetry` could be re-initialized and works as designed irrespective of the `MapboxNavigation` lifecycle that internally handles its instantiation

## Testing

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

**Review by LukasPaczos — APPROVED** [review]
lgtm

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 1]
```diff
@@ -163,6 +166,10 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
         sessionEndPredicate()
         sessionEndPredicate = {}
         postUserEventDelegate = postUserEventBeforeInit
+        monitorSession?.apply {
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:169]:
```suggestion
        monitorSession?.cancel()
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt [hunk 2]
```diff
@@ -635,7 +631,7 @@ internal object MapboxNavigationTelemetry : MapboxNavigationTelemetryInterface {
         mapboxNavigation.unregisterOffRouteObserver(callbackDispatcher)
         mapboxNavigation.unregisterNavigationSessionObserver(navigationSessionObserver)
         Log.d(TAG, "resetting Telemetry initialization")
-        initializer = preInitializePredicate
+        weakMapboxNavigation = WeakReference(null)
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:634]:
```suggestion
        weakMapboxNavigation.clear()
```
or 
```suggestion
        weakMapboxNavigation.set(null) 
```

Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/telemetry/MapboxNavigationTelemetry.kt:634]:
```kotlin
weakMapboxNavigation.clear()
```

TIL it seems that internally is setting the reference to `null` 🚀 

```kotlin
weakMapboxNavigation.set(null) 
```

The setter is not available for some reason 🤔

Going to go ahead and use your first suggestion 👍

**Review by RingerJK — APPROVED** [review]
