### PR TITLE
Fix issue #2869 by removing unneccessary LocationObserver.

### LINKED ISSUE #2869: Puck jumpy when transitioning from Active Guidance to Free Drive
When testing the test app `SimpleMapboxNavigationKt` noticed that when transitioning from _Active Guidance_ to _Free Drive_ the puck becomes jumpy 👀 

free_drive_puck_jumpy

This normally happens when having multiple observers enabled sending location updates to the `LocationComponent` so wondering if this is a regression from https://github.com/mapbox/mapbox-navigation-android/pull/2832#discussion_r413495752

We should investigate if this is an issue in the SDK or an issue in the example setup.

cc @JunDai @abhishek1508 @cafesilencio

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2869 

As @Guardiola31337 mentioned, it seems the multiple `locationObserver` are competing to update the puck location. I have tested this PR with the _Mock Locations_ app, seems working.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Please describe the PR goals. Just the stuff needed to implement the fix / feature and a simple rationale. It could contain many check points if needed

### Implementation

In PR #2698 we added the locationObserver in the `NavigationMapboxMap`, so we could remove the locationObserver from `mapboxNavigation`

FYI: https://github.com/mapbox/mapbox-navigation-android/pull/2698/files#diff-e5a5b815f804b7277b6f60237aacc739R343

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt [hunk 1]
```diff
@@ -397,6 +376,8 @@ class SimpleMapboxNavigationKt : AppCompatActivity(), OnMapReadyCallback,
                     updateCameraTrackingMode(NavigationCamera.NAVIGATION_TRACKING_MODE_GPS)
                     updateLocationLayerRenderMode(RenderMode.GPS)
                 } else {
+                    symbolManager?.deleteAll()
+                    removeRoute()
```
Comment (JunDai) [inline examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt:380]: clean up the route and symbol while `End Navigation` from notification.

File: examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt [hunk 2]
```diff
@@ -194,6 +187,10 @@ class CustomUIComponentStyleActivity : AppCompatActivity(), OnMapReadyCallback,
                 addProgressChangeListener(mapboxNavigation)
                 setCamera(DynamicCamera(mapboxMap))
             }
+
+            LocationEngineProvider.getBestLocationEngine(this)
+                .getLastLocation(locationListenerCallback)
```
Comment (LukasPaczos) [inline examples/src/main/java/com/mapbox/navigation/examples/ui/CustomUIComponentStyleActivity.kt:192]: This could also be `mapboxNavigation.locationEngine.getLastLocation`.
