### PR TITLE
Bug fix for route legs that have a distance array value of 0.

### LINKED ISSUE #4877: Multileg routes with 0 distance elements will not get correct traffic congestion.
After some refactoring there is a function in `MapboxRouteLineUtils` that filters out distance values of 0 when extracting data from the `DirectionsRoute`. The side effect of this resulted in an incorrect traffic congestion synchronization between the distance array and the traffic congestion array. Returning an element with a 0 distance causes problems but the implementation extracts the incorrect traffic value for items following the element with a 0 distance.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Fixes #4877 by correctly handling route legs that have a distance value of 0 in the distance array.

### Changelog
```
<changelog>Bug fix for calculating traffic on route line multi-leg routes.</changelog>
```

### CODE REVIEW

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt [hunk 1]
```diff
@@ -520,18 +520,21 @@ object MapboxRouteLineUtils {
             // which results in a distance of 0.0 in the distance array since.  The duplicated
             // coordinate seems to occur at the point the next leg begins. This distance item
             // is filtered out here.
+            val itemOmissionCount = leg.annotation()?.distance()?.count { it == 0.0 } ?: 0
             leg.annotation()?.distance()?.filter { it > 0.0 }?.forEachIndexed { index, distance ->
                 val percentDistanceTraveled = runningDistance / route.distance()
                 val isLegOrigin = index == 0
-                val isInRestrictedRange = restrictedRanges.any { it.contains(index) }
-                val isInAClosure = closureRanges.any { it.contains(index) }
+                val effectiveIndex = index + itemOmissionCount
```
Comment (Zayankovsky) [inline libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt:527]: I guess it will be correct only if all zeros are located at the start of the distance list. 
I suggest doing something like this instead:
```kotlin
leg.annotation()?.distance()?.withIndex()?.filter { it.index > 0.0 }?.forEach { (index, distance) ->
    // use index as is
}
```
or
```kotlin
leg.annotation()?.distance()?.forEachIndexed { index, distance ->
    if (distance <= 0) return@forEachIndexed
    // use index as is
}
```
The second option doesn't create a filtered list, which may be more efficient.

Comment (kmadsen) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt:527]: this is a good point, @cafesilencio can you add a test that covers this case?

Comment (cafesilencio) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt:527]: It's unlikely there would be more than entry with a zero distance but not necessarily impossible. I realized this last night so i'll make an adjustment to handle the anomaly.

**Review by Zayankovsky — APPROVED** [review]

File: libnavui-maps/src/test/resources/artificially_wrong_two_leg_route.json [hunk 2]
```diff
@@ -0,0 +1,1810 @@
+{
```
Comment (kmadsen) [inline libnavui-maps/src/test/resources/artificially_wrong_two_leg_route.json:1]: nit: if you remove the white space from these, it reduces the size by a lot.

Before: 46KB
After: 19KB

KB is small. But percentage wise, size reduction of 242%

**Review by kmadsen — APPROVED** [review]

File: libnavui-maps/src/test/resources/artificially_wrong_two_leg_route.json (hunk 2 above)
Comment (cafesilencio) [reply libnavui-maps/src/test/resources/artificially_wrong_two_leg_route.json:1]: I"ll minify them.

**Comment by cafesilencio** [comment]
This has been cherry picked into the release 2.0 branch here: https://github.com/mapbox/mapbox-navigation-android/pull/4883
