### PR TITLE
handle route changes and navigation state separately

### LINKED ISSUE #6251: Android Drop-In UI: Camera issues
1. ~~Camera pitch does not change to zero before a maneuver, if reroute happened before that~~ (fixed in #6283):

https://user-images.githubusercontent.com/71784588/184895086-10386fc0-f321-432b-8f7b-514a2367ca92.mp4

2. Camera returns to user location when going from route preview to destination preview:

https://user-images.githubusercontent.com/71784588/185092723-6910d4d9-02f7-4af8-a13b-a5c8411ae01a.mp4

3. Camera unnecessarily moves from location puck to destination and back after you cancel the trip:

https://user-images.githubusercontent.com/71784588/185176129-5a67094d-2815-46db-bf04-accacbde8565.mp4

4.  ~~Following camera is not working properly after a reroute~~ (fixed in #6283):

https://user-images.githubusercontent.com/71784588/187438409-9b586ea6-1599-4a11-9484-9d39a69008eb.mp4

### PR DESCRIPTION
**Pull request by Zayankovsky**
### Description

Fixes #6251. 
Previously we combined both flows which caused camera to change state not only when navigation state changes, but also when routes change (reroute or switching to an alternative). By observing the flows separately the issue is fixed. The only exception is free drive state, where we have to wait for routes to become empty and avoid unnecessary camera transitions in an intermediate state. 

### Screenshots or Gifs

https://user-images.githubusercontent.com/2395284/189198184-7e4ef7b9-44a3-4ef2-9834-1551df38ad1c.mp4

### CODE REVIEW

File: libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt [hunk 1]
```diff
@@ -188,47 +189,51 @@ internal class CameraComponent constructor(
...
+                viewportDataSource.evaluate()
+            } else {
+                viewportDataSource.onRouteChanged(routes.first())
+                viewportDataSource.evaluate()
+            }
+        }
+        val navigationStateFlow = store.select { it.navigation }
+        combine(navigationStateFlow, routesFlow) { navigationState, routes ->
+            navigationState == NavigationState.FreeDrive && routes.isEmpty()
+        }.filter { it }.observe { store.dispatch(SetCameraMode(TargetCameraMode.Overview)) }
```
Comment (kmadsen) [inline libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt:220]: This store.dispatch would be better moved to the other flowable.

There are 2 streams dispatching camera modes, it's easier to understand when there is 1 stream that will dispatch the events

File: libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt [hunk 2]
```diff
@@ -188,47 +189,51 @@ internal class CameraComponent constructor(
...
+        navigationStateFlow.observe { navigationState ->
+            when (navigationState) {
+                NavigationState.FreeDrive -> {
+                    // handled above
```
Comment (kmadsen) [inline libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt:224]: why not handle it here? with a `combine(navigationStateFlow, routesFlow)`

```
NavigationState.FreeDrive && && routes.isEmpty() -> {
    store.dispatch(SetCameraMode(TargetCameraMode.Overview)
}
```

Comment (Zayankovsky) [reply libnavui-dropin/src/main/java/com/mapbox/navigation/dropin/component/camera/CameraComponent.kt]: In the description I wrote why we can't observe the combined flow, that's basically the main change in this PR. But I updated a little, now we dispatch camera events from a single collector.
