### PR TITLE
do not pass invalid routes to observers

### LINKED ISSUE #5945: Handle errors produced by Native Navigator in setRoutes method
Now when `MapboxNavigation#setRoutes` method is called the routes are first passed to Native Navigator and then to all the `RouteObserver`s.
https://github.com/mapbox/mapbox-navigation-android/issues/5686#issuecomment-1161695132
However, Native Navigator can fail routes handing with an error and that error will be ignored and callbacks will be called with invalid routes. The only way to know that something went wrong is now to read the logs.
At least we should stop dispatching invalid routes to callbacks. We should also look if there's something else ww shouldn't do with invalid routes.

### PR DESCRIPTION
**Pull request by dzinad**
Fixes #5945.

### CODE REVIEW

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 1]
```diff
@@ -804,8 +805,12 @@ class MapboxNavigation @VisibleForTesting internal constructor(
         threadController.getMainScopeAndRootJob().scope.launch(Dispatchers.Main.immediate) {
             routeUpdateMutex.withLock {
                 navigationSession.setRoutes(routes)
-                setRoutesToTripSession(routes, legIndex, reason)
-                directionsSession.setRoutes(routes, legIndex, reason)
+                val processedRoutes = setRoutesToTripSession(routes, legIndex, reason)
+                if (processedRoutes.error == null) {
```
Comment (dzinad) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:809]: It seems like this is the right place to distinguish success from error. It looks like the routes should not be set to directionsSession at all or the state becomes inconsistent. I may be wrong tho. Any thoughts?

**Comment by Zayankovsky** [comment]
> I'm not sure if this one should be merged to main considering that beta3 is already released. Maybe after the release? Or do you have a separate branch for new features while the prev one is in beta?

A separate branch for the current release train is created when it goes into RC stage. After that `main` branch is used for the next release train. For example after 2.6.0-rc.1 is released, branch `release-2.6` is created, which is going to contain all changes necessary for future 2.6.0 releases (rc.2 and stable). `main` will contain changes necessary for 2.7.0 releases (alphas, betas and rc.1). So if you merge this PR this week there will be at least two weeks of testing before it becomes a part of a stable release.

**Comment by dzinad** [comment]
> A separate branch for the current release train is created when it goes into RC stage. After that main branch is used for the next release train. For example after 2.6.0-rc.1 is released, branch release-2.6 is created, which is going to contain all changes necessary for future 2.6.0 releases (rc.2 and stable). main will contain changes necessary for 2.7.0 releases (alphas, betas and rc.1). So if you merge this PR this week there will be at least two weeks of testing before it becomes a part of a stable release.

RC goes after betas, right? I'm not sure yet how dangerous a change can be merged at what stage. This one seems kinda bug-prone.

**Comment by Zayankovsky** [comment]
> RC goes after betas, right? 

Yes. You can also read about release trains here: https://docs.google.com/document/d/1cxPp_ZlmNSgNECyGO6i-Bb87oTEAVRqcYi9o_5o1lBE/edit?usp=sharing.

**Comment by dzinad** [comment]
> Yes. You can also read about release trains here: https://docs.google.com/document/d/1cxPp_ZlmNSgNECyGO6i-Bb87oTEAVRqcYi9o_5o1lBE/edit?usp=sharing.

Cool, thanks. I was trying to open the link to Testpad to see the testcases but I don't have an account there. Could you send me an invitation or smth?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 1 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:809]: how can the application react on an invalid routes error? 🤔 it seems we need mechanism for that aka `callback`

Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:809]: Another option is to invoke `RoutesObserver` with empty list of routes and a new reason called `ROUTES_UPDATE_REASON_IGNORE_INVALID`, for example. Although with callback it's more obvious which routes were ignored.

Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:809]: yeah, let's add it

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt [hunk 2]
```diff
@@ -3,5 +3,6 @@ package com.mapbox.navigation.core.trip.session
 import com.mapbox.navigator.RouteAlternative
 
 internal data class NativeSetRouteResult(
-    val nativeAlternatives: List<RouteAlternative>? = null
+    val nativeAlternatives: List<RouteAlternative>? = null,
+    val error: String? = null,
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:7]: Can it have `nativeAlternatives` and `error` simultaneously?

Comment (VysotskiVadim) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:7]: From the usage it seems that result is success **or** error 🤔

**Comment by VysotskiVadim** [comment]
Do you handle a following case:
1. Set valid route
2. Set invalid route
Expected result: navigator has no active routes

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt (hunk 2 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:7]: internal sealed class candidate

**Comment by dzinad** [comment]
> Do you handle a following case:
> 
> 1. Set valid route
> 2. Set invalid route
>    Expected result: navigator has no active routes

What do you mean by navigator? Native navigator? That's what actually tells us if the routes are valid or not. So all routes are passed to it.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 1 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt]: Done, could you review please?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt [hunk 3]
```diff
@@ -0,0 +1,27 @@
+package com.mapbox.navigation.core
+
+import com.mapbox.navigation.base.route.NavigationRoute
+
+/**
+ * Interface definition for a callback that gets notified whenever routes
+ * passed to [MapboxNavigation.setNavigationRoutes] are set or ignored for some reason.
+ */
+interface SetRoutesCallback {
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:9]:
```suggestion
interface RoutesCallback {
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+    /**
+     * Invoked whenever the routes passed to [MapboxNavigation.setNavigationRoutes]
+     * are successfully set.
+     *
+     * @param routes List of routes that were successfully set.
+     */
+    fun onRoutesSetResult(routes: List<NavigationRoute>)
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:17]: Let's add the wrapper, it will potentially help to extend result with new data. 
```suggestion
    fun onSuccess(result: RoutesCallbackSuccess)
```
where 
```kotlin
class RoutesCallbackSuccess internal constructor(
val routes: List<NavigationRoute>
) {
 // equal, hasCode, toString
}
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+    /**
+     * Invoked whenever the routes passed to [MapboxNavigation.setNavigationRoutes]
+     * are ignored for some reason.
+     *
+     * @param routes List of routes that were ignored.
+     * @param error Reason why routes were ignored.
+     */
+    fun onRoutesSetError(routes: List<NavigationRoute>, error: String?)
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:26]: the same as above
```suggestion
    fun onError(error: RoutesCallbackError)
```

```kotlin
class RoutesCallbackError internal constructor(
val routes: List<NavigationRoute>,
val error: String?,
) {
 // equal, hasCode, toString
}
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt [hunk 6]
```diff
@@ -2,6 +2,12 @@ package com.mapbox.navigation.core.trip.session
...
-internal data class NativeSetRouteResult(
-    val nativeAlternatives: List<RouteAlternative>? = null
-)
+internal sealed class NativeSetRouteResult
+
+internal class NativeSetRouteValue(
+    val nativeAlternatives: List<RouteAlternative>
+) : NativeSetRouteResult()
+
+internal class NativeSetRouteError(
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:11]: add docs please

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt [hunk 7]
```diff
@@ -0,0 +1,27 @@
+package com.mapbox.navigation.core
+
+import com.mapbox.navigation.base.route.NavigationRoute
+
+/**
+ * Interface definition for a callback that gets notified whenever routes
+ * passed to [MapboxNavigation.setNavigationRoutes] are set or ignored for some reason.
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:7]:
```suggestion
 * passed to [MapboxNavigation.setNavigationRoutes] are set or produce an error and ignored.
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt [hunk 8]
```diff
@@ -96,11 +96,12 @@ internal class MapboxTripSession(
...
             }
             RoutesExtra.ROUTES_UPDATE_REASON_ALTERNATIVE -> {
-                NativeSetRouteResult(
+                NativeSetRouteValue(
                     nativeAlternatives = navigator.setAlternativeRoutes(routes.drop(1))
                 )
             }
             RoutesExtra.ROUTES_UPDATE_REASON_REFRESH -> {
+                var errorMessage: String? = null
                 val alternatives = if (routes.isNotEmpty()) {
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt:105]:
```suggestion
                return if (routes.isNotEmpty()) {
                  ...
                  alternatives
                } else {  
                  "Cannot refresh route. Route can't be null".also {
                    logW(this, LOG_CATEGORY)
                  }
                }
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt (hunk 4 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:17]: Makes sense, I'll change it when we agree about the naming.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt (hunk 8 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt:105]: Mm? This code does not return anything.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt (hunk 3 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt:9]: Discussed internally. Agreed on `RoutesSetCallback`.

**Comment by dzinad** [comment]
Do you have any tests that check equals/hashCode/toString methods? I trust the auto-generation but there's a possibility we'll forget to update them when we add new properties to the class.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt (hunk 3 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/SetRoutesCallback.kt]: Agreed with `RoutesSetCallback`

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt (hunk 6 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:23]: sometimes, they are not spread for customers, it's for us, internal teams

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt (hunk 8 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt:105]: fixed comment, thanks for catch 👍

**Comment by RingerJK** [comment]
> Do you have any tests that check equals/hashCode/toString methods? I trust the auto-generation but there's a possibility we'll forget to update them when we add new properties to the class.

We still don't have anything for internal classes, have for builders only (see `com.mapbox.navigation.testing.BuilderTest`, it seems that can be extended for plain classes). So for now we just verify it manually

File: CHANGELOG.md [hunk 9]
```diff
@@ -27,6 +28,7 @@ This release depends on, and has been tested with, the following Mapbox dependen
 - Mapbox Java `v6.5.0` ([release notes](https://github.com/mapbox/mapbox-java/releases/tag/v6.5.0))
 - Mapbox Android Core `v5.0.1`
 - Mapbox Android Telemetry `v8.1.2`
+- Fixed the issue with the close icon in the trip notification occasionally using wrong color when including ui-dropin dependency. [#5956](https://github.com/mapbox/mapbox-navigation-android/pull/5956)
```
Comment (RingerJK) [inline CHANGELOG.md:31]: looks like it's not your string 😄

File: CHANGELOG.md [hunk 10]
```diff
@@ -6,6 +6,7 @@ Mapbox welcomes participation and contributions from everyone.
 #### Features
 
 #### Bug fixes and improvements
+- Introduced `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`, which is called after the routes are set or they have been declared invalid. If invalid, they will not be passed to `RoutesObserver#onRoutesChanged` [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```
Comment (VysotskiVadim) [inline CHANGELOG.md:9]: > If invalid, they will not be passed to `RoutesObserver#onRoutesChanged`

I think we should pass empty routes. Consider following scenario.
```kotin
val validRoute = createValidRoute()
val invalidRoute = createInvalidRoute()

val latestNavigationRoutes: List<NavigationRoute> = emptyList()
mapboxNavigation.registerRouteProgressObserver { result ->  latestNavigationRoutes = result.navigationRoutes }

mapboxNavigation.setNavigationRoutes(validRoutes)
// wait for processing
mapboxNavigation.setNavigationRoutes(invalidRoutes)
// wait for processing

assertEquals(emptyList(), latestNavigationRoutes)
assertEquals(emptyList(), mapboxNavigation.getNavigationRoutes())
```

Comment (VysotskiVadim) [reply CHANGELOG.md:9]: BTW, this suggestion is based on assumption that native navigator switches to a free drive after setting routes with error.

Comment (VysotskiVadim) [reply CHANGELOG.md:9]: NN tracks old route in case of error. The suggestion isn't relevant.

Comment (dzinad) [reply CHANGELOG.md:9]: Then it makes sense to not pass anything.

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 11]
```diff
@@ -599,6 +615,146 @@ class MapboxNavigationTest {
...
+        createMapboxNavigation()
+        mapboxNavigation.setRerouteController(navigationRerouteController)
+        val observers = mutableListOf<OffRouteObserver>()
+        verify { tripSession.registerOffRouteObserver(capture(observers)) }
+
+        observers.forEach {
+            it.onOffRouteStateChanged(true)
+        }
+        coVerify(exactly = 1) {
+            directionsSession.setRoutes(newRoutes, 0, RoutesExtra.ROUTES_UPDATE_REASON_REROUTE)
```
Comment (VysotskiVadim) [inline libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt:640]: I'm wondering, do we need to check other side effects of set routes like `routeAlternativesController.processAlternativesMetadata`? 
@dzinad , @RingerJK , what do you think?

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 12]
```diff
@@ -599,6 +615,146 @@ class MapboxNavigationTest {
...
+            }
+        }
+        coEvery {
+            tripSession.setRoutes(any(), any(), any())
+        } returns NativeSetRouteValue(emptyList())
+
+        createMapboxNavigation()
+        mapboxNavigation.setRerouteController(navigationRerouteController)
+        coVerify(exactly = 1) {
+            directionsSession.setRoutes(newRoutes, 0, RoutesExtra.ROUTES_UPDATE_REASON_REROUTE)
```
Comment (VysotskiVadim) [inline libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt:687]: I'm wondering, do we need to check other side effects of set routes like `routeAlternativesController.processAlternativesMetadata`? 
@dzinad , @RingerJK , what do you think?

Comment (dzinad) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt:687]: I'd say yes. However, here my purpose was to cover all the entry points for `internalSetNavigationRoutes` so that I can check the behaviour depending on whether it's success of failure. I think that goal was achieved. I don't see why not add this tests, but it's not really relevant to the task. I prefer doing such things separately so that the original issue does not get stuck because of these small improvements. I can cut a ticket if we agree to add the tests.

File: CHANGELOG.md (hunk 10 above)
Comment (VysotskiVadim) [inline CHANGELOG.md:9]: maybe?
```suggestion
- Introduced a `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`. The callback is called when navigation finished or failed processing given routes. [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945)
-  `RoutesObserver#onRoutesChanged` won't be triggered if navigation fails processing new routes. [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945)
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 13]
```diff
@@ -767,10 +770,15 @@ class MapboxNavigation @VisibleForTesting internal constructor(
      *
      * @param routes a list of [NavigationRoute]s
      * @param initialLegIndex starting leg to follow. By default the first leg is used.
+     * @param callback callback to be called when routes are set or ignored. See [RoutesSetCallback].
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:773]: Maybe?
```suggestion
     * @param callback is called when routes are set or ignored due to an error. See [RoutesSetCallback].
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 14]
```diff
@@ -767,10 +770,15 @@ class MapboxNavigation @VisibleForTesting internal constructor(
...
      * @see [requestRoutes]
      */
     @JvmOverloads
-    fun setNavigationRoutes(routes: List<NavigationRoute>, initialLegIndex: Int = 0) {
+    fun setNavigationRoutes(
```
[the remark this answers is not in the document]
Comment (VysotskiVadim) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: but from the other side, what can we do if a user cancels set routes? Leave navigation in an intermediate state? It's probably okay to let users either destroy navigator or set a new route to cancel and override previous.

[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: Cancellation of what?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt [hunk 15]
```diff
@@ -96,24 +96,29 @@ internal class MapboxTripSession(
...
-                val alternatives = if (routes.isNotEmpty()) {
+                if (routes.isNotEmpty()) {
                     val primaryRoute = routes.first()
                     val alternatives = navigator.refreshRoute(primaryRoute)
                     roadObjects = getRouteInitInfo(primaryRoute.nativeRoute().routeInfo)
                         ?.roadObjects
                         ?: emptyList()
                     this@MapboxTripSession.primaryRoute = routes.first()
-                    alternatives
+                    if (alternatives != null) {
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt:111]: it's not obvious that null means error. Maybe it would make sense to return an `Expected` from `com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl#refreshRoute`?

File: CHANGELOG.md (hunk 10 above)
Comment (VysotskiVadim) [reply CHANGELOG.md:9]: > > The callback is called when navigation finished
> 
> Why? It's called when routes are set, hence the name.

I just find "they have been declared invalid" a bit vague. I think "failed processing given routes" should be easier for users to understand. "set" just doesn't sound good with "failed processing given routes", but "finished" does.

It's a very subjective topic, so it would be nice to hear other opinions. WDYT?

Comment (dzinad) [reply CHANGELOG.md]: OK, first: "when navigation finished" seems odd. It's actually triggered when `setNavigationRoutes` method finished. I can also say "when routes processing finished" or something like that. I don't see how it's clearer than "routes are set", especially when we're talking about the method called `setNavigationRoutes` but I might lack depth in terminology knowledge.
 About "failed processing given routes": probably I agree, because for now the reason is their invalidity, maybe in the future there will be other reasons, your option covers it.
 Tried to create a grammatically valid sentence having taken these points into consideration. Please take a look.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 14 above)
[the remark this answers is not in the document]
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: according to our API should be good to set an empty list, without additional calls 🤔

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt [hunk 16]
```diff
@@ -0,0 +1,88 @@
...
+
+        if (routes != other.routes) return false
+        if (error != other.error) return false
+
+        return true
+    }
+
+    override fun hashCode(): Int {
+        var result = routes.hashCode()
+        result = 31 * result + (error?.hashCode() ?: 0)
```
Comment (RingerJK) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:81]:
```suggestion
        result = 31 * result + error.hashCode()
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 14 above)
[the remark this answers is not in the document]
Comment (VysotskiVadim) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: @RingerJK , some of our users use Kotlin coroutines. I'm trying to image how suspend wrapper would look like:
```kotlin
suspend fun MapboxNavigation.setRoutes(routes: List<NavigationRoute>): SetRoutesResult = suspendCancellableCoroutine { continuation ->
    setRoutes(routes) {
        continutation.resume(it)
    }
    continuation.invokeOnCancellation {
        this.setRoutes(emptyList()) // ????????
    }
}
```

No, it's probably should be not cancellable:
```kotlin
suspend fun MapboxNavigation.setRoutes(routes: List<NavigationRoute>): SetRoutesResult = suspendCoroutine { continuation ->
    setRoutes(routes) {
        continutation.resume(it)
    }
}
```

Or cancellable, but ignore cancellation
```
suspendCancellableCoroutine { continuation ->
    setRoutes(routes) {
        continutation.resume(it)
    }
    continuation.invokeOnCancellation {
      
    }
}
```
Doesn't seem good as well 😞

[the remark this answers is not in the document]
Comment (VysotskiVadim) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: maybe we need to also introduce `MapboxNavigation.cancelSetRoutes` to simplify users's life. If you don't mind I will cut a ticket for this, do you?

File: CHANGELOG.md [hunk 17]
```diff
@@ -7,6 +7,8 @@ Mapbox welcomes participation and contributions from everyone.
 
 #### Bug fixes and improvements
 - Fixed reroute request interruption when setting the `NavigationRerouteController` [#5950](https://github.com/mapbox/mapbox-navigation-android/pull/5950).
+- Introduced `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`, which is called after the routes passed to `MapboxNavigation#setNavigationRoutes` are processed or are failed to be processed [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
+- `RoutesObserver#onRoutesChanged` will not be triggered if tha navigator fails to process the routes passed via `MapboxNavigation#setNavigationRoutes` [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```
Comment (VysotskiVadim) [inline CHANGELOG.md:11]: maybe?
```suggestion
- `RoutesObserver#onRoutesChanged` will not be triggered if the navigator fails to process routes passed via `MapboxNavigation#setNavigationRoutes` [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```

File: CHANGELOG.md [hunk 18]
```diff
@@ -7,6 +7,8 @@ Mapbox welcomes participation and contributions from everyone.
 
 #### Bug fixes and improvements
 - Fixed reroute request interruption when setting the `NavigationRerouteController` [#5950](https://github.com/mapbox/mapbox-navigation-android/pull/5950).
+- Introduced `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`, which is called after the routes passed to `MapboxNavigation#setNavigationRoutes` are processed or are failed to be processed [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```
Comment (VysotskiVadim) [inline CHANGELOG.md:10]: Maybe?
```suggestion
- Introduced `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`. The callback is called after new routes are processed or are failed to be processed [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 14 above)
[the remark this answers is not in the document]
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:777]: I'd not introduce a new API without needs, it will require support, but we don't have any requests for it.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt (hunk 16 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:81]: it works, as std lib has `Any?.hasCode()` extension 😎 
agree, would be great to set value to non-null

**Comment by Guardiola31337** [comment]
Noting that Ktlint is ❌ 

```
> Task :libnavigator:ktlint FAILED
/root/code/libnavigator/src/main/java/com/******/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt:209:1: Exceeded max line length (100) (cannot be auto-corrected) (max-line-length)
/root/code/libnavigator/src/main/java/com/******/navigation/navigator/internal/MapboxNativeNavigatorImpl.kt:252:1: Exceeded max line length (100) (cannot be auto-corrected) (max-line-length)

FAILURE: Build failed with an exception.
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt (hunk 16 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:81]: Yes, it's not nullable anymore.

File: CHANGELOG.md (hunk 18 above)
Comment (dzinad) [reply CHANGELOG.md:10]: Why do you want to remove the specification of the routes ("passed to `MapboxNavigation#setNavigationRoutes`")? "New routes" sounds vague.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 19]
```diff
@@ -791,21 +799,33 @@ class MapboxNavigation @VisibleForTesting internal constructor(
...
+                when (val processedRoutes = setRoutesToTripSession(routes, legIndex, reason)) {
+                    is NativeSetRouteValue -> {
+                        directionsSession.setRoutes(routes, legIndex, reason)
+                        callback?.onRoutesSetResult(RoutesSetCallbackSuccess(routes))
+                    }
+                    is NativeSetRouteError -> {
+                        logW("Routes $routes will be ignored as they are not valid")
+                        callback?.onRoutesSetError(
+                            RoutesSetCallbackError(routes, processedRoutes.error)
+                        )
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:826]: I think it would be nice to have an instrumentation test for this case. WDYT?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt [hunk 20]
```diff
@@ -2,6 +2,24 @@ package com.mapbox.navigation.core.trip.session
...
+ * Represents what native navigator returned after `setRoute` invocation.
+ * Can be either [NativeSetRouteValue] for success or [NativeSetRouteError] for failure.
+ */
+internal sealed class NativeSetRouteResult
+
+/**
+ * Represents successful setting of routes to native navigator.
+ * @param nativeAlternatives Set routes.
+ */
+internal class NativeSetRouteValue(
```
[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/NativeSetRouteResult.kt:15]: Too long, IMHO. I suppose it could be sth like `NativeSetRouteSuccess`, but I don't really see the difference from the current name.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt [hunk 21]
```diff
@@ -96,24 +96,29 @@ internal class MapboxTripSession(
...
+                if (routes.isNotEmpty()) {
                     val primaryRoute = routes.first()
                     val alternatives = navigator.refreshRoute(primaryRoute)
                     roadObjects = getRouteInitInfo(primaryRoute.nativeRoute().routeInfo)
                         ?.roadObjects
                         ?: emptyList()
                     this@MapboxTripSession.primaryRoute = routes.first()
-                    alternatives
+                    alternatives.fold({
+                        NativeSetRouteError(it)
```
[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/session/MapboxTripSession.kt:112]: I'm not sure what changed in the behaviour here. The method is called exactly when it used to be called. The returned result only affects setting the routes to DirectionsSession and processing alternative metadata. I don't see how the `RouteRefreshController` is affected, could you explain please?

File: libnavigation-core/api/current.txt [hunk 22]
```diff
@@ -105,6 +106,23 @@ package com.mapbox.navigation.core {
     method public void onSwitchToTargetVersion(String? tilesVersion);
   }
 
+  public interface RoutesSetCallback {
+    method public void onRoutesSetError(com.mapbox.navigation.core.RoutesSetCallbackError result);
+    method public void onRoutesSetResult(com.mapbox.navigation.core.RoutesSetCallbackSuccess result);
+  }
```
[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/api/current.txt:112]: I think we can avoid it. We can introduce a new callback and mark this one as deprecated. Or provide the default implementation. The alternative is to introduce `onCancelled` method and not provide the opportunity to cancel. I'd find that confusing.

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt (hunk 12 above)
Comment (RingerJK) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt:486]: `routeAlternativesController.processAlternativesMetadata` doesn't affect reason or otherwise, if you mean it

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 19 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:826]: It turned out for now there's no such case when route is parsed successfully but `setRoutes` returns the error. However, it can filter out some of the alternatives if they have less than 3 intersections. Do you think the behaviour now is OK? Practically, SDK will never invoke `onRoutesSetError`. We could check if alternatives were filtered out, if the result list is empty and so on. But probably it's better to check for the error, just like it's implemented now. WDYT? @RingerJK @VysotskiVadim

Comment (VysotskiVadim) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:826]: After some discussion with NN we found a case when it could happen: wrong leg index. They also said that the logic of setting routes is still pretty complex and they can not guarantee always good result. So it makes sense to handle errors.

Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:826]: > We could check if alternatives were filtered out, if the result list is empty and so on.

I like this idea. It works if NN explicitly provides this info to the platform in the callback, then we don't have concerns. I think we should be good to keep API as + cut a ticket for NN and track it separately

File: libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt [hunk 23]
```diff
@@ -395,6 +411,152 @@ internal class MapboxNavigationTest : MapboxNavigationBaseTest() {
...
+        coEvery {
+            tripSession.setRoutes(any(), any(), any())
+        } returns NativeSetRouteValue(emptyList())
+
+        createMapboxNavigation()
+        mapboxNavigation.setRerouteController(oldController)
+        mapboxNavigation.setRerouteController(rerouteController)
+        coVerify(exactly = 1) {
+            directionsSession.setRoutes(any(), 0, RoutesExtra.ROUTES_UPDATE_REASON_REROUTE)
+        }
```
[the remark this answers is not in the document]
Comment (RingerJK) [reply libnavigation-core/src/test/java/com/mapbox/navigation/core/MapboxNavigationTest.kt:534]: agree, it's out of PR scope. Let's discuss it separately

**Comment by RingerJK** [comment]
could you address git conflict and CI issues, I'll have a look again 👀

**Comment by dzinad** [comment]
> could you address git conflict and CI issues, I'll have a look again 👀

Done. As I understand, I can skip codecov -0.05% failure? I guess that's because of `toString`, `hashCode`/`equals` methods.

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt [hunk 24]
```diff
@@ -0,0 +1,113 @@
...
+                RouteOptions.builder()
+                    .coordinatesList(mockRoute.routeWaypoints)
+                    .profile(DirectionsCriteria.PROFILE_DRIVING_TRAFFIC)
+                    .build()
+            )
+            .build()
+            .toNavigationRoute(RouterOrigin.Custom())
+        val routes = listOf(route)
+        mapboxNavigation.setNavigationRoutes(routes, callback = callback)
+        countDownLatch.await(1, TimeUnit.MINUTES)
```
Comment (RingerJK) [inline instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt:87]: should be a problem if can be almost 1 min 🤔 let's set it to 5 seconds, it will help to catch potential regression. Here and below in tests 
```suggestion
        countDownLatch.await(5, TimeUnit.SECONDS)
```

**Review by RingerJK — APPROVED** [review]
LGTM with one nit 🚀

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt (hunk 24 above)
Comment (dzinad) [reply instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt:87]: It was the first thing that came to mind. It executes much faster. Just didn't want the test to be flaky if some emulators start lagging. Reduced the timeout.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt (hunk 19 above)
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:827]: Created an issue and cc'ed you.

File: instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt (hunk 24 above)
[the remark this answers is not in the document]
Comment (dzinad) [reply instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/SetRoutesTest.kt:87]: I don't see why not but do you mind if I do it in a separate PR? This one already has 95 comments and 11 commits (and who knows how many force-pushes), I don't want to keep it open for much longer.

File: CHANGELOG.md [hunk 25]
```diff
@@ -53,6 +53,8 @@ This release depends on, and has been tested with, the following Mapbox dependen
 - Mapbox Java `v6.6.0` ([release notes](https://github.com/mapbox/mapbox-java/releases/tag/v6.6.0))
 - Mapbox Android Core `v5.0.1`
 - Mapbox Android Telemetry `v8.1.2`
+- Introduced `RoutesSetCallback` parameter to `MapboxNavigation#setNavigationRoutes`, which is called after the routes passed to `MapboxNavigation#setNavigationRoutes` are processed or are failed to be processed [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
+- `RoutesObserver#onRoutesChanged` will not be triggered if the navigator fails to process routes passed via `MapboxNavigation#setNavigationRoutes` [#5945](https://github.com/mapbox/mapbox-navigation-android/pull/5945).
```
Comment (Zayankovsky) [inline CHANGELOG.md:57]: Move changelog to the appropriate section.

Comment (Zayankovsky) [reply CHANGELOG.md:57]: And update it according to the guidelines: https://github.com/mapbox/navigation-sdks/blob/main/documentation/android-changelog-guidelines.md.

Comment (dzinad) [reply CHANGELOG.md]: Thanks. How do you usually keep track that changelog is not messed up after rebase?

Comment (Zayankovsky) [reply CHANGELOG.md]: By reviewing the changes myself. We should probably improve our validate-changelog.py script to verify that the changelog is located in the proper section. 
By the way, your changelog contains wrong links and dots are in the wrong places.

Comment (dzinad) [reply CHANGELOG.md]: If I were a lawyer, I could argue about the dots... The guideline says:
> Begin each changelog entry with a capitalized past tense verb and end it with a period.

That's exactly as I did it. It's different in examples tho. Corrected.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt [hunk 26]
```diff
@@ -792,21 +800,33 @@ class MapboxNavigation @VisibleForTesting internal constructor(
...
+                    }
+                }
```
Comment (LukasPaczos) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:829]: I just now see that this is already implemented and actually suffers from the issue I mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/5938#discussion_r915770292.

The `NavigationSession.setRoutes(routes)` should not be called if `DirectionsSession.setRoutes(routes, legIndex, reason)` wasn't.

Comment (LukasPaczos) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt:829]: Tracking in https://github.com/mapbox/mapbox-navigation-android/issues/6023.

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt [hunk 27]
```diff
@@ -0,0 +1,107 @@
...
+    fun onRoutesSetResult(result: RoutesSetCallbackSuccess)
+
+    /**
+     * Invoked whenever the routes passed to [MapboxNavigation.setNavigationRoutes]
+     * produce an error and are ignored.
+     *
+     * @param result [RoutesSetCallbackError] object that describes the failure.
+     */
+    fun onRoutesSetError(result: RoutesSetCallbackError)
+}
```
Comment (LukasPaczos) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:26]: How about this instead:
```kotlin
fun interface RoutesSetCallback {
    fun onRoutesSet(result: Expected<RoutesSetError, RoutesSetSuccess>)
}
```

Much more concise and easier to consume from Kotlin (and Java as well).

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt [hunk 28]
```diff
@@ -0,0 +1,107 @@
...
+
+/**
+ * Represents the result of setting routes. See [RoutesSetCallback.onRoutesSetResult].
+ *
+ * @param routes List of routes that were successfully set.
+ */
+class RoutesSetCallbackSuccess internal constructor(
+    val routes: List<NavigationRoute>
+) {
```
[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:35]: Good question. I'm not sure if it's a success of a failure. So here are a bunch of options:
1. We change the API to
```
fun interface RoutesSetCallback {
    fun onRoutesSet(result: RoutesSetResult)
}
```
where `RoutesSetResult` is a sealed class with 3 subclasses: Success, PrimaryRouteNotSet, NotAllAlternativesSet (the names are very raw).
2. We leave the interface as-is and add a third method `onAlternativesFilteredOut` (and maybe rename `onRoutesSetError` into `onPrimaryRouteSetError`). But that would break API in the future and for now the third method will never be invoked.
3. We change the API to
```
fun interface RoutesSetCallback {
    fun onRoutesSet(result: RoutesSetResult)
}
```
where `RoutesSetResult` is a data class that contains all info: whether the primary route was set, which alternatives were set, which alternatives were ignored, etc. Maybe there would be a status (3 possible values for now).

I personally like the first option: I find it easier to use both when you need to just check the status and get the additional info.
WDYT? @LukasPaczos

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt (hunk 27 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:26]: @LukasPaczos I think we don't expose `Expected`, do we?

Comment (LukasPaczos) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:26]: We do, it's a viable public API. A lot of Common SDK, Maps SDK, as well as our Nav UI components rely on it, less so Nav Core components but that's not a rule (we probably just had less opportunity to return result-based callbacks in the past).

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt (hunk 28 above)
[the remark this answers is not in the document]
Comment (dzinad) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/RoutesSetCallback.kt:35]: https://github.com/mapbox/mapbox-navigation-android/pull/6040
