### PR TITLE
Provide example of showing and hiding Fragment with NavigationView

### LINKED ISSUE #1109: App crashes for second time NavigationView initialized
**Android API:** `NavigationView$initialize`, `NavigationView$stopNavigation` and `NavigationView$.onDestroy`

**Mapbox Navigation SDK version:**  `android-navigation-ui:0.16.0-SNAPSHOT`

### Steps to trigger behavior
We have a single activity to manage all fragments included the one having `NavigationView`. We do not close this activity and mange all fragment transactions on demand.

- We call `NavigationView$initialize` to initialize NavigationView via `OnNavigationReadyCallback` (App crashes here when user came back from another fragment).
- We call `NavigationView$stopNavigation` when we needs to end navigation without finishing the whole view.
- We call `NavigationView$.onDestroy` for `Fragment$onDestroyView`

### Expected behavior
Navigation should work for every iteration.

### Actual behavior
After completing a ride or user moves to another screen / fragment and comes back to start navigation with `NavigationView` app crashes.

Without destroying an `Activity` there must be a way to reinitialize `NavigationView`. Second attempt to call `NavigationView$initialize` (in a same activity or fragment) crashes the app.

### Crash log
Logcat only gives this crash report.

```
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad: Chrome build fingerprint:
W/google-breakpad: 67.0.3396.87
W/google-breakpad: 339608752
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x646168b3 in tid 32429 (app.package.name), pid 32429 (app.package.name)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1109 

This PR iterates on the `Fragment` example we provide in the test app.  Now we demonstrate how to show / hide a `Fragment` inflating a `NavigationView` with a `FragmentTransaction`.  

ezgif com-video-to-gif

### CODE REVIEW

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java [hunk 1]
```diff
@@ -258,6 +260,7 @@ private void addMilestones(NavigationViewOptions options) {
   private ProgressChangeListener progressChangeListener = new ProgressChangeListener() {
     @Override
     public void onProgressChange(Location location, RouteProgress routeProgress) {
+      Timber.d("NAV_DEBUG - onProgressChange");
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: I imagine this slipped in by mistake (debugging purposes). We should remove this log.
