### PR TITLE
Remove NavigationCamera ProgressChangeListener as public api

### LINKED ISSUE #826: IllegalArgumentException thrown using NavigationCamera
**Android API:** Oreo 8.0.0

**Mapbox SDK versions:**
`mapbox-android-sdk:5.5.0`
`mapbox-android-plugin-locationlayer:0.4.0`
`mapbox-sdk-services:3.0.1`
`mapbox-sdk-services:3.0.1`
`mapbox-android-navigation:0.12.0`
`mapbox-android-navigation-ui:0.12.0`

### Steps to trigger behavior

Try to use a NavigationCamera object like this:

```mapboxNavigation.setLocationEngine(locationEngine);
      navigationCamera = new NavigationCamera(mapboxMap, mapboxNavigation);
      mapboxNavigation.startNavigation(route);
      navigationCamera.start(route);
      navigationCamera.setCameraTrackingLocation(true);
      locationPlugin.setLocationLayerEnabled(LocationLayerMode.NAVIGATION); 
```

### Expected behavior
The `NavigationCamera` object smoothly handles camera updates.

### Actual behavior

An `IllegalArgumentException` is thrown, leading app to crash:

```
java.lang.IllegalArgumentException: Null duration passed into easeCamera
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:836)
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:807)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.easeMapCameraPosition(NavigationCamera.java:191)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.animateCameraFromLocation(NavigationCamera.java:258)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.onProgressChange(NavigationCamera.java:102)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:156)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:117)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:91)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 ```

It seems the exception is thrown consistently when `navigationCamera.onProgressChange(location, routeProgress)` is called from `onProgressChange(Location location, RouteProgress routeProgress)` callback.

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #826

### CODE REVIEW

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java [hunk 1]
```diff
@@ -139,6 +121,25 @@ public void resetCameraPosition() {
...
+  /**
+   * Used to update the camera position.
+   * <p>
+   * {@link Location} is also stored in case the user scrolls the map and the camera
+   * will eventually need to return to that last location update.
+   *
+   * @param location      used to update the camera position
+   * @param routeProgress ignored in this scenario
+   */
+  ProgressChangeListener progressChangeListener = new ProgressChangeListener() {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java]: NIT Could we move this up with the rest of the variables?

File: libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCameraTest.java [hunk 2]
```diff
@@ -1,25 +1,19 @@
...
 
 import static junit.framework.Assert.assertFalse;
 import static junit.framework.Assert.assertNotNull;
 import static junit.framework.Assert.assertTrue;
 import static org.mockito.Mockito.times;
 import static org.mockito.Mockito.verify;
 
-@RunWith(RobolectricTestRunner.class)
-@Config(constants = BuildConfig.class, manifest = Config.DEFAULT_MANIFEST_NAME)
 public class NavigationCameraTest {
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCameraTest.java]: NIT This is a great opportunity to refactor the tests 🎉
In general, we should avoid inline setup 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=65
Could you remove `navigation` and `mapboxMap` mock variables and extract https://github.com/mapbox/mapbox-navigation-android/blob/98ffc5e84daa8d2f33abc41826cb60b05b9dd94c/libandroid-navigation-ui/src/test/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCameraTest.java#L35-L36 code into a `private` "factory" method called for example `setupCamera` and use it across the tests?
IMO, it reflects better what's going on in the test and you don't break the [triple A](https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40) "rule".
