### PR TITLE
Fixing `examples` test app LocationComponent race condition

### LINKED ISSUE #2942: Examples crash with Style loading race condition
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. Open examples, Faster Route
 2. Crash sometimes

```
2020-05-08 14:16:51.578 9478-9478/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 9478
    com.mapbox.mapboxsdk.location.LocationComponentNotInitializedException: The LocationComponent has to be activated with one of the LocationComponent#activateLocationComponent overloads before any other methods are invoked.
        at com.mapbox.mapboxsdk.location.LocationComponent.checkActivationState(LocationComponent.java:1712)
        at com.mapbox.mapboxsdk.location.LocationComponent.forceLocationUpdate(LocationComponent.java:913)
        at com.mapbox.navigation.examples.core.FasterRouteActivity$MyLocationEngineCallback.onSuccess(FasterRouteActivity.kt:290)
        at com.mapbox.navigation.examples.core.FasterRouteActivity$MyLocationEngineCallback.onSuccess(FasterRouteActivity.kt:283)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:136)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:125)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Expected behavior

Tricky lifecycle and asynchronous issues waiting for styles to load, classic 

### Actual behavior

When you register in onStart, this will have race conditions with styles loading. The crash above is an example of one of these race conditions. But they seem to be all over.
``` kotlin
    override fun onStart() {
        super.onStart()
        mapView.onStart()
        navigationMapboxMap?.onStart()
        mapboxNavigation.registerTripSessionStateObserver(tripSessionStateObserver)
    }
```
https://github.com/mapbox/mapbox-navigation-android/blob/752a5c65436f63f585b6037a960bec7bd7a552e1/examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt#L100

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2942 

The locationComponent is initialized until `navigationMapboxMap` been created. So not assign `mapboxMap` variable until style is loaded and everything is set up.

```kotlin
    override fun onMapReady(mapboxMap: MapboxMap) {
        mapboxMap.setStyle(Style.MAPBOX_STREETS) {
            mapboxMap.moveCamera(CameraUpdateFactory.zoomTo(15.0))
            navigationMapboxMap = NavigationMapboxMap(mapView, mapboxMap, true)
            this.mapboxMap = mapboxMap
        }
```

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by kmadsen** [comment]
Is this needed by any other examples?

File: examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt [hunk 1]
```diff
@@ -198,10 +198,10 @@ class FasterRouteActivity : AppCompatActivity(), OnMapReadyCallback {
     }
 
     override fun onMapReady(mapboxMap: MapboxMap) {
-        this.mapboxMap = mapboxMap
```
Comment (kmadsen) [inline examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt:201]: Some crashes are exchanged with no-op bugs?

**Comment by LukasPaczos** [comment]
> The locationComponent is initialized until navigationMapboxMap been created.

That's definitely the reason of the crash.

I think it might be easier to understand the fix if `LocationComponent#isLocationComponentActivated` was used before calling https://github.com/mapbox/mapbox-navigation-android/blob/462a94ead1bbad080e8a6ad70e3fb6f8d553d234/examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt#L294 instead of reshuffling the initialization of variables.

**Comment by JunDai** [comment]
> > The locationComponent is initialized until navigationMapboxMap been created.
> 
> That's definitely the reason of the crash.
> 
> I think it might be easier to understand the fix if `LocationComponent#isLocationComponentActivated` was used before calling
> 
> https://github.com/mapbox/mapbox-navigation-android/blob/462a94ead1bbad080e8a6ad70e3fb6f8d553d234/examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt#L294
> 
> instead of reshuffling the initialization of variables.

sounds good, changed the fix and verified it works!

**Comment by JunDai** [comment]
> Is this needed by any other examples?

no, I checked our other examples.

File: examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt [hunk 2]
```diff
@@ -287,7 +289,9 @@ class FasterRouteActivity : AppCompatActivity(), OnMapReadyCallback {
 
         override fun onSuccess(result: LocationEngineResult?) {
             result?.locations?.firstOrNull()?.let {
-                activityRef.get()?.mapboxMap?.locationComponent?.forceLocationUpdate(it)
+                if (activityRef.get()?.mapboxMap?.locationComponent?.isLocationComponentActivated == true) {
+                    activityRef.get()?.mapboxMap?.locationComponent?.forceLocationUpdate(it)
+                }
```
Comment (langsmith) [inline examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt:294]:
```suggestion
                if (activityRef.get()?.mapboxMap?.locationComponent?.isLocationComponentActivated!!) {
                    activityRef.get()?.mapboxMap?.locationComponent?.forceLocationUpdate(it)
                }
```

**Comment by langsmith** [comment]
Above the `class FasterRouteActivity : AppCompatActivity(), OnMapReadyCallback {` line, can we add:

```
/**
 * This example shows how to use the Navigation SDK's [FasterRouteObserver]
 * and display the observer's faster routes that are returned if the 
 * device goes off of the original [DirectionsRoute].
 */
```

File: examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt (hunk 2 above)
Comment (JunDai) [reply examples/src/main/java/com/mapbox/navigation/examples/core/FasterRouteActivity.kt:294]: this won't work because the mapboxMap isn't initialized at that moment. It will crash.
