### PR TITLE
Fix OffRoute engine cleared before service shutdown

### LINKED ISSUE #1139: OffRoute#isUserOffRoute NullPointerException
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.navigation.v5.offroute.OffRoute.isUserOffRoute(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress, com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.isUserOffRoute(NavigationHelper.java:478)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.determineUserOffRoute(RouteProcessorHandlerCallback.java:74)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleRequest(RouteProcessorHandlerCallback.java:51)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleMessage(RouteProcessorHandlerCallback.java:33)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Actually Fixes #1139 

We are setting the camera engine to `null` here because it holds onto `MapboxMap` and is then given to `MapboxNavigation`.  

For the turn-by-turn UI, `MapboxNavigation` survives rotation, so we need to set it to null so it doesn't leak.

### CODE REVIEW

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java [hunk 1]
```diff
@@ -97,6 +97,7 @@ public void onDestroy(boolean isChangingConfigurations) {
       deactivateInstructionPlayer();
       endNavigation();
     }
+    navigation.setCameraEngine(null);
```
Comment (Guardiola31337) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewModel.java]: This is currently doing nothing 👀 

```java
public void setCameraEngine(@NonNull Camera cameraEngine) {
  navigationEngineFactory.updateCameraEngine(cameraEngine);
}
```
👇 
```java
void updateCameraEngine(Camera cameraEngine) {
  if (cameraEngine == null) {
    return;
  }
  this.cameraEngine = cameraEngine;
}
```

Also, note
> Passing 'null' argument to parameter annotated as `@NotNull`
