### PR TITLE
Kyv offboard fails on multiple requests 

### LINKED ISSUE #2329: OffboarRouter fails on multiple route requests
When `MapboxOffbaordRouter` is used to request a route, the first request behaves correctly, however, each following one fails with error code `422`.

/cc @RingerJK @Lebedinsky

### PR DESCRIPTION
**Pull request by RingerJK**
## Description

Fix issue: When `MapboxOffbaordRouter` is used to request a route, the first request behaves correctly, however, each following one fails with error code 422.

Closes #2329 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ import retrofit2.Callback
  * 1.0
  */
 
-class NavigationRoute
+class NavigationOffboardRoute
```
Comment (LukasPaczos) [inline libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt]: This class can be internal, right?

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt [hunk 2]
```diff
@@ -85,7 +91,7 @@ class NavigationController {
                 )
             )
             OffboardRouter -> arrayOf(
-                Context::class.java to context
+                NavigationOffboardRoute::class.java to navigationOffboardRoute
```
Comment (LukasPaczos) [inline libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: This leaks `NavigationOffboardRoute` to the controller. Why can't we use the `(accessToken, context)` constructor?

File: libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt [hunk 3]
```diff
@@ -7,28 +7,28 @@ import com.mapbox.api.directions.v5.models.DirectionsResponse
...
-import com.mapbox.navigation.route.offboard.router.NavigationRoute
+import com.mapbox.navigation.route.offboard.router.NavigationOffboardRoute
 import com.mapbox.navigation.utils.exceptions.NavigationException
 import retrofit2.Call
 import retrofit2.Callback
 import retrofit2.Response
 
 @MapboxNavigationModule(MapboxNavigationModuleType.OffboardRouter, skipConfiguration = true)
-class MapboxOffboardRouter(private val routeBuilder: NavigationRoute.Builder) : Router {
+class MapboxOffboardRouter(private val routeBuilder: NavigationOffboardRoute) : Router {
```
Comment (korshaknn) [inline libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/MapboxOffboardRouter.kt]: is it a `builder` or a route? param name and type are little confusing

File: libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt [hunk 4]
```diff
@@ -52,7 +52,7 @@ class NavigationRouteTest {
     @Test
     @Throws(Exception::class)
     fun sanityTest() {
-        val navigationRoute = NavigationRoute.builder(context)
+        val navigationRoute = NavigationOffboardRoute.builder(ACESS_TOKEN, context)
```
Comment (korshaknn) [inline libdirections-offboard/src/test/java/com/mapbox/navigation/route/offboard/router/NavigationRouteTest.kt]:
```suggestion
        val navigationRoute = NavigationOffboardRoute.builder(ACESS_TOKEN, context)
```
many tests have the same line. maybe move it to a separate fun. 
like `buildNavigationRoute() = NavigationOffboardRoute.builder(ACESS_TOKEN, context)`

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt (hunk 2 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: `MapboxDirection` checks if access token is valid by pattern, so if I create it under the hood it throws exception

File: libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt (hunk 1 above)
Comment (RingerJK) [reply libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt]: nope, this class is provided by developer

**Comment by RingerJK** [comment]
@LukasPaczos in my approach user shouldn't even know that default points exist. `RouteOptions` forces him to pass `origin` and `destination`. It's limits of `MapboxDirection`. If you have a look at constructor `NavigationOffboardRoute`: here we apply `MapboxDirections` as a parameter and to create this on user shoul pass origin, desination and access token. So we make the same, just to create immutable instance of `MapboxDirections`. 

Could you clarify your suggestion with `object` and builder? I don't really like second idea because I have to handle every value by hands

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt (hunk 2 above)
Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: I believe that @LukasPaczos is referring to implement something like this 👇 

```diff
diff --git a/libandroid-navigation-ui/src/main/assets/sdk_versions/com.mapbox.services.android.navigation.ui.v5 b/libandroid-navigation-ui/src/main/assets/sdk_versions/com.mapbox.services.android.navigation.ui.v5
deleted file mode 100644
index 5cf16b8c..00000000
--- a/libandroid-navigation-ui/src/main/assets/sdk_versions/com.mapbox.services.android.navigation.ui.v5
+++ /dev/null
@@ -1,2 +0,0 @@
-libandroid-navigation-ui/0.43.0-SNAPSHOT
-v-1
diff --git a/libandroid-navigation/src/main/assets/sdk_versions/com.mapbox.services.android.navigation b/libandroid-navigation/src/main/assets/sdk_versions/com.mapbox.services.android.navigation
deleted file mode 100644
index 9af9ac52..00000000
--- a/libandroid-navigation/src/main/assets/sdk_versions/com.mapbox.services.android.navigation
+++ /dev/null
@@ -1,2 +0,0 @@
-libandroid-navigation/0.43.0-SNAPSHOT
-v-1
diff --git a/libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt b/libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt
index d59e71d2..dddc0267 100644
--- a/libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt
+++ b/libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt
@@ -21,7 +21,6 @@ import com.mapbox.navigation.base.route.model.Route
 import com.mapbox.navigation.directions.session.DirectionsSession
 import com.mapbox.navigation.module.NavigationModuleProvider
 import com.mapbox.navigation.navigator.MapboxNativeNavigator
-import com.mapbox.navigation.route.offboard.router.NavigationOffboardRoute
 import com.mapbox.navigation.trip.notification.NavigationNotificationProvider
 import com.mapbox.navigation.trip.service.TripService
 import com.mapbox.navigation.trip.session.TripSession
@@ -35,9 +34,9 @@ class NavigationController {
     private val navigator: MapboxNativeNavigator
     private val locationEngine: LocationEngine
     private val locationEngineRequest: LocationEngineRequest
-    private val navigationOffboardRoute: NavigationOffboardRoute
     private val navigationNotificationProvider: NavigationNotificationProvider
     private val context: Context
+    private val accessToken: String
 
     private val mainHandler: Handler by lazy { Handler(Looper.getMainLooper()) }
     private val workerHandler: Handler by lazy { Handler(workerThread.looper) }
@@ -52,19 +51,19 @@ class NavigationController {
 
     constructor(
         context: Context,
+        accessToken: String,
         navigator: MapboxNativeNavigator,
         locationEngine: LocationEngine,
         locationEngineRequest: LocationEngineRequest,
         tripServiceLambda: () -> Unit,
-        navigationOffboardRoute: NavigationOffboardRoute,
         navigationNotificationProvider: NavigationNotificationProvider
     ) {
         this.context = context
+        this.accessToken = accessToken
         this.navigator = navigator
         this.locationEngine = locationEngine
         this.locationEngineRequest = locationEngineRequest
         this.navigationNotificationProvider = navigationNotificationProvider
-        this.navigationOffboardRoute = navigationOffboardRoute
 
         logger = NavigationModuleProvider.createModule(LoggerModule, ::paramsProvider)
         directionsSession = NavigationComponentProvider.createDirectionsSession(
@@ -117,7 +116,8 @@ class NavigationController {
                 )
             )
             OffboardRouter -> arrayOf(
-                NavigationOffboardRoute::class.java to navigationOffboardRoute
+                String::class.java to accessToken,
+                Context::class.java to context
             )
             OnboardRouter -> arrayOf(
                 MapboxNativeNavigator::class.java to navigator
diff --git a/libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt b/libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt
index 1d6ad48f..6aac78db 100644
--- a/libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt
+++ b/libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt
@@ -5,7 +5,6 @@ import android.content.Context
 import com.mapbox.android.core.location.LocationEngine
 import com.mapbox.android.core.location.LocationEngineRequest
 import com.mapbox.navigation.navigator.MapboxNativeNavigator
-import com.mapbox.navigation.route.offboard.router.NavigationOffboardRoute
 import com.mapbox.navigation.trip.notification.NavigationNotificationProvider
 import com.mapbox.navigation.utils.extensions.inferDeviceLocale
 import io.mockk.every
@@ -25,10 +24,10 @@ class NavigationControllerTest {
 
     private lateinit var navigationController: NavigationController
     private val context: Context = mockk(relaxed = true)
+    private val accessToken: String = "pk.XXX"
     private val navigator: MapboxNativeNavigator = mockk()
     private val locationEngine: LocationEngine = mockk()
     private val locationEngineRequest: LocationEngineRequest = mockk()
-    private val navigationOffboardRoute: NavigationOffboardRoute = mockk()
     private val navigationNotificationProvider: NavigationNotificationProvider = mockk()
     private val tripServiceLambda: () -> Unit = mockk()
 
@@ -49,11 +48,11 @@ class NavigationControllerTest {
         navigationController =
             NavigationController(
                 context,
+                accessToken,
                 navigator,
                 locationEngine,
                 locationEngineRequest,
                 tripServiceLambda,
-                navigationOffboardRoute,
                 navigationNotificationProvider
             )
     }
```

Comment (Guardiola31337) [reply libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: > `MapboxDirection` checks if access token is valid by pattern, so if I create it under the hood it throws exception 

Yeah, that's correct 👀 

https://github.com/mapbox/mapbox-java/blob/3d4297ec822275edb41849c95bfef5f6c4c1615b/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L966-L969

https://github.com/mapbox/mapbox-java/blob/3d4297ec822275edb41849c95bfef5f6c4c1615b/services-core/src/main/java/com/mapbox/core/utils/MapboxUtils.java#L23-L26

Note

```kotlin
private val accessToken: String = "pk.XXX"
```

Using a "valid" access token (`"pk."`) works 👌

Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: @Guardiola31337 for this I need valid access token, because as I said `DirectionSession` checks one under the hood

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt [hunk 5]
```diff
@@ -31,11 +32,13 @@ import kotlinx.coroutines.InternalCoroutinesApi
 @ExperimentalCoroutinesApi
 class NavigationController {
 
-    private val context: Context
     private val navigator: MapboxNativeNavigator
     private val locationEngine: LocationEngine
     private val locationEngineRequest: LocationEngineRequest
+    private val navigationOffboardRoute: NavigationOffboardRoute
```
Comment (Guardiola31337) [inline libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: This is not needed / used 👀 https://github.com/mapbox/mapbox-navigation-android/pull/2332#discussion_r361965898

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt [hunk 6]
```diff
@@ -50,17 +53,21 @@ class NavigationController {
 
     constructor(
         context: Context,
+        accessToken: String,
         navigator: MapboxNativeNavigator,
         locationEngine: LocationEngine,
         locationEngineRequest: LocationEngineRequest,
         tripServiceLambda: () -> Unit,
+        navigationOffboardRoute: NavigationOffboardRoute,
```
Comment (Guardiola31337) [inline libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: Same as above re: `NavigationOffboardRoute` not used

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt [hunk 7]
```diff
@@ -50,17 +53,21 @@ class NavigationController {
...
         navigationNotificationProvider: NavigationNotificationProvider
     ) {
         this.context = context
+        this.accessToken = accessToken
         this.navigator = navigator
         this.locationEngine = locationEngine
         this.locationEngineRequest = locationEngineRequest
         this.navigationNotificationProvider = navigationNotificationProvider
+        this.navigationOffboardRoute = navigationOffboardRoute
```
Comment (Guardiola31337) [inline libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: Same as above re: `NavigationOffboardRoute` not used

File: libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt [hunk 8]
```diff
@@ -24,9 +25,11 @@ class NavigationControllerTest {
 
     private lateinit var navigationController: NavigationController
     private val context: Context = mockk(relaxed = true)
+    private val accessToken = "pk.XXX"
     private val navigator: MapboxNativeNavigator = mockk()
     private val locationEngine: LocationEngine = mockk()
     private val locationEngineRequest: LocationEngineRequest = mockk()
+    private val navigationOffboardRoute: NavigationOffboardRoute = mockk()
```
Comment (Guardiola31337) [inline libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt]: Same as above re: `NavigationOffboardRoute` not needed

File: libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt [hunk 9]
```diff
@@ -47,10 +50,12 @@ class NavigationControllerTest {
         navigationController =
             NavigationController(
                 context,
+                accessToken,
                 navigator,
                 locationEngine,
                 locationEngineRequest,
                 tripServiceLambda,
+                navigationOffboardRoute,
```
Comment (Guardiola31337) [inline libnavigation-core/src/test/java/com/mapbox/navigation/NavigationControllerTest.kt]: Same as above re: `NavigationOffboardRoute` not needed

File: libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt [hunk 10]
```diff
@@ -113,6 +120,7 @@ class NavigationController {
                 )
             )
             OffboardRouter -> arrayOf(
+                String::class.java to mapboxToken,
```
Comment (Guardiola31337) [inline libnavigation-core/src/main/java/com/mapbox/navigation/NavigationController.kt]: Typo

```suggestion
                String::class.java to accessToken,
```

File: libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt [hunk 11]
```diff
@@ -57,15 +60,21 @@ constructor(
                     DirectionsCriteria.ANNOTATION_CONGESTION,
                     DirectionsCriteria.ANNOTATION_DISTANCE
                 )
+                .routeOptions(RouteOptionsNavigation.builder()
```
Comment (Guardiola31337) [inline libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt]: What about making the required parameters in `RouteOptionsNavigation` so we don’t need to add default `origin`, `destination` and `accessToken`? Right now, these are nullable in `RouteOptionsNavigation` e.g. https://github.com/mapbox/mapbox-navigation-android/blob/1bf6dee6d0ee6a413e7339b13d86c3f50b4d31a4/libnavigation-base/src/main/java/com/mapbox/navigation/base/route/model/RouteOptionsNavigation.kt#L24

File: libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt (hunk 1 above)
Comment (LukasPaczos) [reply libdirections-offboard/src/main/java/com/mapbox/navigation/route/offboard/router/NavigationOffboardRoute.kt]: Is it? As far as I can tell it's only used internally and the route options are the public component.

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/2342 addresses most of the comments and implements the above-mentioned builder provider pattern. If y'all are okay with the changes, I'm happy to merge them into this PR.

**Comment by Guardiola31337** [comment]
> https://github.com/mapbox/mapbox-navigation-android/pull/2342 addresses most of the comments and implements the above-mentioned builder provider pattern. If y'all are okay with the changes, I'm happy to merge them into this PR.

As commented in https://github.com/mapbox/mapbox-navigation-android/pull/2342#pullrequestreview-338178941 #2342 changes look good to me. It'd be great if we could discuss adding required parameters to `RouteOptionsNavigation` so we wouldn’t need to "initialize" them https://github.com/mapbox/mapbox-navigation-android/pull/2332/files#r361986498 and implement `RouteOptionsNavigation#toBuilder` to merge here.

What do you think @LukasPaczos?
