### PR TITLE
Added fix to stop the camera from setting itself to idle when an ongoing transition is canceled.

### LINKED ISSUE #5600: Avoid setting NavigationCamera to Idle state if transition to overview or following is canceled.
Current `requestNavigationCameraToFollowing` and `requestNavigationCameraToOverview` public API(s) start their transitions with `TRANSITION_TO_FOLLOWING` and `TRANSITION_TO_OVERVIEW` respectively before finally ending with `FOLLOWING` and `OVERVIEW`. In between these transition states if the transition is canceled, the `NavigationCameraState` goes back to `Idle` state. 

The problem with this approach is that, the apps have to handle this intermediate `Idle` state although it wasn't intentional from users perspective but something that the SDK assumes. Both 1Tap and Drop-In UI are handling this scenario differently along with other customers. The aim of this ticket is remove the code that transitions camera to `Idle` state if transition to following/overview is canceled for any reason.

/cc @LukasPaczos

### PR DESCRIPTION
**Pull request by abhishek1508**
### Description

Fixes #5600

### CODE REVIEW

**Review by kmadsen — APPROVED** [review]

**Review by LukasPaczos — CHANGES_REQUESTED** [review]
Synced with @abhishek1508 that this is not ready to land and we'll want to narrow down when cancellation is ignored to only situations when that's caused by the `NavigationCamera` itself. Otherwise, we risk even more competition between code that interacts with Maps SDK camera.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt [hunk 1]
```diff
@@ -282,6 +284,7 @@ class NavigationCamera(
         frameTransitionOptions: NavigationCameraTransitionOptions = DEFAULT_FRAME_TRANSITION_OPT,
         transitionEndListener: TransitionEndListener? = null,
     ) {
+        isFromNavigationCamera = true
```
Comment (abhishek1508) [inline libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt:287]: @LukasPaczos 
I am setting this boolean flag to true inside these 2 methods `requestCameraModeToFollowing` and `requestCameraModeToOverview` which makes sense because these functions can only be invoked on `NavigationCamera`. So if the use case were as follows:
- User invokes `requestCameraModeToFollowing` followed by immediately
- User invokes `requestCameraModeToOverview`, the NavigationCamera will not go to idle state because this flag is set to true

However, if the use case is
- User invokes `requestCameraModeToFollowing` followed by immediately
- invoking an operation on mapView camera, I somehow need to set this `isFromNAvigationCamera` flag to `false`.

This is what I am trying to figure out as to how to do that and what would be the correct place to set it to false. Wdyt?

Comment (abhishek1508) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt:287]: Okay so I think I figured it out on how to set it to false. The answer is in `NavigationScaleGestureHandler` and as per public documentation 
```
### Interruptions
 * Any other camera change request outside of the [NAVIGATION_CAMERA_OWNER] and scale
 * gestures ([MapAnimationOwnerRegistry.GESTURES]) will immediately make [NavigationCamera] fallback
 * to [NavigationCameraState.IDLE] state to avoid running competing animations.
```
I am hooking onto the `owner` of the transition request. Based on the owner I decide whether to set this to true or false.

**Comment by abhishek1508** [comment]
@LukasPaczos Made the changes as discussed!

File: CHANGELOG.md [hunk 2]
```diff
@@ -33,6 +33,7 @@ This release depends on, and has been tested with, the following Mapbox dependen
 - Mapbox Java `v6.4.0-beta.3` ([release notes](https://github.com/mapbox/mapbox-java/releases/tag/v6.4.0-beta.3))
 - Mapbox Android Core `v5.0.1`
 - Mapbox Android Telemetry `v8.1.1`
+- Refactored `NavigationCamera` to not set itself to idle properties if it cancels an active transition. [#5607](https://github.com/mapbox/mapbox-navigation-android/pull/5607)
```
Comment (LukasPaczos) [inline CHANGELOG.md:36]:
```suggestion
- :warning: Realigned all `NavigationCamera` transitions to not fallback to `Idle` if a transition is canceled to keep the behavior consistent and predictable (state transitions used to be cancelable while frame transitions weren't). If you need the `NavigationCamera` to reset to `Idle` on external interactions or cancellations, use `NavigationBasicGesturesHandler` or `NavigationScaleGestureHandler`. [#5607](https://github.com/mapbox/mapbox-navigation-android/pull/5607)
```

also the entry is in the wrong place in the changelog :upside_down_face:

**Review by LukasPaczos — APPROVED** [review]
Could you also apply this diff?
```diff
diff --git a/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt b/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
index 75802e2d32..44e206248a 100644
--- a/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
+++ b/libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/camera/NavigationCamera.kt
@@ -77,7 +77,7 @@ import java.util.concurrent.CopyOnWriteArraySet
  * executing, listening for cancellation, adjusting states, etc.
  *
  * ## Gestures and other camera interactions
- * When [FOLLOWING] or [OVERVIEW] states are engaged, the `NavigationCamera` assumes full ownership
+ * The `NavigationCamera` assumes full ownership
  * of the [CameraAnimationsPlugin]. This means that if any other camera transition is scheduled
  * outside of the `NavigationCamera`’s context, there might be side-effects or glitches.
  * Consequently, if you want to perform other camera transitions,
```
