### PR TITLE
Check for valid index before updating steps in NavigationRouteProcessor

### LINKED ISSUE #1413: IndexOutOfBoundsException
I've noticed the below crash in my crashlytics - http://crashes.to/s/7b7f531f9e1

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 3
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.get(ArrayList.java:304)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.updateSteps(NavigationRouteProcessor.java:236)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.processNewIndex(NavigationRouteProcessor.java:186)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.advanceIndices(NavigationRouteProcessor.java:160)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.checkManeuverCompletion(NavigationRouteProcessor.java:145)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildNewRouteProgress(NavigationRouteProcessor.java:82)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleRequest(RouteProcessorHandlerCallback.java:49)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleMessage(RouteProcessorHandlerCallback.java:33)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Fixes #1413 

This could be a data edge case with `MapMatching` given @Danny-James setup, but still something we should guard against. 

cc @kevinkreiser something to look into here (could very well be a problem on our side) - `NavigationStatus` is providing leg / step indices that are out of bounds of the current route leg / step lists.

### CODE REVIEW

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java [hunk 1]
```diff
@@ -106,9 +106,14 @@ private RouteProgress buildRouteProgressFrom(NavigationStatus status) {
   }
 
   private void updateSteps(DirectionsRoute route, int legIndex, int stepIndex, int upcomingStepIndex) {
-    currentLeg = route.legs().get(legIndex);
+    List<RouteLeg> legs = route.legs();
+    if (legIndex < legs.size()) {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java]: Shouldn't be `<=`?

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java [hunk 2]
```diff
@@ -106,9 +106,14 @@ private RouteProgress buildRouteProgressFrom(NavigationStatus status) {
...
+      currentLeg = legs.get(legIndex);
+    }
     List<LegStep> steps = currentLeg.steps();
-    currentStep = steps.get(stepIndex);
+    if (stepIndex < steps.size()) {
```
Comment (Guardiola31337) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java]: Same here ☝️

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java (hunk 1 above)
Comment (Guardiola31337) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java]: Scratch this, it's 👌

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java (hunk 2 above)
Comment (Guardiola31337) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java]: Scratch this, it's 👌
