### PR TITLE
Fix issue #2848

### LINKED ISSUE #2848: The camera goes back and forth by doing a zoom in and zoom out
This seems a regression from the `DynamicCamera`. It's pretty easy to reproduce running a simulated session (`ReplayActivity`). It looks like there are fighting animations. This is noticeable when approaching intersections or when going off-route in which we zoomed in but now that animation is canceled and goes back causing that unexpected back and forth 👀 

dynamic_camera_fighting_animations

cc @abhishek1508 @cafesilencio

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2848 

According to the legacy code, we should only build the `currentRouteInformation` with the **location** and **routeProgress** in the `onProgressChange` callback.

#### FYI: [legacy code](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L92-L101)
```java
    public void onProgressChange(Location location, RouteProgress routeProgress) {
      currentRouteProgress = routeProgress;
      if (isTrackingEnabled()) {
        currentRouteInformation = buildRouteInformationFromLocation(location, routeProgress);
        if (!isCameraResetting) {
          adjustCameraFromLocation(currentRouteInformation);
        }
      }
    }
  };

  private RouteInformation buildRouteInformationFromLocation(Location location, RouteProgress routeProgress) {
    return new RouteInformation(null, location, routeProgress);
  }
```

The `route` field is for other scenarios use, for example:
* reset camera mode to normal
* click `overview` button from the SummaryBottomSheet

The correct camera update flow is to check if the `routeProgress` has new camera change, if yes, update it. otherwise will use the current camera zoom without checking the route info.:
```java
return mapboxMap.getCameraPosition().zoom;
```

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Please describe the PR goals. Just the stuff needed to implement the fix / feature and a simple rationale. It could contain many check points if needed

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/NavigationCamera.java [hunk 1]
```diff
@@ -414,7 +414,7 @@ void updateIsResetting(boolean isResetting) {
   private void tryToBuildRouteInformationAndAdjustCamera() {
     if (isTrackingEnabled() && currentRouteProgress != null) {
       currentRouteInformation =
-        new RouteInformation(currentRouteProgress.route(), currentLocation, currentRouteProgress);
+        new RouteInformation(null, currentLocation, currentRouteProgress);
```
Comment (Guardiola31337) [inline libnavigation-ui/src/main/java/com/mapbox/navigation/ui/camera/NavigationCamera.java:417]: Great catch!
