### PR TITLE
Fix DynamicCamera#CameraPosition.zoom NPE

### LINKED ISSUE #1969: NPE: double com.mapbox.mapboxsdk.camera.CameraPosition.zoom
### Steps to reproduce

Not sure. 

### Expected behavior

No crash.

### Actual behavior

```
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'double com.mapbox.mapboxsdk.camera.CameraPosition.zoom' on a null object reference
com.mapbox.services.android.navigation.ui.v5.camera.DynamicCamera.createZoom (DynamicCamera.java:110)
com.mapbox.services.android.navigation.ui.v5.camera.DynamicCamera.zoom (DynamicCamera.java:60)
com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.adjustCameraForReset (NavigationCamera.java:526)
com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.onCameraTransitionFinished (NavigationCamera.java:432)
com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.updateTransitionListenersFinished (NavigationCamera.java:352)
com.mapbox.services.android.navigation.ui.v5.camera.NavigationCameraTransitionListener.onLocationCameraTransitionFinished (NavigationCameraTransitionListener.java:15)
com.mapbox.mapboxsdk.location.LocationComponent$CameraTransitionListener.onLocationCameraTransitionFinished (LocationComponent.java:572)
com.mapbox.mapboxsdk.location.LocationCameraController$1.onFinish (LocationCameraController.java:135)
com.mapbox.mapboxsdk.maps.Transform$2.run (Transform.java:89)
```

### Configuration

**Android versions:** 6, 8, 9
**Device models:** Various
**Mapbox SDK versions:** 
```
com.mapbox.mapboxsdk:mapbox-android-sdk:7.4.0
com.mapbox.mapboxsdk:mapbox-android-navigation:0.38.0
com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.38.0
```

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Fixes `DynamicCamera#CameraPosition.zoom` `NullPointerException`

Fixes #1969 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

The goal here is to prevent any potential NPEs when using `MapboxNavigationMap` and `NavigationCamera` / `DynamicCamera` objects

### Implementation

Add a `position` `null` check returning `DEFAULT_ZOOM` if the `CameraPosition` created is `null` preventing `position.zoom` to happen and therefore NPEs 👀 https://github.com/mapbox/mapbox-navigation-android/blob/4b95b77203725119117e94ffe5b280fc43724a5a/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java#L110-L112

⚠️ DISCLAIMER ⚠️ This NPE isn't reproducible if lifecycle methods from `NavigationCamera` https://github.com/mapbox/mapbox-navigation-android/blob/410672dfc69cfa95296b08c4f8bdf2c14bcfde88/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/NavigationCamera.java#L275-L295 or `NavigationMapboxMap` https://github.com/mapbox/mapbox-navigation-android/blob/410672dfc69cfa95296b08c4f8bdf2c14bcfde88/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/NavigationMapboxMap.java#L461-L483 are called as part of the `Activity` / `Fragment` lifecycle 👀 [`ComponentNavigationActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/ComponentNavigationActivity.java) for further details on how to use these UI components

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

cc @hrach

### CODE REVIEW

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java [hunk 1]
```diff
@@ -107,6 +107,9 @@ private double createTilt(double distanceRemaining) {
    */
   private double createZoom(RouteInformation routeInformation) {
     CameraPosition position = createCameraPosition(routeInformation.location(), routeInformation.routeProgress());
+    if (position == null) {
```
Comment (andrlee) [inline libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java]: I'm still unsure how will we end up getting null ref returned by `createCameraPosition`?

Comment (Guardiola31337) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java]: https://github.com/mapbox/mapbox-navigation-android/blob/d382c3ab6de763f870f2f0202ab77e1ba7bd595f/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java#L151 `MapboxMap#getCameraForLatLngBounds` could return `null` if the map is not visible - this is obviously as designed because why would you want to interact with it if not present?

That's why I remarked the importance of using the lifecycle methods from `NavigationCamera` and `NavigationMapboxMap` i.e. `DynamicCamera` is a lifecycle aware component which doesn't mean anything if the map is not foregrounded. Does that make sense?

Maybe we should remove the `null` check altogether and work on a solution in which these classes are harder to be misused. The challenge here is that `NavigationMapboxMap` and `NavigationCamera` go hand by hand so it's not trivial / simple.

**Comment by Guardiola31337** [comment]
@andrlee 
Yeah, you're right but as I mentioned https://github.com/mapbox/mapbox-navigation-android/pull/1979#discussion_r295845350 the camera doesn't mean anything without the map, they should obey the same lifecycle, if no map you cannot do anything with the camera (at least you're not suppose to) that's why `clearMap` (and lifecycle methods from `NavigationCamera` and `NavigationMapboxMap`) are exposed so you can take care of the lifecycle and prevent any unexpected behaviors.

So the question here is if we want to work on a solution in which these classes are harder to be misused right now. As I mentioned the challenge here is that `NavigationMapboxMap` and `NavigationCamera` go hand by hand so it's not trivial / straightforward. What do you think?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java (hunk 1 above)
Comment (andrlee) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java]: imho in this case returning a valid ref of `CameraPosition` that represents an invalid state of camera is better than returning a `null` but i don't know all under the hood details, so i can't say if it's feasible.

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@ Mapbox welcomes participation and contributions from everyone.
 
 ### v0.41.0 - June 26, 2019
 
+* Fix DynamicCamera#CameraPosition.zoom NPE [#1979](https://github.com/mapbox/mapbox-navigation-android/pull/1979)
```
Comment (andrlee) [inline CHANGELOG.md]: btw, why are you doing this with every PR?

File: libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java (hunk 1 above)
Comment (Guardiola31337) [reply libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java]: Yeah, I know what you mean, creating a `CameraPosition` Null Object would be ideal. There's this [`CameraPosition#DEFAULT`](https://github.com/mapbox/mapbox-gl-native/blob/da69a88c04fcd7e93507dde74ffbc4e0fbd57210/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java#L21) constant that we could use here. Great idea! Although we cannot get rid off the `null` check completely because [`MapboxMap#getCameraForLatLngBounds`](https://github.com/mapbox/mapbox-gl-native/blob/da69a88c04fcd7e93507dde74ffbc4e0fbd57210/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L1420-L1422) is `@Nullable`, we'd need to move it to right before returning the `CameraPosition` https://github.com/mapbox/mapbox-navigation-android/blob/156e6a7aafe3bb603ac7c0ba28a322e0925b7a8d/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/camera/DynamicCamera.java#L148 ¯\\\_(ツ)\_/¯

File: CHANGELOG.md (hunk 2 above)
Comment (Guardiola31337) [reply CHANGELOG.md]: So we don't need to go over all the PRs that got merged and include them in the `CHANGELOG` pre-release i.e. long story short to improve the release process 😉

We used to have a checkbox in the release checklist to do this 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1920 and it was a hard task that made the release process slower so we thought that could be done incrementally on every PR, making the process more straightforward. This was a quick improvement that didn't involve any extra automation, ideally this should be autogenerated as part of the release build.
