### PR TITLE
Kyv alternatives cache limit to 3 portion

### LINKED ISSUE #5308: RouteAlternativesCacheManager accumulates unlimited amount of routes
**Android API:**
**Mapbox Navigation SDK version:** 2.0.1

### Steps to trigger behavior

 1. Start active guidance with `RouteOptions.enableRefresh` enabled.
 2. Wait until app is crashed with OOM.

### Expected behavior
Should RouteAlternativesCacheManager save only a few last routes?

### PR DESCRIPTION
**Pull request by RingerJK**
### Description
RouteAlternativesCacheManager: limit cache to 3 portions (avoid OOM Exception)

Closes #5308 

```
<changelog>Fixed OOM Exception because of non-limited internal cached of alternative routes</changelog>
```

cc @zeac

### CODE REVIEW

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt [hunk 1]
```diff
@@ -21,14 +22,24 @@ internal class RouteAlternativesCacheManager(
         }
     }
 
+    @VisibleForTesting
+    internal companion object {
+        internal const val CACHE_SIZE = 3
+    }
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:28]: You wouldn't need to make it visible for testing if it was a constructor parameter:
```kotlin
internal class RouteAlternativesCacheManager(
    navigationSession: NavigationSession,
    cacheSize: Int,
)
```

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt [hunk 2]
```diff
@@ -21,14 +22,24 @@ internal class RouteAlternativesCacheManager(
...
     init {
         navigationSession.registerNavigationSessionStateObserver(sessionStateObserver)
     }
 
     fun push(alternatives: List<DirectionsRoute>) {
-        cachedAlternatives.addAll(alternatives)
+        if (cachedAlternatives.size == CACHE_SIZE) {
+            cachedAlternatives.remove()
+        }
+        cachedAlternatives.add(alternatives)
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:38]: You use `ConcurrentLinkedQueue` but this method doesn't seem like a thread safe. Can `RouteAlternativesCacheManager` be accessed from multiple threads?

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt [hunk 3]
```diff
@@ -21,14 +22,24 @@ internal class RouteAlternativesCacheManager(
...
     }
 
     fun areAlternatives(routes: List<DirectionsRoute>): Boolean =
-        routes.map { it in cachedAlternatives }.any { it }
+        cachedAlternatives.flatten().let { cacheList ->
+            return@let routes.map { it in cacheList }.any { it }
+        }
```
Comment (VysotskiVadim) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:44]: what does the method do? does it return true if any of `DirectionsRoute` from the `routes` is present in any of cached `alternatives` ?

If so, maybe this one is easier to read?
```suggestion
        cachedAlternatives.any { cachedAlternative ->
            routes.any { cachedAlternative.contains(it)  }
        }
```

**Review by VysotskiVadim — APPROVED** [review]
LGTM

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt (hunk 1 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:28]: I wouldn't provide an option to setup cache size outside

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt (hunk 2 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:38]: nah, the method is consumed by router callback only

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt (hunk 3 above)
Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesCacheManager.kt:44]: yeah, looks good 👍
