### PR TITLE
Prevent NavigationNotification update after unregistered

### LINKED ISSUE #1116: Errors occur after navigation
**Android API:** N/A
**Mapbox Navigation SDK version:** 0.16.0-SNAPSHOT

### Steps to trigger behavior

 1. I am using an activity with navigationView for several cycles / routes, I am starting the next part some metres before the end of the current route. (I have to admit I have not figured out the best way to do that, I am having issues especially with listeners not triggering because my starting the next part is not smooth, tips concerning that are also appreciated.)
 2. After stopping the navigation sometimes errors occur. I can't really provide a definite guide to reproduce them.

### Expected behavior
No errors
### Actual behavior
Sometimes this crash occurs:
```
2018-07-17 22:50:10.792 29855-29855/com.................................. E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.................................., PID: 29855
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.services.android.navigation.v5.navigation.notification.NavigationNotification.updateNotification(com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:21)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

that one occurs more often, but the app does not crash at least:

```
2018-07-18 17:00:42.271 3918-3918/com.mapbox.services.android.navigation.testapp E/MapboxSpeechPlayer: java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.stopMediaPlayerPlaying(MapboxSpeechPlayer.java:141)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy(MapboxSpeechPlayer.java:95)
        at com.mapbox.services.android.navigation.ui.v5.voice.SpeechPlayerProvider.onDestroy(SpeechPlayerProvider.java:68)
        at com.mapbox.services.android.navigation.ui.v5.voice.NavigationSpeechPlayer.onDestroy(NavigationSpeechPlayer.java:81)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.deactivateInstructionPlayer(NavigationViewModel.java:364)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.onDestroy(NavigationViewModel.java:97)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.shutdown(NavigationView.java:574)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:169)
        at com.mapbox.services.android.navigation.testapp.activity.navigationui.EmbeddedNavigationActivity.onDestroy(EmbeddedNavigationActivity.java:147)
        at android.app.Activity.performDestroy(Activity.java:6881)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1116 Regression from #1066 

Added a boolean to prevent notification updates after the notification has been shut down.

### CODE REVIEW

**Comment by Guardiola31337** [comment]
@danesfeder this would only fix the first crash reported in #1116 right?
If that's correct, should we create a new ticket for the second crash? Noting because you added `Closes #1116` and that would close the issue completely.

**Comment by Guardiola31337** [comment]
> should we create a new ticket for the second crash?

I've just 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1116#issuecomment-406003585 Thanks @danesfeder 🙏

**Comment by Guardiola31337** [comment]
> I've just 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1116#issuecomment-406003585

Tracking in https://github.com/mapbox/mapbox-navigation-android/issues/1119

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationNotificationProvider.java [hunk 1]
```diff
@@ -8,6 +8,7 @@
 class NavigationNotificationProvider {
 
   private NavigationNotification navigationNotification;
+  private boolean isUpdating = true;
```
Comment (Guardiola31337) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationNotificationProvider.java]: NIT - what about `shouldUpdate` instead? It sounds better to me. By default, `shouldUpdate`? Yes - `true` After shutting down, `shouldUpdate`? No - `false`
What do you think?
