### PR TITLE
ReplayRouteLocationEngine: default init `lastLocation` by own provider

### LINKED ISSUE #2514: ReplayRouteLocationEngine crashes when calling startTripSession early
**Mapbox Navigation SDK version:** 1.0.0

### Steps to trigger behavior

 1. Create an app that uses ReplayRouteLocationEngine
 2. Create a mapbox navigator and call startTripSession early

### Expected behavior
Does not crash

### Actual behavior
Crashes with stack trace
```
2020-02-26 17:29:36.733 9190-9190/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.example, PID: 9190
    kotlin.UninitializedPropertyAccessException: lateinit property lastLocation has not been initialized
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.getLastLocation(ReplayRouteLocationEngine.kt:93)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.startLocationUpdates(MapboxTripSession.kt:108)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.start(MapboxTripSession.kt:98)
        at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:179)
        at com.mapbox.example.MyViewModel.startTripSession(MyViewModel.kt:123)
```

This should be nullable. Please don't make a default 0,0 location that makes the app think we're in the ocean :)
https://github.com/mapbox/mapbox-navigation-android/blob/c325d9d2531a008f87cc14945edf69c3daf2f602/libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt#L33
```

### PR DESCRIPTION
**Pull request by RingerJK**
## Description

_ReplayRouteLocationEngine_ crashes on `lastLocation` is not initialized

Closes #2514 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt [hunk 1]
```diff
@@ -30,7 +30,7 @@ class ReplayRouteLocationEngine(
     private lateinit var mockedLocations: MutableList<Location>
     private lateinit var dispatcher: ReplayLocationDispatcher
     private lateinit var replayLocationListener: ReplayRouteLocationListener
-    private lateinit var lastLocation: Location
+    private var lastLocation = Location(REPLAY_ROUTE)
```
Comment (kmadsen) [inline libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt]: `lastLocation = Location(REPLAY_ROUTE)` will create a location with valid location coordinates (0,0)

this means when `beginReplayWith` starts, it will start in the ocean
```
    private fun beginReplayWith(callback: LocationEngineCallback<LocationEngineResult>) {
        route?.let {
            start(it, callback)
        } ?: point?.let {
            startRoute(it, lastLocation, callback)
        } ?: callback.onFailure(Exception("No route found to replay."))
    }
```

we should suspend until the first valid location is received to begin the replay

Comment (RingerJK) [reply libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt]: it's a tricky point just to avoid crash, need set route before start routing
