### PR TITLE
Fix #1201: the stepPrimaryText doesn't have enough width in landscape mode

### LINKED ISSUE #1201: Abbreviations not working properly in landscape mode
The same phone actually shows more text in portrait than in landscape, as you can see in the screenshots. These were taken on a Pixel 2 XL.

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #1201: the stepPrimaryText doesn't have enough width in landscape mode

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Better support landscape mode.

### Implementation

Landscape the primary and secondary text are in same line. Both TextView's width is dynamic
and determined during runtime. This PR assigns maxWidth to each TextView and check fit by
using textView.getMaxWidth() instead of use textView.getWidth().

## Testing

1. Use the location in #1201 to verify the same road name is shown correctly.
Screenshot_1591404065

2. Use location that will also have `secondaryText` so verify the fix also work in both cases.
Screenshot_1591404126
Screenshot_1591404212

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java [hunk 1]
```diff
@@ -976,18 +976,33 @@ private void updateDataFromBannerText(@NonNull BannerText primaryBannerText, Ban
   }
 
   private void loadPrimary(BannerText primaryBannerText) {
-    stepPrimaryText.setMaxLines(2);
+    if (!ViewUtils.isLandscape(getContext())) {
```
Comment (JunDai) [inline libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: @Guardiola31337 - this change should fix the https://github.com/mapbox/mapbox-navigation-android/issues/1672

Since I don't have such long road info, can you help to verify?

Comment (abhishek1508) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: @JunDai 
I couldn't reproduce [#1672](https://github.com/mapbox/mapbox-navigation-android/issues/1672) with the master branch itself. I don't think it's an issue

Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: as I discussed with @Guardiola31337 today, he will double check #1672 

I just searched but couldn't find such road info at my side. But from code, I think #1672 might be still there. This line can make sure it's fixed.

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java [hunk 2]
```diff
@@ -976,18 +976,33 @@ private void updateDataFromBannerText(@NonNull BannerText primaryBannerText, Ban
...
     loadTextWith(primaryBannerText, stepPrimaryText);
   }
 
   private void loadPrimaryAndSecondary(BannerText primaryBannerText, BannerText secondaryBannerText) {
     stepPrimaryText.setMaxLines(1);
     stepSecondaryText.setVisibility(VISIBLE);
     adjustBannerTextVerticalBias(0.65f);
+
+    if (ViewUtils.isLandscape(getContext())) {
+      int primaryTextMaxWidth = (int) (instructionLayoutText.getWidth() * 0.75);
```
Comment (abhishek1508) [inline libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:997]: Magic Number 0.75. Can we extract it out in a separate constant, so that it is easy to understand it's need?

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java (hunk 1 above)
Comment (abhishek1508) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: I think the thing we first need to confirm is whether the information should be displayed in 1 line only or it can be taken to 2 lines. As shown in #1672, is the requirement to make sure the road name was displayed properly in 2nd line or was the requirement to ellipsize the text in 1 line itself. Also, if there is no `secondaryText` then the `primary text` is allowed to be displayed in 2 lines as per existing logic in master branch. This makes sense to me, because since there is no secondary text then we can very well display the primary text in 2 lines. With the above logic change introduced in this PR, the existing logic will break.
cc @JunDai @Guardiola31337

Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: I would say the existing logic doesn't mean to show the primaryText in two lines if no secondaryText in landscape mode, because the landscape mode doesn't have enough space to show two lines. You could check the layout file.
* portrait mode, the primaryText and secondaryText are displayed in separate lines that's why we set primaryText's maxLines to 2 when secondaryText is absent.
* landscape mode, due to the limitation of the height of the screen, but in the other hand we get more space in width, we show primaryText and secondaryText in one line. 

If we want to show two lines, we need to either increase the height or decrease the font. Which we could do, but not good IMO.

Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: > as I discussed with @Guardiola31337 today, he will double check #1672 

Confirmed that I wasn't able to reproduce anymore 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1672#issuecomment-640618473

Comment (abhishek1508) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: Yes exactly right. The current logic only handles portrait mode. But with your changes it will only handle the landscape mode and not the portrait mode since you check for `isLandscape` and only then assign maxLines=2, which in my opinion is not right because portrait mode needs 2 lines more than landscape. Since @Guardiola31337  was able to confirm that #1672 is not an issue anymore, let's revert this change which is trying to fix #1672. 
cc @JunDai

Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: @abhishek1508 
> Since @Guardiola31337  was able to confirm that #1672 is not an issue anymore, let's revert this change which is trying to fix #1672. 

Didn't OP aim to fix https://github.com/mapbox/mapbox-navigation-android/issues/1201? It's different from https://github.com/mapbox/mapbox-navigation-android/issues/1672

cc @JunDai

Comment (abhishek1508) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: @Guardiola31337 I meant only this particular change that is trying to fix #1672. Not the complete PR

Comment (Guardiola31337) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: Ohh got it. Makes sense 👍

Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: > The current logic only handles portrait mode. 

Why the current logic only handles portrait mode? Isn't it set to 2 lines for both landscape and portrait mode?

> But with your changes it will only handle the landscape mode and not the portrait mode since you check for `isLandscape` and only then assign maxLines=2, which in my opinion is not right because portrait mode needs 2 lines more than landscape.

Can you check my change again? Isn't it setting the maxLines to 2 only for portrait?

I can revert this change if @Guardiola31337 can't reproduce this issue. But I would think there is risk that #1672 could happen on some devices as the code suggests.

cc @abhishek1508

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java (hunk 2 above)
Comment (JunDai) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:997]: yes, it's a magic number indeed. I can update it.

File: libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java (hunk 1 above)
Comment (abhishek1508) [reply libnavigation-ui/src/main/java/com/mapbox/navigation/ui/instruction/InstructionView.java:979]: Let's go with it 👍
