### PR TITLE
fix IndexOutOfBoundsException in MapboxRouteLineUtils

### LINKED ISSUE #4833: IndexOutOfBoundsException in MapboxRouteLineUtils
**Android API: 29 (Android 10), 30 (Android 11)**
**Mapbox Navigation SDK version: 2.0.0-rc.1**

Our Crashlytics detected a crash originating from Navigation SDK. 
As of Sep 16 2021,  we only recorded 3 crashes (out of 1.23K installs at 25% rollout).

### Repro steps
Unfortunately we don't have exact repro steps for this crash. We can only assume the app state based on the captured stacktrace.  Judging from it, the crash could have happened either on Directions Selection screen or on Turn-by-turn navigation screen.

To start turn-by-turn navigation in straightaway:
1. Run Straightaway app
2. Add at least one stop
3. Start a route by pressing "Start route"
4. Start navigation by pressing "Navigate"
5. (potential crash point) You should land on Direction Selection screen. From here select proposed route and press GO.
6. (potential crash point) You should start Turn-by-turn navigation session.

Few notes about Straightaway implementation:
- `mapboxNavigation.startTripSession()` is called only on Turn-by-turn navigation screen
- Only first `DirectionsRoute` line is rendered on Turn-by-turn navigation screen
  ```
  // from Turn-by-turn navigation fragment
  private val routesObserver = object : RoutesObserver {
          override fun onRoutesChanged(routes: List<DirectionsRoute>) {
              if (activity == null || routes.isEmpty()) return
  
              try {
                  // MapboxNavigation might load multiple directions on rerouting.
                  // We are only interested in primary directions that are always at index 0.
                  val lines = listOf(RouteLine(routes.first(), null))
                  routeLineAPI.setRoutes(lines, navConsumer)
                  updateCameraToFollowing()
              } catch (e: Throwable) {
                  logW(TAG, "onRoutesChanged: Error updating route line and camera.", e)
              }
          }
      }
  ```
- Directions Select screen renders all DirectionRoute lines.

### Stacktrace from Crashlytics report:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 980, Size: 980
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.getRouteLineAnnotationExpressionData$libnavui_maps_release(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$getRouteLineAnnotationExpressionDataFromCache$1.invoke(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$getRouteLineAnnotationExpressionDataFromCache$1.invoke(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:1)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultHandler.invoke(CacheResultUtils.java:2)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$cacheResult$2.invoke(CacheResultUtils.java:1)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.calculateRouteLineSegments(MapboxRouteLineUtils.java:1)
       at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi$buildDrawRoutesState$4$segmentsDef$1.invokeSuspend(MapboxRouteLineApi.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

### PR DESCRIPTION
**Pull request by Zayankovsky**
### Description
Fixes #4833. The problem was in the check `index > trafficCongestion.size`. It should be `index >= trafficCongestion.size`. Also simplified code a bit using kotlin smart casts. 

### Changelog
```
<changelog>Fixed `IndexOutOfBoundsException` in `MapboxRouteLineUtils`</changelog>
```

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Nice catch! Could you add a regression unit test as well?

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt [hunk 1]
```diff
@@ -522,9 +522,9 @@ object MapboxRouteLineUtils {
                 val isInAClosure = closureRanges.any { it.contains(index) }
                 val congestionValue: String = when {
                     isInAClosure -> RouteConstants.CLOSURE_CONGESTION_VALUE
-                    trafficCongestion?.isEmpty() ?: true -> RouteConstants.UNKNOWN_CONGESTION_VALUE
-                    index > trafficCongestion?.size ?: 0 -> RouteConstants.UNKNOWN_CONGESTION_VALUE
-                    else -> trafficCongestion?.get(index) ?: RouteConstants.UNKNOWN_CONGESTION_VALUE
+                    trafficCongestion.isNullOrEmpty() -> RouteConstants.UNKNOWN_CONGESTION_VALUE
+                    index >= trafficCongestion.size -> RouteConstants.UNKNOWN_CONGESTION_VALUE
```
Comment (RingerJK) [inline libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt:526]: could we cover it by tests?

**Comment by Zayankovsky** [comment]
> Nice catch! Could you add a regression unit test as well?

Added.

File: libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt (hunk 1 above)
Comment (LukasPaczos) [reply libnavui-maps/src/main/java/com/mapbox/navigation/ui/maps/internal/route/line/MapboxRouteLineUtils.kt:526]: @cafesilencio do you know why in some situations the congestion list can be shorter than the distances list when both are available for a specific route leg? Is there some filtering that we do, or is this the way data comes in from the Directions API?

**Review by LukasPaczos — APPROVED** [review]
LGTM

**Comment by cafesilencio** [comment]
> @LukasPaczos "do you know why in some situations the congestion list can be shorter than the distances list..."

I've always seen a 1 to 1 relationship between the distance and congestion arrays.

**Comment by LukasPaczos** [comment]
In this case, why did we have this check (`index [of the distance array] > trafficCongestion.size`) in the first place?

**Comment by cafesilencio** [comment]
@LukasPaczos It looks like the cause is a line I added recently that filters out distance elements where the distance is 0.0.  That throws off the elements between the distance array and the congestion array.  I have an example of a two leg route where one of the distance arrays has a value of 0.0.  That was causing other problems so I modified the code to filter those out. However, looking at the implementation now I can see that filtering out that value reduces the collection size of the `forEachIndexed` loop but isn't adjusting the index value for reading the congestion array.   

The offending line:
`leg.annotation()?.distance()?.filter { it > 0.0 }?.forEachIndexed { index, distance ->...`

I created an issue here:  https://github.com/mapbox/mapbox-navigation-android/issues/4877

**Comment by Zayankovsky** [comment]
> However, looking at the implementation now I can see that filtering out that value reduces the collection size of the `forEachIndexed` loop but isn't adjusting the index value for reading the congestion array.
> 
> The offending line:
> `leg.annotation()?.distance()?.filter { it > 0.0 }?.forEachIndexed { index, distance ->...`


That makes the index smaller, but the `IndexOutOfBoundsException` was thrown because the index was too large. So that's probably not the actual reason.
