### PR TITLE
fixed endnavigation issue

### LINKED ISSUE #68: Second navigation session not initializing correctly

### PR DESCRIPTION
**Pull request by cammace**
Closes #68 

Fixes issue with navigationSession using old reference of service even after the service is destroyed.

### CODE REVIEW

File: navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java [hunk 1]
```diff
@@ -127,6 +128,17 @@ public void onStop() {
     if (isBound) {
       Timber.d("unbindService called");
       context.unbindService(connection);
+      isBound = false;
+    }
+  }
+
+  @Override
+  public void onProgressChange(Location location, RouteProgress routeProgress) {
+
```
Comment (zugaldia) [inline navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java]: nit: extra line

File: navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java [hunk 2]
```diff
@@ -127,6 +128,17 @@ public void onStop() {
...
+    // If the user arrives at the final destination, end the navigation session.
+    if (routeProgress.getAlertUserLevel() == NavigationConstants.ARRIVE_ALERT_LEVEL) {
+      System.out.println("working");
```
Comment (zugaldia) [inline navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java]: remove or replace with Timber

File: navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java [hunk 3]
```diff
@@ -438,7 +455,7 @@ public void onServiceConnected(ComponentName componentName, IBinder service) {
       if (alertLevelChangeListeners != null) {
         navigationService.setAlertLevelChangeListeners(alertLevelChangeListeners);
       }
-
+      progressChangeListeners.add(MapboxNavigation.this);
```
Comment (zugaldia) [inline navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java]: This doesn't seem right, the object is implementing a listener that is keeping track of. Also, the next line is always true because there always is at least one ProgressChangeListener. Could you elaborate why is this needed?

File: navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java [hunk 4]
```diff
@@ -403,7 +420,7 @@ public float getUserOriginBearing() {
    * @since 0.3.0
    */
   public MapboxNavigationOptions getMapboxNavigationOptions() {
-    return options;
+    return isServiceAvailable() ? navigationService.getMapboxNavigationOptions() : options;
```
Comment (zugaldia) [inline navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java]: Why do we have two different copies of options?

File: navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java (hunk 3 above)
Comment (cammace) [inline navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java]: The if null checks were leftovers from before when we didn't add the listeners to a list, I've removed them since the list are always set in the constructor. The MapboxNavigation objects listening in to get notified when the user arrives at the destination. When this occurs, the sessions, automatically ended. Otherwise, the service would continue running in the background even though the navigation sessions over. 

I'm not really happy with the current setup with everything being passed inside the onConnected callback since this is only called once when the service is first created, but I'll need more time to refactor.
